### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin✖

### ISSUE THREAD

**Issue by uniartisan** [nextcloud/documentserver_community#102]
I have downloaded the plugin from github and upload and unzip it to /nextcloud/www/nextcloud/apps/

It seems to be fine to set ONLYOFFICE and it shows:
![image](https://user-images.githubusercontent.com/31544054/77729432-9b597780-7039-11ea-8f90-51e348dd85f2.png)

but latter when i open a doc file, it seems to be broke down:
![image](https://user-images.githubusercontent.com/31544054/77729458-aa402a00-7039-11ea-8ff1-292f1aa3000a.png)
![image](https://user-images.githubusercontent.com/31544054/77729923-c2647900-703a-11ea-8ea2-966ddbb687ae.png)

I cant't find more useful information from Baidu or Google, so I come here to report my question.

I use docker to set up my nextcloud: linuxserver/nextcloud on my NAS: UNRAID.

**Comment by zichichi** [comment]
same problem on my server. Unraid + docker extcloud.

![image](https://user-images.githubusercontent.com/1170727/77819939-fd1fed00-70de-11ea-89a3-d8f2b90d70e9.png)

this is logs server nextcloud:

`[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: not found
 at <<closure>>

 0. /config/www/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php line 72
    OCA\DocumentServer\Document\ConverterBinary->run("")
 1. /config/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php line 34
    OCA\DocumentServer\Document\ConverterBinary->test()
 2. /config/www/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php line 89
    OCA\DocumentServer\SetupCheck->check()
 3. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\DocumentServer\Controller\StaticController->webApps("apps/api/documents/api.js")
 4. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\DocumentServ ... {}, "webApps")
 5. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "webApps")
 6. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\DocumentSe ... r", "webApps", OC\AppFramework\ ... {}, {path: "apps/api ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({path: "apps/api ... "})
 8. /config/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {path: "apps/api ... "})
 9. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/documents ... s")
10. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /apps/documentserver_community/web-apps/apps/api/documents/api.js
from 10.8.0.1 by christophe at 2020-03-28T09:27:41+00:00`

**Comment by bwoodworth** [comment]
I have the same issue as well.  New setup on NextCloud as a docker container.  Installed the ONLYOFFICE and Document Community Server apps.  I have the exact same error as @uniartisan

**Comment by develroo** [comment]
Is this problem fixed? Why are you closing it without a resolution? That is not how development works.

**Comment by uniartisan** [comment]
> Is this problem fixed? Why are you closing it without a resolution? That is not how development works.

Aha, I didn't think about it😕.
You can try to use onlyoffice's official docker first to solve this problem. Orz
I will reopen this issue later.

**Comment by develroo** [comment]
It that the official policy? In which case whoever is in charge of the documentation for the Nextcloud App needs to amend it to talk about 

1) using docker to install onlyoffice 

2) connecting a next cloud instance to it be it remote or on the same host.

**Comment by Exist2Resist** [comment]
Probably your proxy configuration. 
Are you using a reverse proxy?
I am and had this exact error till I fixed my onlyoffice swag conf.

**Comment by chmanie** [comment]
Is it correct that it won't work on docker setups with just installing the two apps? I am getting this error message and all the conflicting information that I'm getting is really confusing :(

**Comment by Exist2Resist** [comment]
> Is it correct that it won't work on docker setups with just installing the two apps? I am getting this error message and all the conflicting information that I'm getting is really confusing :(

It does work. I have it working with my Nextcloud and ONLYOFFICE both in docker containers.

**Comment by timmwille** [comment]
I have the same issue with Version 19.0.7 - just using the two apps seems to be the issue. Is it important in what order one has installed the two apps?
