### ISSUE TITLE
Update to onlyoffice 5.5.0

### ISSUE THREAD

**Issue by ashcoft** [nextcloud/documentserver_community#104]
Please update gradually after onlyoffice update

**Comment by jospoortvliet** [comment]
See https://github.com/nextcloud/documentserver_community/issues/94 - we're discussing with them to see if something can be done here. I personally think the editors we built into our mobile apps (that just use the webview) are probably a better option anyway, but some users might want the mobile apps.

**Comment by wurstsalat3000** [comment]
I’d like to add one specific bug which would be fixed with updating to 5.5:
https://github.com/ONLYOFFICE/DocumentServer/issues/682
Using `pyopenxl` with documents generated/modified by the currently shipped version is not possible.

**Comment by p-bo** [comment]
I would like to second this plea - in recently released 5.5.1 for instance, there is lot of improvements in translations (and even new languages added!). It would improve experience for non-english speaking users of Nexcloud Hub a lot.

**Comment by wurstsalat3000** [comment]
@jospoortvliet any update on this topic? I read the forum post you linked in #94, but it has been closed two months ago.
