### ISSUE TITLE
About certificate.crt certificate 

### ISSUE THREAD

**Issue by JRelland** [nextcloud/documentserver_community#106]
Hi, thank you for CDS

Our CDS is in a NextCloud installed with YUNOHOST with a Let's Encrypt certificate.

```
occ $ status
  - installed: true  - version: 18.0.2.2  - versionstring: 18.0.2  - edition:
```

As recommanded, I run

```
security:certificates:import /path/to/certificate.crt
certificate not found
```
Without "occ" otherwise I have this message: `Command "occ" is not defined`.

I tried

```
security:certificates
+-----------+-------------+--------------+-------------+-----------+
| File Name | Common Name | Organization | Valid Until | Issued By |
+-----------+-------------+--------------+-------------+-----------+
```

Thank you for any comment on how to install this certificate

even if OnlyOffice works well :)
https://jreservices.fr/nextcloud/apps/onlyoffice/474?filePath=%2FSpreadsheet (3).xlsx

Thank, Jrd from France

**Comment by icewind1991** [comment]
If it is already a valid Let's Encrypt certificate then there is no need to install it, that is only required for self signed certficiates
