### ISSUE TITLE
Can not install Community Document Server - cURL Error

### ISSUE THREAD

**Issue by JonasToth** [nextcloud/documentserver_community#11]
I am running my nextcloud on a local box with a docker-based installation (apache-image from the docker-examples), it is updated to nextcloud 18.

When trying to install the document server i get the following error:

```
cURL error 28: Operation timed out after 30000 milliseconds with 71258684 out of 305969549 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```
I do have internet connection and the error indicates, that only ~40% of some download worked, too.

This happens through the normal app-store installation and nothing more.
`docker-compose logs -f` does not give any more insights.

**Comment by rullzer** [comment]
Might be a timeout indeed. As the documentserver is quite large.

PLease fetch and extract the file manually: https://github.com/nextcloud/documentserver_community/releases/download/v0.1.1/documentserver_community.tar.gz

**Comment by NorryNew** [comment]
or see this:
https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603/11

**Comment by NorryNew** [comment]
Maybe there should be a permanent change in the installation for NC in the file lib/private/Http/Client/Client.php to the value: RequestOptions::TIMEOUT

**Comment by martin930** [comment]
switch to app directoy → "wget https://github.com/nextcloud/documentserver_community/releases/download/v0.1.1/documentserver_community.tar.gz"

then untar with "tar -xvzf documentserver_community.tar.gz"

Now the app can be installed vai Web-Interface

**Comment by JonasToth** [comment]
Thank you for the quick help and responses!
I do not have an issue with the fix, its just a bit extra work :/ Will this be required for all updates, too?
Maybe the timeout value could be adapted to the filesize to be downloaded or something like that?

**Comment by christianvw** [comment]
> Maybe there should be a permanent change in the installation for NC in the file lib/private/Http/Client/Client.php to the value: RequestOptions::TIMEOUT

I think so too. OnlyOffice and Nextcloud are now advertised as ready-to-go which they arent when having a moderate internet connection. 300MB is a really heavy if you consider some linux distros having just a few MBs.

**Comment by JonasToth** [comment]
For everyone else hitting this issue and using docker (and volumes):

When manually downloading the file and unpacking it, remember to set the proper permissions afterwards.
In my case, I did download and unpack as `root` and did afterwards `chown -R www-data:root documentserver_community` in the `nextcloud/apps` directory.
This depends of course on the user and permissions you use for your nextcloud. Just check with `ls -la` what the other directories use.

Now everything works fine! Thanks again.
