### ISSUE TITLE
Document Server installed but unable to use it

### ISSUE THREAD

**Issue by ghost** [nextcloud/documentserver_community#111]
I installed Document server (with some difficulties: I had to change the timeout in the configuration files of Nextcloud and to use CLI mode to install), but my installation does not work properly. When I want to create a document, I see the loading screen and then nothing happen and I receive the following message in my web browser: “The connection is too slow, some components have not been loaded. Please refresh the web page.” (take a look to the screenshot), whereas I use my server on my local Network with a good connection.

![image](https://user-images.githubusercontent.com/61425832/78533901-f9c8e780-77e9-11ea-9164-8971d17d575f.png)

**Comment by jospoortvliet** [comment]
So your server might be too slow or it is not x86. Look at CPU load on your server, memory usage - there might not be enough of either or both of those... Without more info there is nothing we can say about that.

**Comment by Ildegarde59** [comment]
My computer’s characteristics:
- RAM: 6 GB
- CPU: Intel Core 2 Quad Q8300 (4) @ 2.5 GHz (64 bits)
