### ISSUE TITLE
OnlyOffice: Button "back to file location" is missing on opening document

### ISSUE THREAD

**Issue by HFranz** [nextcloud/documentserver_community#115]
If I open document, button "Back to file location" (German: Dateispeicherort öffnen) on the upper right is missing. If I reload page, the button appears. See also screenshot.
![back to file location](https://user-images.githubusercontent.com/5477386/78770365-c5426080-798e-11ea-93fd-806deaab8422.JPG)

I have NC 18.0.3 with Document server and OnlyOffice (native integration NOT docker installation). I am not sure if it is a bug with NC / document server (interacting with OO) or a bug with OO itself.

**Comment by HFranz** [comment]
Same behavior with NC 18.0.6

**Comment by bes1002t** [comment]
In my humble opinion this button should be replaced with the common "X" button to close applications.
