### ISSUE TITLE
White page instead of editor (no docker)

### ISSUE THREAD

**Issue by microfx** [nextcloud/documentserver_community#118]
Hey!

I am really struggling finding out why this is not working anymore. There are no error messages (or at least I don't look at the right place). 

Only a white page is displayed instead of the ONLYOFFICE editor. Where could I start finding out what is causing it?

**Comment by Niclas-sol** [comment]
Same problem here. OnlyOffice and documentserver reinstalled, NC updated from 18.0.5 to 18.0.6 and now to 19 but still no response or error...
