### ISSUE TITLE
Missing spaces after opening of about.odf document

### ISSUE THREAD

**Issue by erikfdev** [nextcloud/documentserver_community#122]
After opening the NextCloud "about.odt" in NextCloud OnlyOffice, several space characters are missing.
"Nextcloud is the open" is shown as "Nextcloudistheopen" after the import.
[About.zip](https://github.com/nextcloud/documentserver_community/files/4529164/About.zip)

DocumentServer version:
Community Document Server 0.1.5
Operating System:
Linux Mint 19.3
Browser version:
Firefox 75.0
Chrome 81.0.

**Comment by thmo** [comment]
Duplicate of #116.

**Comment by lpilz** [comment]
I have the same problem

Nextcloud 19.0.2 (snap)
DocumentServer version: Community Document Server 0.1.7
Operating System: Ubuntu 18.04.5 LTS
Browser version: Firefox 75.0

**Comment by lpilz** [comment]
This seems to be an issue with the OnlyOffice renderer, since all spaces seem okay when downloading the file.
