### ISSUE TITLE
An Error has occurred while opening the file - ods/odt files

### ISSUE THREAD

**Issue by toehold** [nextcloud/documentserver_community#123]
Hi,

on Ubuntu 18.04 64bit with NC 18.04, OnlyOffice: 0.1.5 and Community Document Server: 0.1.5

When opening a ods/odt file get this error messge:

An Error has occurred while opening the file. It works for md or txt files.

Any ideas?

THanks a lot!

**Comment by toehold** [comment]
Solved! My Document Editing Service address was wrong!

**Comment by timmwille** [comment]
I have the same error

![grafik](https://user-images.githubusercontent.com/8081055/148126397-ed16dce6-391e-4d22-8ec6-9d772d36f297.png)


seems to be linked to here: https://github.com/nextcloud/server/pull/29900
