### ISSUE TITLE
could you help me? document_server community don´t work

### ISSUE THREAD

**Issue by julbroa-zz** [nextcloud/documentserver_community#125]
I have installed document_server by downloading and decompress on hosting and activate app but when tried create new document an error ocurred
![2020-05-03](https://user-images.githubusercontent.com/28205134/80922699-6d580900-8d44-11ea-8684-aa83aab90c37.png)

**Comment by romankh3** [comment]
I have the same issue.

**Comment by romankh3** [comment]
I found the problem!
there was a wrong settings for ONLYOFFICE. `Document Editing Service address` was wrong. it refers to `http` host without domain name.

When I changed it to my https URL with domain name it was fixed it.

**Comment by Philglo** [comment]
Great, I have the same problem. Where we have to change the domain name ? Thank you

**Comment by romankh3** [comment]
@Philglo, you need to go to **Profile** -> **Settings** -> in a left-bottom corner choose **ONLYOFFICE**.

**Comment by julbroa** [comment]
my settings are correct, with https and still not working.
