### ISSUE TITLE
Doesnt work in Safari 

### ISSUE THREAD

**Issue by NiTRoeSE** [nextcloud/documentserver_community#13]
Hi, i recognized that documentserver dont work in safari browser, but in firefox and chrome.
Safari just doesnt display the "editor".
Error message from browser console :

"Unrecognized Content-Security-Policy directive 'worker-src'."

<img width="1760" alt="Bildschirmfoto 2020-01-18 um 12 49 43" src="https://user-images.githubusercontent.com/24574743/72663354-06f7e680-39f2-11ea-90a7-eb680a3f4041.png">

Hope its possible to fix it.

Thanks for your work!

**EDIT:**

I researched a bit and it seems that this error / problem only occurs if option "open in same tab " is set in onlyoffice app. If i unset this option the editor loads in new tab correctly.

**Comment by Marcwa19197** [comment]
> Hi, i recognized that documentserver dont work in safari browser, but in firefox and chrome.
> Safari just doesnt display the "editor".
> Error message from browser console :
> 
> "Unrecognized Content-Security-Policy directive 'worker-src'."
> 
> <img alt="Bildschirmfoto 2020-01-18 um 12 49 43" width="1760" src="https://user-images.githubusercontent.com/24574743/72663354-06f7e680-39f2-11ea-90a7-eb680a3f4041.png">
> 
> Hope its possible to fix it.
> 
> Thanks for your work!
> 
> **EDIT:**
> 
> I researched a bit and it seems that this error / problem only occurs if option "open in same tab " is set in onlyoffice app. If i unset this option the editor loads in new tab correctly.

Hi!,
if you get this issue do you only see an white page? If so, try refreshing the Page (On Mac: command + R) this worked for me.

Also, i can confirm if i uncheck "open in same tab" it is working without an manual page refresh.

**Comment by LinneyS** [comment]
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/213

**Comment by icewind1991** [comment]
this is an upstream issue, please report with onlyoffice
