### ISSUE TITLE
Onlyoffice - doc with an image will never load

### ISSUE THREAD

**Issue by nuke-web3** [nextcloud/documentserver_community#136]
![image](https://user-images.githubusercontent.com/35669742/82395253-5e41ae00-9a08-11ea-9d1d-6b14203924b9.png)

---

Above is a capture of the likely error.

The file was working fine, until I attempted to upload an image, that took on one browser, but all others that tried to load the page again get to 100% load state, but then sit there. 

Using Firefox 76.0.1 and Brave (Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by NukeManDan** [comment]
![image](https://user-images.githubusercontent.com/35669742/82395584-0ce5ee80-9a09-11ea-80d1-265dbf00841d.png)
Console from brave
