### ISSUE TITLE
Spell checking not working.

### ISSUE THREAD

**Issue by N3tFX** [nextcloud/documentserver_community#14]
As the title says. Even though the button is checked on the toolbar, spell checking isn't working. No red lines appear under misspelled words and, also, nothing related with spell checking appears in the right click menu.

**Comment by martin930** [comment]
The dedicated version needs to do a rebuild after installing. (https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation.aspx#Spellchecker)

Maybe it's the same here?

**Comment by N3tFX** [comment]
For now I went back to using Onlyoffice from the docker server that works fine. I have come across to other bugs (that are already reported by other users) that, for now, makes it difficult for me to use the documentserver_community app. I will try again, after the devs have some time to squash these early bugs.

**Comment by djohannes** [comment]
@martin930 I used the Nextcloud community server app to install it and I don't even have a SpellChecker folder.

**Comment by ostasevych** [comment]
> @martin930 I used the Nextcloud community server app to install it and I don't even have a SpellChecker folder.
> EDIT:
> I noticed, that OnlyOffice normally shows you a little icon next to the document language if it supports spell check, but no language has this symbol. So there are just no spell check languages installed :/

Well... how to install them?
![image](https://user-images.githubusercontent.com/5199030/72733298-3e0bfa80-3ba0-11ea-93c0-0b09507c5a59.png)

**Comment by icewind1991** [comment]
Spell check is currently not supported

**Comment by djohannes** [comment]
> > @martin930 I used the Nextcloud community server app to install it and I don't even have a SpellChecker folder.
> > EDIT:
> > I noticed, that OnlyOffice normally shows you a little icon next to the document language if it supports spell check, but no language has this symbol. So there are just no spell check languages installed :/
> 
> Well... how to install them?
> ![image](https://user-images.githubusercontent.com/5199030/72733298-3e0bfa80-3ba0-11ea-93c0-0b09507c5a59.png)

In the meantime you can just setup OnlyOffice in a docker container, it took me 10 minutes yesterday, it also runs on the same server and supports spell check :)

**Comment by djohannes** [comment]
> Spell check is currently not supported

Thanks for the info! Is it planned to support it in the future?

**Comment by ostasevych** [comment]
Sorry for nube question: may I install it manually taking files from the full version of OnlyOffice? If yes, how?

**Comment by ostasevych** [comment]
What I found spell checking works using desktop client, which is a web wrapper...

**Comment by djohannes** [comment]
> Sorry for nube question: may I install it manually taking files/compiling from the full version of OnlyOffice? If yes, how?

As far as I know this isn't possible. Again, I'd suggest to run OnlyOffice in a docker (it's not tooo difficult) and link it to the Nextcloud, both can be on the same server. Then you also have spell check :)

**Comment by ostasevych** [comment]
> > Sorry for nube question: may I install it manually taking files/compiling from the full version of OnlyOffice? If yes, how?
> 
> As far as I know this isn't possible. Again, I'd suggest to run OnlyOffice in a docker (it's not tooo difficult) and link it to the Nextcloud, both can be on the same server. Then you also have spell check :)

This not a solution for me by now. Is it possible to recompile specifically the spellchrcker and add it somehow?
