### ISSUE TITLE
"ONLYOFFICE cannot be contacted. Please contact admin" after fresh install

### ISSUE THREAD

**Issue by BuilderGuy1** [nextcloud/documentserver_community#140]
Just did a fresh install of NC 18.04snap2 on Ubuntu 20.04 LTS.
After doing some basic setup and adding a few users I tried to create a Document and got the error "ONLYOFFICE cannot be contacted. Please contact admin".
Obviously this is a snap install.
I set the trusted domains in the config.php to be two addresses: one an IP address on my home network and the other the domain name for the server.
I have not made any other changes to the system.

**Comment by BastianBalthasarBux** [comment]
Looks like it's connected to:
#190
