### ISSUE TITLE
Community document server is not supported for this instance, please setup and configure an external document server - 32 bit setups are not supported

### ISSUE THREAD

**Issue by MetaLDarK** [nextcloud/documentserver_community#142]
Hello,
I use nextcloud 18.0.4 at OVH as part of a shared hosting.
I installed Community Document Server 0.1.5 and ONLYOFFICE 4.1.4.
I activated the 2 applications.
When I want to open office document present in my cloud, the following error message appears:
 "Community document server is not supported for this instance, please setup and configure an external document server" and "32 bit setups are not supported".

The result of the Linux commands:
lsof -p $$ | grep libc | awk '{print $ NF "--version"; } '| sh
GNU C Library (Debian GLIBC 2.19-18 + deb8u10) stable release version 2.19, by Roland McGrath et al.
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.4.
Compiled on a Linux 3.16.43 system on 2017-06-18.
Available extensions:
crypt add-on version 2.1 by Michael Glad and others
GNU Libidn by Simon Josefsson
Native POSIX Threads Library by Ulrich Drepper et al
BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.

uname -a
Linux ssh01.xxxxx.xxx.hosting.ovh.net 4.14.149-ovh-vps-grsec-zfs-classid # 1 SMP Mon Oct 14 07:43:53 CEST 2019 x86_64 GNU / Linux

The kernel of my linux server seems to be 64 bit.

Do you have any idea why I am getting these errors?
Can you help me please.
thank you in advance
Regards,

**Comment by icewind1991** [comment]
the 32bit warning should only be shown if the php installation is 32bit, you can verify this with `php -r 'echo PHP_INT_SIZE;'`

the "32bit issue" might also not be the cause of your issue, those checks are only done when the bundled binaries can't be ran.
