### ISSUE TITLE
warning: command substitution: ignored null byte in input

### ISSUE THREAD

**Issue by HLFH** [nextcloud/documentserver_community#143]
Hi,

I am using the git version on master branch.
When I use `make`, I am getting the following error:

> ➜  documentserver_community git:(master) ✗ make
VERSION=$(grep -ozP "DocsAPI\.DocEditor\.version\s*=\s*function\(\) *\{\n\s+return\s\'\K(\d+.\d+.\d+)" 3rdparty/onlyoffice/documentserver/web-apps/apps/api/documents/api.js) ;\
	sed -i "s/return '[0-9.]*'/return '$VERSION'/" lib/OnlyOffice/WebVersion.php
/bin/sh: avertissement :substitution de commande: octet nul ignoré en entrée

In English the error would give:
>warning: command substitution: ignored null byte in input

Can the Makefile be fixed?

Thanks,
HLFH

**Comment by djipco** [comment]
I am experiencing the same problem with the version of [documentserver_community](https://github.com/nextcloud/documentserver_community) that is currently in the repo (Nov 28, 2025).
