### ISSUE TITLE
Compatibility with NC 19

### ISSUE THREAD

**Issue by schniepp** [nextcloud/documentserver_community#144]
Maximum supported version at this point is v18.

**Comment by ArisuOngaku** [comment]
4d945026c4c3d6df46e5f3cf8b20c358be8ccd7b

**Comment by olegchensky** [comment]
4d94502 - don't helps.

**Comment by grondinm** [comment]
What's the status of having a new release pushed out? Seeing as this is now a major part of Nextcloud i can't understand why 19 would be pushed out without this app being ready...

**Comment by schniepp** [comment]
From the outside, it looks like Nextcloud is now pushing Collabora/CODE instead of OnlyOffice. With the release of NC 19, there was an app "Collabora Online - Built-in CODE Server". I am thinking this might be the entire document server installed as an app, just as they did with OnlyOffice for the release of NC 18. (I haven't tried it since; I have a standalone version of CODE installed on my machine.)
They now also support CODE/Collabora (LibreOffice online) as a companion tool to Talk. They seem to be pushing Talk hard, which makes sense, since many people currently need tools to work from home. At any rate, it looks to me like they are doing a 180, switching to LibreOffice quite radically, and just one release after having pushed OnlyOffice. I actually was surprised by the earlier push for OnlyOffice, since they are not really following the FOSS model, while NC and Libreoffice are. 
But I don't have any deeper insight. Just speculating from the outside by watching.

**Comment by grondinm** [comment]
Well then...thank you for pointing that out...SMH would be nice if these types of changes where announced...for me i only run an instance for myself but still...It does seem like they are doing what you say. I'm going to look at going the collabora way. I think i like that better anyways. Only went with OnlyOffice because that's what they bundled first and it was easier.

**Comment by schniepp** [comment]
@grondinm : I agree that this is not very transparent from NC's side. The idea that they are switching around important things so rapidly, and without warning or explanation is not exactly comforting. It's not only the admins who have to follow these changes, but then also the users. Would be better to have some planning security (or at least information). This is especially important since they are on a pretty rapid release frequency, and older versions are not supported long. (They just retired NC 16, which was released <14 months ago.)

**Comment by olegchensky** [comment]
https://github.com/CollaboraOnline/richdocumentscode/issues/26
The CODE not works too

**Comment by olegchensky** [comment]
0.1.6 ok

**Comment by kesselb** [comment]
https://nextcloud.com/blog/nextcloud-hub-brings-productivity-to-home-office/

It's announced there. The official release statement.

**Comment by greavette** [comment]
Hello Team,

I'm still confused by OnlyOffice Document Server.  Is this going to be supported and upgraded go forward as an easily installed App within Nextcloud?  I've been using OnlyOffice for a couple of years now first by installing my own but I prefer the App method as it "just works" and I don't have to have a separate server for OnlyOffice (I know I can install it on my Nextcloud but I'd rather not in case something goes south on OnlyOffice and I have all this stuff I don't need on my Nextcloud server).  

I'd be willing to try Collabora but when I installed the App and tried to use it locally it wouldn't work at all. 

What will be the go forward plan/status for OnlyOffice Document Server app?

Thank you.

**Comment by grondinm** [comment]
I can't get the update to install. The download exceeds some timeout and i can't find where that is set...

```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 120000 milliseconds with 205942372 out of 314307276 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I tried looking at the source of GuzzleHttp but i can't figure out how it gets that timeout...something stupid i'm missing i'm sure...

**Comment by jorsn** [comment]
> I can't get the update to install. The download exceeds some timeout and i can't find where that is set...

It's probably php `max_execution_time` or `max_input_time`. See #61.

**Comment by jorsn** [comment]
@Nextcloud devs:
Is this radical change of policy by Nextcloud related to OnlyOffice removing features (mobile editing) and deflecting any critique with irrational arguments (free mobile web app destroys destroys our business while free mobile native apps don't) and implicit legal threats, on top of intransparent licensing? See #94, onlyoffice/documentserver#805, https://opensource.stackexchange.com/questions/9481/is-onlyoffice-restricting-our-freedom-with-their-faq-agpl-v3/.
