### ISSUE TITLE
OCA\DocumentServer\Document\DocumentConversionException

### ISSUE THREAD

**Issue by makakken** [nextcloud/documentserver_community#149]
[index] Error: OCA\DocumentServer\Document\DocumentConversionException: namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
                                                                               ^
 at <<closure>>

 0. /var/www/example.com/apps/documentserver_community/lib/DocumentConverter.php line 123
    OCA\DocumentServer\Document\ConverterBinary->run("/tmp/oc_tmp_QKaaUf-.xml", null)
 1. /var/www/example.com/apps/documentserver_community/lib/Document/DocumentStore.php line 229
    OCA\DocumentServer\DocumentConverter->runCommand(OCA\DocumentServ ... {})
 2. /var/www/example.com/apps/documentserver_community/lib/LocalAppData.php line 100
    OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensitive parameters replaced ***")
 3. /var/www/example.com/apps/documentserver_community/lib/Document/DocumentStore.php line 232
    OCA\DocumentServer\LocalAppData->getReadWriteLocalPath(OC\Files\SimpleFS\SimpleFolder {}, Closure {})
 4. /var/www/example.com/apps/documentserver_community/lib/Controller/DocumentController.php line 179
    OCA\DocumentServer\Document\DocumentStore->convertForDownload(918111026, null, {c: "save",id: " ... "})
 5. /var/www/example.com/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\DocumentServer\Controller\DocumentController->download(918111026, {c: "save",id: " ... "})
 6. /var/www/example.com/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\DocumentServ ... {}, "download")
 7. /var/www/example.com/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "download")
 8. /var/www/example.com/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\DocumentSe ... r", "download", OC\AppFramework\ ... {}, {docId: "9181110 ... "})
 9. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({docId: "9181110 ... "})
10. /var/www/example.com/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {docId: "9181110 ... "})
11. /var/www/example.com/lib/base.php line 1008
    OC\Route\Router->match("/apps/documents ... 6")
12. /var/www/example.com/index.php line 38
    OC::handleRequest()

POST /apps/documentserver_community/3rdparty/onlyoffice/documentserver/downloadas/918111026?cmd=%7B%22c%22%3A%22save%22%2C%22id%22%3A%22918111026%22%2C%22userid%22%3A%22ocabjdjvxihu_makakken%22%2C%22outputformat%22%3A65%2C%22title%22%3A%22Zwischenbericht%20explore%2020200612.docx%22%2C%22nobase64%22%3Atrue%2C%22savetype%22%3A3%2C%22saveindex%22%3A1%2C%22userconnectionid%22%3A%22ocabjdjvxihu_xxx1%22%7D
from 94.134.91.66 by xxx at 2020-06-13T11:39:14+00:00

I really often experience such issues. Can Anyone tell me why my OnlyOffice Server, or the DocumentServerCommunity have so much problems while converting .docx files? is there something i can do?

**Comment by Bolli84** [comment]
Hi, this a specific filepart in many docx-files, which is not handled correctly. Until now, there is no workaround available.

**Comment by mr-bolle** [comment]
#100

**Comment by g4ndy** [comment]
Hi, i have same issue is there a way to detect which document is causing this problem? In logs i see only some temporary paths. Thank you!

**Comment by doc75** [comment]
@g4ndy , on my side here is how I do to identify and fix the issue.

**Warning: This procedure is not official. Use it at your own risk. Always perform a backup before running such procedures.**

I check in nextcloud.log and you should see at the end of the error message, you should see something like that:
```json
    "File": "/var/www/html/custom_apps/documentserver_community/lib/Document/ConverterBinary.php",
    "Line": 64,
    "CustomMessage": "Error while applying changes for document 3878975257"
```

When you have the number (3878975257 in my example), you can go inside the directoy:
`data/appdata_oc<randomstring>/documentserver_community`
And you should see a directory named `doc_3878975257`
In this directory you have the `owner` file which contains the id of the user the file belongs to.
I can also find a saved.docx that could allow you to find out the file it is issued from.

To remove the error in my logs, I am usually deleting the directory `doc_3878975257`.
And then you need to remove associated lines in the oc_filecache table.

First I check the lines with:
```sql
select * from oc_filecache where path LIKE '%doc_3878975257%';
```

Then, if the lines are fine for me, I perform the delete with:
```sql
delete from oc_filecache where path LIKE '%doc_3878975257%';
```

**Comment by g4ndy** [comment]
@doc75  Thank you very much!

**Comment by Githopp192** [comment]
@doc75 - good job, but i think this should be part of an official OnlyOffice Maintenance Tasks.
Why not make a feature request about ? (because this threat is very old and every version of Nextcloud/OnlyOffice has got this issue (i think it is not a functional issue)).

**Comment by doc75** [comment]
@Githopp192 not sure in which repo this feature request should be made. Especially since this repo seems not really maintained actively and that the issue also arise when using a separate onlyoffice container. Any idea ?
