### ISSUE TITLE
how to activate "secret"

### ISSUE THREAD

**Issue by martin930** [nextcloud/documentserver_community#15]
The server is reachable from "outside".

In the dedicated server version it is possible to add a secret key in the local.json. 

Unfortunately, this file doesn't exit in the app-version. Is there a way to activate the secret passphrase? 

Thanks in advance

**Comment by poVoq** [comment]
I don't think this is relevant to the simplified app version of the Document Server. Have you confirmed that it is reachable for the outside as a standalone Document Server?

**Comment by martin930** [comment]
Thank you.

If I use the URL https://nextcloud/apps/documentserver_community/ you can save the settings (no error message) at another server.

But if I try to open a document I get a ”Content Security Policy" Message (Firefox). So you're right, maybe there is no need for that!

**Comment by martin930** [comment]
BUT: The fact that the connection can be saved without errors indicates that the server is reachable

**Comment by simphide** [comment]
is there anything new regarding this topic?

**Comment by icewind1991** [comment]
even if the outside server is able to communicate with the internal document server, the document server cannot be used to load documents for the outside server

**Comment by simphide** [comment]
what about internal documents? or are they protected via nextcloud?

**Comment by icewind1991** [comment]
the documentserver will only open documents that the user has access to
