### ISSUE TITLE
Self-signed certificate with letsencrypt returns error

### ISSUE THREAD

**Issue by d0m1n1q0** [nextcloud/documentserver_community#153]
Hi need help please.
Using letsencrypt certificates and crt's are not available.
occ with fullchain.pem returns certificate not found.

Command issued sudo -u http php occ security:certificates:import /path/to/fullchain.pem

Appreciate response.

Tks

**Comment by talheim-it** [comment]
@d0m1n1q0 can you give us a bit more information about your setup?

That would help a lot first.
