### ISSUE TITLE
IMAGES become BLACK BOXES and / or are CROPPED INCORRECTLY when saving as PDF

### ISSUE THREAD

**Issue by unamundan** [nextcloud/documentserver_community#156]
**Do you want to request a feature or report a bug?**
BUG

**What is the current behavior?**
Imported / placed images become BLACK BOXES when saving as PDF.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a document. Import / place an image. Download the document as a PDF. Placed images are black boxes.

**What is the expected behavior?**
Placed images appear properly in exported PDFs.

**Did this work in previous versions of DocumentServer?**
Unknown

**DocumentServer version:**
OnlyOffice Document Server 0.1.7 with OnlyOffice Nextcloud app 4.3

**Operating System:**
Nextcloud 19.0 running on Ubuntu 18.04.4 LTS

**Browser version:**
Firefox 77.0.1 x64 on macOS 10.13.6

It works using Safari 12.1.1 (13607.2.6.1.2) and Tor 9.5 x64 (based on Mozilla Firefox 68.9.0esr) but using either introduces a DIFFERENT problem: images are cropped incorrectly.

(For privacy, I avoid Chrome.)

**Comment by parrenin** [comment]
Same problem for me.
When I upload the attached pdf file to NextCloud, the image in it does not appear correctly when viewed in a browser: it is cropped.
If I display the local pdf file, the image does appear correctly.

[test-NextCloud.pdf](https://github.com/nextcloud/documentserver_community/files/5803838/test-NextCloud.pdf)
