### ISSUE TITLE
ONLYOFFICE cannot be reached in my host domain

### ISSUE THREAD

**Issue by smartsistemi** [nextcloud/documentserver_community#157]
Hello, i’m here because i have a problem with onlyoffice and CDS integrated in my Nextcloud installation that i don't understand how to solve.
I have installed Community Document Server in Nextcloud, then i have installed ONLYOFFICE and configured it (as the screenshot attached).
![1](https://user-images.githubusercontent.com/5877745/85864387-c2545080-b7c4-11ea-92e7-b68837e537b7.jpg)

Now, when i click on document  it can creat a new document (as Document, Spreadsheet or Presentation) but i cannot open the document to modify (as the screenshot attached) because it returns the error ‘ONLYOFFICE cannot be reached. Pleas contact admin’
![2](https://user-images.githubusercontent.com/5877745/85864420-cda77c00-b7c4-11ea-84fb-4d2bdd57e17a.jpg)

Please, can you help me?

This is my space host:
|Sistema operativo:|Linux 3.10.0-862.2.3.el7.x86_64 x86_64|
|CPU:|Intel® Xeon® Silver 4116 CPU @ 2.10GHz (48 cores)|
|Memoria:|125.33 GB|

This is my PHP version:
Versione: 7.3.17
Limite memoria: 512 MB
Tempo massimo di esecuzione: 3600
Dimensione massima caricamento: 250 MB

This is my SQL version:
Tipo: mysql
Versione: 5.7.25

I have to add that i have the same problem with another my site host (with other maintainer) and with all the browsers.
I do all the configurations but when i arrive to create and then to modify my document Onlyoffice cannot be reached

**Comment by maurice1902** [comment]
Having the same problem using Nextcloud 19.0.2.
Richtig before the upgrade to 19.0.2 all worked fine with 18.0.8.

**Comment by bwoodworth** [comment]
Same issue here.  Brand new Nextcloud install in docker.  Here is the error in the log:
```

Error	documentserver_community	OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: not found

    /config/www/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php - line 72:

    OCA\DocumentServer\Document\ConverterBinary->run("")

    /config/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php - line 34:

    OCA\DocumentServer\Document\ConverterBinary->test()

    /config/www/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php - line 89:

    OCA\DocumentServer\SetupCheck->check()

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\DocumentServer\Controller\StaticController->webApps("apps/api/documents/api.js")

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Document ... {}, "webApps")

    /config/www/nextcloud/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Document ... {}, "webApps")

    /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Docume ... r", "webApps", OC\AppFramew ... {}, { path: "app ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ path: "app ... "})

    /config/www/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { path: "app ... "})

    /config/www/nextcloud/lib/base.php - line 1007:

    OC\Route\Router->match("/apps/docum ... s")

    /config/www/nextcloud/index.php - line 37:

    OC::handleRequest()
```

**Comment by BastianBalthasarBux** [comment]
I think this is related to this one:
https://github.com/nextcloud/documentserver_community/issues/190
