### ISSUE TITLE
Document / table / presentation is not opened

### ISSUE THREAD

**Issue by docmcfly** [nextcloud/documentserver_community#159]
Hello, 

I have Nextcloud 18.0.6 on a Debian Buster system (x86). When I install the "Community Document Server" (manually or via Nextcloud), it takes a long time but it seems that everything works. 
But when I try to open a document (or a table or a presentation), ONLYOFFICE is loaded, I see the office interface, but no document. Instead, only in the middle of the screen is written: "Document is being loaded" and that for hours. :-(

Has anyone ever had such a behavior? Did I miss something in the requirements? 

Thanks for helpful answers...
best regards 
Clemens 

PS: the demo documentserver works.

**Comment by sbellm** [comment]
Same here after update to version 4.3.0

**Comment by docmcfly** [comment]
Thanks for the confirmation. 

What puzzles me most about this problem No error message and no log entry. 

Or have you found something that can be evaluated?

Greetings
Clemens

**Comment by sbellm** [comment]
Have to correct myself, it was only one document. Restored it from Backup, no more Problems. Maybe clear the cache is solving the problem.

**Comment by docmcfly** [comment]
Hi,

I have now separated the log output for the subdomain. 

There I always get the following message many times when I try to open a file 

```[Sun Jul 19 19:09:14.962519 2020] [fcgid:warn] [pid 5220] [client 2a02:c205:3001:9357::1:36336] mod_fcgid: stderr: PHP Warning: fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/public/cloud.mydomain.tld/htdocs/apps/richdocumentscode/proxy.php on line 253```


`Regards Clemens
