### ISSUE TITLE
Error when trying to connect (Client error: `CommandService.ashx` resulted in a `405 Method Not Allowed` response)

### ISSUE THREAD

**Issue by GeneriumMadness** [nextcloud/documentserver_community#163]
Error when trying to connect (Client error: `POST https://own-drive.ru/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response)
![Screenshot_2020-07-31-13-59-39-35](https://user-images.githubusercontent.com/29273152/89029077-45257980-d336-11ea-8233-bae0ce49241c.jpg)

**Comment by GeneriumMadness** [comment]
Nextcloud 19

**Comment by dugaa95** [comment]
Change in Options from Only Office http to https :)

**Comment by GeneriumMadness** [comment]
i reinstalled it and everything went ok
