### ISSUE TITLE
When working in OO things mess up after closing and re-opening the document

### ISSUE THREAD

**Issue by WebTiger89** [nextcloud/documentserver_community#164]
Hi,
I'm new to the nextcloud world. I'm using Ubuntu Server 20.04 and Nextcloud 19.0.1, OO and Document Server are latest as well. I'm not sure if this behavior was mentioned here already but I noticed that my document got messed up after closing and re-opening it. I did a lot of copy & paste stuff in this document. After finishing my work I closed the document page but wanted to adjust something an opened it again. I noticed that all the text was messed up, it was doubled and formatted and specific pages had text which I removed in the session before.

Did someone notice this behavior too?

**Comment by budda85** [comment]
Hey i have the same issue. 
Text that i have formatted to a date is later a number. the size of the columns are changed. some cells formatted as currency have leading zeros. and so on.
 NC 19.0.1
 Community Document Server 0.1.7
 ONLYOFFICE 4.3.0

**Comment by daveknave** [comment]
Same issue after copying and pasting formatted text in lists.
NC 20.0.4
Community Document Server 0.1.8
ONLYOFFICE 6.2.0
