### ISSUE TITLE
Mobile edit docx files: Backspace isn't working with autocompletion (Swiftkey, Gboard)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/documentserver_community#166]
If I use in docx files the autocompletion of Swiftkey or Gboard the the backspace key isn't working until I do a new line. 
See video: 
![OO-Autocomplete](https://user-images.githubusercontent.com/24530680/91435727-12a06b00-e867-11ea-9c3e-18dca41c13ed.gif)

**Comment by icewind1991** [comment]
This is probably an upstream onlyoffice issue, can you try reproducing it with the official document server (either setup their docker image, or use the demo server).
