### ISSUE TITLE
The app doesn't do anything

### ISSUE THREAD

**Issue by stemy2** [nextcloud/documentserver_community#167]
Hello,

I just installed the app from the app manager, but when i open a document, i'm directly prompted to download it, as if i didn't installed any document server. I tried to reinstall it, without results.

I'm on Yunohost 4 (based on debian 10) and the app version is 18.0.7

**Comment by talheim-it** [comment]
@stemy2 did you check to install onlyoffice as connector? The app is necessary.

The document server is not connecting standalone.

**Comment by icewind1991** [comment]
You also need to install the onlyoffice app

**Comment by stemy2** [comment]
> You also need to install the onlyoffice app

Yes.
