### ISSUE TITLE
Installing app fails with "An error occured during the request. Unable to proceed."

### ISSUE THREAD

**Issue by cpbl** [nextcloud/documentserver_community#168]
When I click on the "Download and Install" button for Community Document Server, it spins its wheel/icon for a while and then reverts to being uninstalled, producing a little "An error occured during the request. Unable to proceed." message at the top right of the window.

I have nextcloud installed on an Ubuntu 18.04 server.

I can't find any more logging details.

**Comment by SchokoShampoo** [comment]
try this: https://github.com/nextcloud/documentserver_community/issues/169#issuecomment-694315371

**Comment by icewind1991** [comment]
Closing as duplicate of #26
