### ISSUE TITLE
Add check that proc_open is allowed and show warning otherwise

### ISSUE THREAD

**Issue by fthl** [nextcloud/documentserver_community#17]
Hi,

I upgraded to nc 18 and then proceeded to install the Onlyoffice and Documents Server apps. So far so good, however it seems the Document-Server cannot be reached. Every time I try to open an office-document the nextcloud-log reports:

Exception: fclose() expects parameter 1 to be resource, null given

Undefined offset: 0 at /web/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php#45

proc_open() has been disabled for security reasons at /web/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php#43

Meanwhile the Onlyoffice-settings correctly (or what I assume as correctly) say https://[url]/nextcloud/apps/documentserver_community/

I am running out of ideas and would greatly appreciate any hints or ideas.
![Screenshot from 2020-01-18 20-22-28](https://user-images.githubusercontent.com/26443795/72669319-a936bf00-3a30-11ea-932c-e0656314165d.png)

**Comment by kesselb** [comment]
> proc_open() has been disabled for security reasons

PHP function `proc_open` is required. Please update the PHP configuration and allow it.

**Comment by fthl** [comment]
.....thanks. way too easy.

**Comment by kesselb** [comment]
Thanks :+1: I'm reopening because a warning makes sense.

**Comment by fthl** [comment]
Addendum: same goes for proc_close

**Comment by kesselb** [comment]
Should be fixed by: https://github.com/nextcloud/documentserver_community/commit/31eb8c807df4abff76a901ca4ed98bfd63669d4b
