### ISSUE TITLE
No controls to close the document, see details and chat

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/documentserver_community#176]
In the last version of the Community DocumentServer there are no controls to close document, share document and call the chat.
Nextcloud 20.0.0
Community DocumentServer 0.1.8
OnlyOffice 6.0.2

![image](https://user-images.githubusercontent.com/5199030/95663943-14d73400-0b4c-11eb-9ea8-5908fcfa25b6.png)

**Comment by abortu** [comment]
Same behavior on:

Nextcloud 19.0.4
Community Document Server	0.1.8
OnlyOffice 6.0.2

**Comment by jakobroehrl** [comment]
duplicate of https://github.com/nextcloud/documentserver_community/issues/174 ?
