### ISSUE TITLE
I cannot install Nexcloud Community Document Server

### ISSUE THREAD

**Issue by arnesgurda** [nextcloud/documentserver_community#177]
I am getting error "cURL error 23: Failed writing body (0 != 16347) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)" while installing Community Document Server.
Is there a solution? Thanks.

**Comment by rdz-oss** [comment]
Perhaps you ran out of local memory? I had such an issue in nextcloud 21.0.0.
The fileConverter/bin used more than 150GB.
