### ISSUE TITLE
Editor updated notification

### ISSUE THREAD

**Issue by king-anduin** [nextcloud/documentserver_community#179]
Hi,
I recently updated my NC19 to NC20. Everything is working properly except the fact that OnlyOffice does not open any files. It creates them. That’s it. Existing files or new created files can not be edited.

![Screenshot from 2020-10-17 15-25-40](https://user-images.githubusercontent.com/56738872/96353839-11a1f200-10d0-11eb-9657-a8e59893876b.png)

I get this notification. Afterwards OnlyOffice is doing nothing. Just loading screen. No trace of a error in my log files. I tried to reinstall both. OnlyOffice and documentenserver but it's still the same error.
I hope someone can help me out here.

**Comment by hexitnz** [comment]
I had this problem a few weeks back after an update. When you say reinstalled, did you remove both then install the document server then install onlyoffice? Doing it in that order worked for me.

**Comment by king-anduin** [comment]
I disabled, removed and installed it again. I got these instructions from an issue maybe it was your issue. Both via terminal and then GUI. Didn’t work out.

**Comment by hexitnz** [comment]
Yes I have just done a fresh install of NC20 with Onlyoffice and found older ODS files are not opening even after an uninstall and reinstall of OO client and server. Will need some investigation.

**Comment by hexitnz** [comment]
A Google search brought up others with this error. have a look at 

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/146

but I would test on a non production server first or backup your database! will try it myself later on.

**Comment by hexitnz** [comment]
Actually that last link related to Onlyoffice server, not the the community edition.

**Comment by king-anduin** [comment]
It's about OnlyOffice and it's running on NGINX. I think my problem is DocumentServer and it's running on NC20 and that's running on Apache. But thanks for your help. I realyy appreciate it. I can't check systemctl status like on the page.
