### ISSUE TITLE
Can't install 0.1.8 on fresh Nextcloud server 

### ISSUE THREAD

**Issue by mobious25** [nextcloud/documentserver_community#180]
When installing the Community Document Server on the latest nextcloud build (20 something). I click download and enable on the document server. It sit there spinning for a few minutes and then stops. It still says download and enable. If I click it again, it says disable. After checking the log I see the following error message.

Exception: sh: ../../tools/allfontsgen: not found
/config/www/nextcloud/apps/documentserver_community/lib/LocalAppData.php - line 78:

OCA\DocumentServer\Document\FontManager->OCA\DocumentServer\Document\{closure}("*** sensiti ... *")

/config/www/nextcloud/apps/documentserver_community/lib/Document/FontManager.php - line 76:

OCA\DocumentServer\LocalAppData->getReadLocalPath(OC\Files\Sim ... {}, Closure {})

/config/www/nextcloud/apps/documentserver_community/lib/Migration/RebuildFonts.php - line 50:

OCA\DocumentServer\Document\FontManager->rebuildFonts()

/config/www/nextcloud/lib/private/Repair.php - line 106:

OCA\DocumentServer\Migration\RebuildFonts->run(OC\Repair {})

/config/www/nextcloud/lib/private/legacy/OC_App.php - line 1042:

OC\Repair->run()

/config/www/nextcloud/lib/private/Installer.php - line 160:

OC_App::executeRepairSteps("documentserver_community", { step: "OCA ... "})

/config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 448:

OC\Installer->installApp("documentserver_community")

/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OCA\Settings\Controller\AppSettingsController->enableApps([ "documentserver_community"], [])

/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")

/config/www/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")

/config/www/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { action: nu ... "})

/config/www/nextcloud/lib/base.php - line 1009:

OC\Route\Router->match("/settings/apps/enable")

/config/www/nextcloud/index.php - line 37:

OC::handleRequest()

**Comment by DavinciLeonardo** [comment]
Same for me, its just spinning and then it stops

**Comment by adietz00** [comment]
Just installed a fresh copy of 20.0.2 using docker. Community Document Server installed but refuses to enable. Spins indefinitely for me, though. I have followed the advice to add 'allow_local_remote_servers' => true, to config.php, but that hasn't solved the issue.

**Comment by adietz00** [comment]
A bit more investigation... when I got to Settings -> Administration -> ONLYOFFICE, I see the following errors:

`{"reqId":"ouX7Oapn760nutKiZQVj","level":3,"time":"2020-11-30T05:20:10+00:00","remoteAddr":"x.x.x.x","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/onlyoffice","message":"Could not find resource core/js/systemtags/systemtags.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"20.0.2.2"}

{"reqId":"ouX7Oapn760nutKiZQVj","level":3,"time":"2020-11-30T05:20:10+00:00","remoteAddr":"x.x.x.x","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/onlyoffice","message":"Could not find resource core/js/systemtags/systemtagmodel.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"20.0.2.2"}

{"reqId":"ouX7Oapn760nutKiZQVj","level":3,"time":"2020-11-30T05:20:10+00:00","remoteAddr":"x.x.x.x","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/onlyoffice","message":"Could not find resource core/js/systemtags/systemtagsmappingcollection.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"20.0.2.2"}

{"reqId":"ouX7Oapn760nutKiZQVj","level":3,"time":"2020-11-30T05:20:10+00:00","remoteAddr":"x.x.x.x","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/onlyoffice","message":"Could not find resource core/js/systemtags/systemtagscollection.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"20.0.2.2"}

{"reqId":"ouX7Oapn760nutKiZQVj","level":3,"time":"2020-11-30T05:20:10+00:00","remoteAddr":"x.x.x.x","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/onlyoffice","message":"Could not find resource core/js/systemtags/systemtagsinputfield.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"20.0.2.2"}`

Then when I click the Save button, I get this error:

`{"reqId":"sGJmrFqr8E8tMTNR42nO","level":3,"time":"2020-11-30T05:30:52+00:00","remoteAddr":"x.x.x.x","user":"admin","app":"PHP","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":{"Exception":"Error","Message":"Undefined property: OCA\\Onlyoffice\\DocumentService::$logger at /config/www/nextcloud/apps/onlyoffice/lib/documentservice.php#435","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/onlyoffice/lib/documentservice.php","line":435,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined property: OCA\\Onlyoffice\\DocumentService::$logger","/config/www/nextcloud/apps/onlyoffice/lib/documentservice.php",435,{"urlGenerator":{"__class__":"OC\\URLGenerator"},"crypt":{"__class__":"OCA\\Onlyoffice\\Crypt"},"logger":{"__class__":"OC\\Log"},"version":"5.6.5","healthcheckResponse":true,"commandResponse":{"version":"5.6.5","error":0,"__class__":"stdClass"},"convertedFileUri":{"0":"https://xxxx","__class__":"SimpleXMLElement"},"hashUrl":"xxxx","fileUrl":"https://xxxx"}]},{"file":"/config/www/nextcloud/apps/onlyoffice/controller/settingscontroller.php","line":168,"function":"checkDocServiceUrl","class":"OCA\\Onlyoffice\\DocumentService","type":"->","args":[{"__class__":"OC\\URLGenerator"},{"__class__":"OCA\\Onlyoffice\\Crypt"}]},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"SaveAddress","class":"OCA\\Onlyoffice\\Controller\\SettingsController","type":"->","args":["https://xxxx/apps/documentserver_community/","","",false,"",false]},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Onlyoffice\\Controller\\SettingsController"},"saveAddress"]},{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Onlyoffice\\Controller\\SettingsController"},"saveAddress"]},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["SettingsController","saveAddress",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"onlyoffice.settings.save_address"}]},{"file":"/config/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/onlyoffice/ajax/settings/address"]},{"file":"/config/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"20.0.2.2"}`

**Comment by adietz00** [comment]
UPDATE ON MY OWN ISSUES ABOVE:

1. On the issue of missing systemtags directory under nextcloud/core/js. I downloaded a tarball of Nextcloud version 18 from  https://github.com/nextcloud/server/archive/stable18.zip and extracted the systemtags directory, copying it into my installation's config path under nextcloud/core/js. While this fixed the errors in the logs, it didn't seem to be related to the original issue of being unable to turn on the Community Document Server app after a fresh install.

2. What ultimately fixed the issue with my Community Document Server app was applying this change to file nextcloud/apps/onlyoffice/lib/documentservice.php:

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/4ed51cf2fd6ac52b5b1fe93f8431ec2987f6af2a
