### ISSUE TITLE
TrueNas-NextCloud problem.

### ISSUE THREAD

**Issue by RobertRoberts2020** [nextcloud/documentserver_community#187]
I'm running TrueNas12 and NextCloud latest.

I installed Document Server Community.

OnlyOffice settings were automatically configured in this way:

http://MYIP:8282/apps/documentserver_community/
http://MYIP:8282/
http://MYIP:8282/

When I click save I get the following error:

cURL error 7: Failed to connect to MYIP port 8282: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html))

In the "Office Online" app the following happens:

in URL and port I added this:
http://MYIP:8282/apps/documentserver_community/
And a huge green icon shows up apparently indicating everything is ok but after clicking save I get:
Could not establish connection to the Office Online server.

**Comment by deneb2** [comment]
I am using Freenas 11.3-U5 and nextcloud 19.0.4

I installed the `Document Server Community` app and the `ONLYOFFICE` app

OnlyOffice settings were automatically configured with: https://`<addr>`/apps/documentserver_community/

I tried to open a `.ods` file and I got two messages:
`Community document server is not supported for this instance, please setup and configure an external document server`
`only linux based servers are supported`

I went back to ONLYOFFICE app settings, pressed `save` (just for checking), but nothing happens, I just see the progress gif rolling forever.

Tried to remove the the `Document Server Community` app and pressed `save` again on the ONLYOFFICE app settings it gives me `Error when trying to connect (Bad healthcheck status)` obviously.

So it looks like onlyoffice is properly recognizing and connecting to the community server, but it doesn't work.

**Comment by RobertRoberts2020** [comment]
As of now I deployed NextCloud in a Native Ubuntu VM and everything works perfectly, so it has to be some kind of Truenas/freenas thing.
