### ISSUE TITLE
Documentation of Limitations

### ISSUE THREAD

**Issue by markusdd** [nextcloud/documentserver_community#19]
The App description page says it has limitations compared to OnlyOffice document server.

Are the differences documented somewhere so I can make an informed decision if I still need my bulky VM with OnlyOffice or if I can safely integrate it with my nextcloud and be done with it?

**Comment by akoyaxd** [comment]
Yes, some more documentation would be really nice!

**Comment by martin930** [comment]
I agree. 

What performance / feature differences do we have in the embedded app-version compared to the dedicated?

**Comment by jospoortvliet** [comment]
From our forums I saw somebody mention this:

* no conversion service
* no command service (only ‘version’ command)
* no spellchecking
* issues with adding fonts
* no document chat
* occasional x2t failures
(whats a x2t failure? or doesn’t it matter if I don’t know?)

========
WRT performance, there's a fair bit more communication, but we simply don't have any hard numbers.

But this was developed for private/home user use, and it should work fine for home users. If you want to use this in a small business or with a team of volunteers at  your local soccer club or something, you're using the wrong tool. Please get the docker container.
