### ISSUE TITLE
/x2t: error while loading shared libraries: libgraphics.so

### ISSUE THREAD

**Issue by nilskamm** [nextcloud/documentserver_community#190]
Hi all!
I used the OnlyOffice App with the Community Document Server App for quite a while in another instance and wanted to install it to my new nextcloud instance. 

The instance is installed in a webhosting environment like my other instance.
I updated the instance from 19.0.3 to 10.0.5 and installed the OnlyOffice (6.1.0) and Community Document Server (0.1.8) App from the Appstore. 

When i try to open a document it only says
> ONLYOFFICE cannot be reached. Please contact admin

I tried to reinstall it but it always comes to the same problem.

The log shows two problems:
> {"reqId":"X8P3OOnZhy@xEN97KOROdwAAAz8","level":3,"time":"2020-11-29T19:32:08+00:00","remoteAddr":"89.247.127.98","user":"LIadmin","app":"documentserver_community","method":"GET","url":"/apps/documentserver_community/web-apps/apps/api/documents/api.js","message":
> 
> {"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"./x2t: error while loading shared libraries: libgraphics.so: cannot open shared object file: No such file or directory\n","Code":0,"Trace":[
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/Document/ConverterBinary.php","line":72,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":[""]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/SetupCheck.php","line":34,"function":"test","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":[]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/Controller/StaticController.php","line":89,"function":"check","class":"OCA\\DocumentServer\\SetupCheck","type":"->","args":[]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"webApps","class":"OCA\\DocumentServer\\Controller\\StaticController","type":"->","args":["apps/api/documents/api.js"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/base.php","line":1010,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":64,"CustomMessage":"--"},
> 
> "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"19.0.5.2"}

and

> {"reqId":"X8P3OOnZhy@xEN97KOROdwAAAz8","level":3,"time":"2020-11-29T19:32:09+00:00","remoteAddr":"89.247.127.98","user":"LIadmin","app":"index","method":"GET","url":"/apps/documentserver_community/web-apps/apps/api/documents/api.js","message":
> 
> {"Exception":"Exception","Message":"trim() expects parameter 1 to be string, bool given","Code":0,"Trace":[
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/base.php","line":1010,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"trim() expects parameter 1 to be string, bool given","Code":0,"Trace":[
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/SetupCheck.php","line":80,"function":"trim","args":[false]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/SetupCheck.php","line":55,"function":"lddError","class":"OCA\\DocumentServer\\SetupCheck","type":"->","args":[]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/Controller/StaticController.php","line":90,"function":"getHint","class":"OCA\\DocumentServer\\SetupCheck","type":"->","args":[]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"webApps","class":"OCA\\DocumentServer\\Controller\\StaticController","type":"->","args":["apps/api/documents/api.js"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/lib/base.php","line":1010,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},
> 
> {"file":"/www/htdocs/w00b5f79/nextcloud-test/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/w00b5f79/nextcloud-test/apps/documentserver_community/lib/SetupCheck.php","Line":80},"CustomMessage":"--"},
> 
> "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"19.0.5.2"}

I guess the second error just occurs because of the first one. They always come together.

My config.php:
>     <?php
>     $CONFIG = array (
>       'instanceid' => 'oca1zua6cgwx',
>       'passwordsalt' => 'GUGITRAVvHjWyQ3bEesaMeaxkD3ku9',
>       'secret' => 'TJTkwIlDopYBMXwwjDpz4EHEjPZtu24KBNBHCy57CWo10NOy',
>       'trusted_domains' => 
>       array (
>         0 => 'cloudtest.host.com',
>         1 => 'www.cloudtest.host.com',
>       ),
>       'datadirectory' => '/www/htdocs/w00b5f79/nextcloud-test/data',
>       'dbtype' => 'mysql',
>       'version' => '19.0.5.2',
>       'overwrite.cli.url' => 'http://cloudtest.host.com',
>       'htaccess.RewriteBase' => '/',
>       'dbname' => 'daname',
>       'dbhost' => 'localhost',
>       'dbport' => '',
>       'dbtableprefix' => 'BQ8qJ_',
>       'mysql.utf8mb4' => true,
>       'dbuser' => 'dbuser',
>       'dbpassword' => 'dbpassword',
>       'installed' => true,
>       'tempdirectory' => '/www/htdocs/w00b5f79/nextcloud-test/tmp/',
>       'mail_smtpmode' => 'sendmail',
>       'mail_sendmailmode' => 'pipe',
>       'mail_from_address' => 'it',
>       'mail_domain' => 'host.com',
>       'maintenance' => false,
>       'theme' => '',
>       'loglevel' => 0,
>       'simpleSignUpLink.shown' => false,
>       'default_language' => 'de',
>       'default_locale' => 'de_DE',
>       'updater.secret' => '$2y$10$G1DoE5HSre7FLBnHpD/N3OpTsr2/ayQ8PGmuvpQ83UohttUHVnM/W',
>     );

Any idea how to fix that?

**Comment by nilskamm** [comment]
In the nextcloud forum (https://help.nextcloud.com/t/x2t-error-while-loading-shared-libraries-libgraphics-so/99726/4) one user (j-ed) explained to me, that this error comes from a missing shared library in the OS and the solution would be to install the libraries. 

My problem is, that i use it in a shared environment of a webhosting company. So i don't have any access to the OS and the hoster already said, that he will not install this library for us. 

So my question is, if you have any idea how to fix that problem in another way? Is it maybe possible to deactivate the function which uses this library in our installation?

Thanks a lot!

**Comment by j-ed** [comment]
Sorry, no way to get it fixed in your environment.

**Comment by BastianBalthasarBux** [comment]
libgraphics.so is located in
`apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/`
So why the heck shouldn't this be fixable?
The documentserver brings the lib with him. And in v 18 of Nextcloud it worked. In v19 not anymore.

**Comment by nilskamm** [comment]
The documentserver app worked for me in the v19 of Nextcloud as well. In the documentserver app version 0.1.7. After the update on the documentserver app version 0.1.8 it started to have this problem.

**Comment by JensHH** [comment]
same problem here

**Comment by plush** [comment]
It turns out the "missing library" is just an incorrectly set path. I filed a dedicated bug for this at #195.
