### ISSUE TITLE
0.1.8 - downgrade possible? No libgraphics.so (by the way: why?) for CentOS#8

### ISSUE THREAD

**Issue by TueTchen** [nextcloud/documentserver_community#194]
1 year ago I was sad, 'cause my hosted server was only a 32-bit Server, and so I couldn't use OnlyOffice/CDS because of needed x64.

End of last year I rent a modern CentOS#8x64 (managed, with custom installations, if safe from a safety point of view) - but now comes CDS with 0.1.8 and the need of libgraphics.so .... and I'm now sad again, 'cause this lib seems not to exist for CentOS#8 :-/
https://pkgs.org/download/libgraphics.so()(64bit

What can I or what could you do?
The best would be a version whithout needing this lib (question, as many others in www already asked: Why? For what? Why introduction within a minor release?), and compatible with current 20.0.4 NC + OO.

Could you please help?
Thank you very much for short-term response/action.
Kindest regards
Peter

**Comment by plush** [comment]
I don't think the library is missing. You simply ran into issue 195.

**Comment by TueTchen** [comment]
Thank you very much! You were - of course - totally right!
Worked now with the replacement you announced - syntay here:
https://github.com/nextcloud/documentserver_community/issues/195#issuecomment-761855751

So I'm happy now - thanks a lot!
Peter
