### ISSUE TITLE
./x2t: error while loading shared libraries: libgraphics.so: SELINUX issue

### ISSUE THREAD

**Issue by Disco1** [nextcloud/documentserver_community#196]
I'm having an issue with SELinux.

I get the following error: ./x2t: error while loading shared libraries: libgraphics.so

I've checked the permissions and it's set like this:

-rw-r--r--. apache apache system_u:object_r:httpd_sys_rw_content_t:s0 libgraphics.so

If I disable SELinux, everything works fine and the rest of Nextcloud works well, too. I don't see what's wrong. Any suggestions?

**Comment by BastianBalthasarBux** [comment]
I have the same problem!

**Comment by BastianBalthasarBux** [comment]
Solution:
Try to set this one:
`semanage fcontext -a -t httpd_sys_rw_content_t "/path_to_nextcloud/apps(/.*)?"`

See also:
https://help.nextcloud.com/t/centos-selinux-documentserver-onlyoffice/70173
