### ISSUE TITLE
Error after each execution of cron background job (cron.php): OCA\DocumentServer\Document\DocumentConversionException: Received signal 11 SEGV_MAPERR 000000000000 / Error in simultaneous usage

### ISSUE THREAD

**Issue by TueTchen** [nextcloud/documentserver_community#198]
Hello,

NC **20.0.5** with Community Document Server **0.1.8** / Community OnlyOffice **6.2.0**
Linux **CentOS8x64** (Managed Server - no root, no docker, but ssh/ftps/occ)

**1. Error in the system protocol appears after every cron.php-execution** Since switching the background jobs from ajax to cron yesterday, ****
==> see below: **"Add. ERROR-LOG"**

**2. Error when starting to work simultaneously in OO-Sheets** - Probalby not correlating to error #1 (then sorry!), presumably already from first start of OO+CDS yesterday (not yet tested before my conversion to cron mentioned under #1)
==> see below: **"Add. SCREENSHOT"**

Known weaknesses/bugs about this, or any idea for help?
Thank you in advance!
Peter

**Add. ERROR-LOG (extract from nc's system protocol / custom paths alienated)**

> [documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: Received signal 11 SEGV_MAPERR 000000000000
> 
> ==== C stack trace ===============================
> 
>  [0x7f8de26a0d82]
>  [0x7f8de1af5dd0]
>  [0x7f8de1edd8ac]
>  [0x7f8de1e8fa2d]
>  [0x7f8de1e867f3]
>  [0x0000007161a0]
>  [0x00000072d06b]
>  [0x000000734c45]
>  [0x0000007380b6]
>  [0x00000053cbbf]
>  [0x7f8de13c26a3]
>  [0x000000713ca3]
> [end of stack trace]
>  at <<closure>>
> 
> 0. <custom-NC-path>/apps/documentserver_community/lib/DocumentConverter.php line 123
>    OCA\DocumentServer\Document\ConverterBinary->run("<custom-NC...> ... l", null)
> 1. <custom-NC-path>/apps/documentserver_community/lib/DocumentConverter.php line 78
>    OCA\DocumentServer\DocumentConverter->runCommand(OCA\DocumentServ ... {})
> 2. <custom-NC-path>/apps/documentserver_community/lib/Document/DocumentStore.php line 155
>    OCA\DocumentServer\DocumentConverter->saveChanges("*** sensitive parameter replaced ***", ["76;AgAAADEA//8 ... "], "<custom-NC...> ... x", "docx")
> 3. <custom-NC-path>/apps/documentserver_community/lib/LocalAppData.php line 100
>    OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensitive parameters replaced ***")
> 4. <custom-NC-path>/apps/documentserver_community/lib/Document/DocumentStore.php line 175
>    OCA\DocumentServer\LocalAppData->getReadWriteLocalPath(OC\Files\SimpleFS\SimpleFolder {}, Closure {})
> 5. <custom-NC-path>/apps/documentserver_community/lib/Document/SaveHandler.php line 56
>    OCA\DocumentServer\Document\DocumentStore->saveChanges(921923466, [OCA\DocumentSer ... "])
> 6. <custom-NC-path>/apps/documentserver_community/lib/BackgroundJob/Cleanup.php line 69
>    OCA\DocumentServer\Document\SaveHandler->flushChanges(921923466)
> 7. <custom-NC-path>/lib/public/BackgroundJob/Job.php line 80
>    OCA\DocumentServer\BackgroundJob\Cleanup->run(null)
> 8. <custom-NC-path>/cron.php line 128
>    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
> 

**Add. SCREENSHOT (USER trying to work in the sheet)**

> ![image](https://user-images.githubusercontent.com/63955513/105045696-7cb0eb00-5a68-11eb-99b5-006549af31b9.png)

**Comment by jr-riketz** [comment]
Got the Same Problem, 
Have you already been able to achieve a solution?
I'm not sure if I can actually use the system based on Community Edition.
