### ISSUE TITLE
Changes are not saved to file - Errors in Logging when trying "flush"

### ISSUE THREAD

**Issue by nilskamm** [nextcloud/documentserver_community#199]
Hi!
Nextcloud: 19.0.8
Document Server 0.1.8
OnlyOffice 6.2.0

Changes made in OnlyOffice are only shown in OnlyOffice. They are not saved to the file and the change date and time of the file are not changed. 

When i try to "occ documentserver:flush" i get these errors in the nextcloud logging:
`{"reqId":"wr4XaaPPXOqZt3rRiuSH","level":3,"time":"2021-02-01T20:37:51+00:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"run_code: $.ready();\nrun: Uncaught ReferenceError: $ is not defined\nDoctRenderer:<result><error code=\"run\" /></result>\n","Code":0,"Trace":[{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":123,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":["/www/htdocs/w00b5f79/nextcloud/tmp/oc_tmp_0GNhg9-.xml",null]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":78,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Document\\ConvertCommand"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":155,"function":"saveChanges","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":["*** sensitive parameter replaced ***",["69;QQAAAAEAEAECAAAANgABBQAAAAEAAAAFAAAAAQAAAAAhAAAAAAIBAQIFAgkDFAAAAAAAAQkBCQAAAAAAAQACAAMCAAIA"],"/www/htdocs/w00b5f79/nextcloud/data/appdata_ocfq3mbhmkub/documentserver_community/doc_270678579/saved.xlsx","xlsx"]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/LocalAppData.php","line":100,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":175,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"Closure"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php","line":56,"function":"saveChanges","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[270678579,[{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},"And 10 more entries, set log level to debug to see all entries"]]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Command/FlushChanges.php","line":72,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->","args":[270678579]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\DocumentServer\\Command\\FlushChanges","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/core/Command/Base.php","line":169,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":1012,"function":"run","class":"OC\\Core\\Command\\Base","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":272,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Command\\FlushChanges"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":148,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"/www/htdocs/w00b5f79/nextcloud/occ","line":11,"args":["/www/htdocs/w00b5f79/nextcloud/console.php"],"function":"require_once"}],"File":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":64,"CustomMessage":"Error while applying changes for document 270678579"},"userAgent":"--","version":"19.0.8.1"}

{"reqId":"wr4XaaPPXOqZt3rRiuSH","level":3,"time":"2021-02-01T20:37:51+00:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"Received signal 11 SEGV_MAPERR 000000000000\n\n==== C stack trace ===============================\n\n [0x7f1cda28dd82]\n [0x7f1cd96e3980]\n [0x7f1cd9aca8ac]\n [0x7f1cd9a7ca2d]\n [0x7f1cd9a737f3]\n [0x0000007161a0]\n [0x00000072d06b]\n [0x000000734c45]\n [0x0000007380b6]\n [0x00000053cbbf]\n [0x7f1cd8f63bf7]\n [0x000000713ca3]\n[end of stack trace]\n","Code":0,"Trace":[{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":123,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":["/www/htdocs/w00b5f79/nextcloud/tmp/oc_tmp_m2qbqB-.xml",null]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":78,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Document\\ConvertCommand"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":155,"function":"saveChanges","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":["*** sensitive parameter replaced ***",["78;AgAAADEA//8BACTRzkcOEQAAigAAAA0AAAA5AAAAOQAAADwAAAB7AQAAewEAABwAAAA1AC4ANAAuADIALgA0ADYALgBAAEAAUgBlAHYA","58;AgAAADEAAQABAAoAAAAxAF8AOAA1ADQAAAAEAAMAAAAKAAAAMQBfADgANQA0AACAIAAAAAAAAAAAAA==","98;AgAAADEAAQABAAoAAAAxAF8AOAA1ADUAAAAcACcAAAAKAAAAMQBfADgANQA1AAoAAAAxAF8AOAA1ADMAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","34;CgAAADEAXwA4ADUANQABABwAAQAAAAAAAAAEAAAAAwAAAA==","87;AgAAADEAAQABAAoAAAAxAF8AOAA1ADMAAAADAAoAAAAxAF8AOAA1ADMAQgAAAAAAAAAAAAAACgAAADEAXwA4ADUANAABAAAACgAAADEAXwA4ADUANQAB","And 28 more entries, set log level to debug to see all entries"],"/www/htdocs/w00b5f79/nextcloud/data/appdata_ocfq3mbhmkub/documentserver_community/doc_2769206278/saved.docx","docx"]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/LocalAppData.php","line":100,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":175,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"Closure"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php","line":56,"function":"saveChanges","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[2769206278,[{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},"And 407 more entries, set log level to debug to see all entries"]]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Command/FlushChanges.php","line":72,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->","args":[2769206278]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\DocumentServer\\Command\\FlushChanges","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/core/Command/Base.php","line":169,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":1012,"function":"run","class":"OC\\Core\\Command\\Base","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":272,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Command\\FlushChanges"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":148,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"/www/htdocs/w00b5f79/nextcloud/occ","line":11,"args":["/www/htdocs/w00b5f79/nextcloud/console.php"],"function":"require_once"}],"File":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":64,"CustomMessage":"Error while applying changes for document 2769206278"},"userAgent":"--","version":"19.0.8.1"}

{"reqId":"wr4XaaPPXOqZt3rRiuSH","level":3,"time":"2021-02-01T20:37:51+00:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"Received signal 11 SEGV_MAPERR 000000000000\n\n==== C stack trace ===============================\n\n [0x7f69e2a97d82]\n [0x7f69e1eed980]\n [0x7f69e22d48ac]\n [0x7f69e2286a2d]\n [0x7f69e227d7f3]\n [0x0000007161a0]\n [0x00000072d06b]\n [0x000000734c45]\n [0x0000007380b6]\n [0x00000053cbbf]\n [0x7f69e176dbf7]\n [0x000000713ca3]\n[end of stack trace]\n","Code":0,"Trace":[{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":123,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":["/www/htdocs/w00b5f79/nextcloud/tmp/oc_tmp_PWBIM3-.xml",null]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":78,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Document\\ConvertCommand"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":155,"function":"saveChanges","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":["*** sensitive parameter replaced ***",["78;AgAAADEA//8BAEWQ7Zn6YgIALQEAAAQAAAAAAAAAAAAAAAAAAAAAAAAA9v///xwAAAA1AC4ANAAuADIALgA0ADYALgBAAEAAUgBlAHYA","40;DAAAADIAXwAyADAANAA0AAEAHAABAAAAAAAAAAEAAABNAAAAAwAAAA==","40;DAAAADIAXwAyADAANAA0AAEAHAABAAAAAQAAAAEAAABlAAAAAwAAAA==","40;DAAAADIAXwAyADAANAA0AAEAHAABAAAAAgAAAAEAAABnAAAAAwAAAA==","40;DAAAADIAXwAyADAANAA0AAEAHAABAAAAAwAAAAEAAABhAAAAAwAAAA=="],"/www/htdocs/w00b5f79/nextcloud/data/appdata_ocfq3mbhmkub/documentserver_community/doc_3733669732/saved.docx","docx"]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/LocalAppData.php","line":100,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":175,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"Closure"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php","line":56,"function":"saveChanges","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[3733669732,[{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},"And 133 more entries, set log level to debug to see all entries"]]},{"file":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Command/FlushChanges.php","line":72,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->","args":[3733669732]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\DocumentServer\\Command\\FlushChanges","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/core/Command/Base.php","line":169,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":1012,"function":"run","class":"OC\\Core\\Command\\Base","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":272,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Command\\FlushChanges"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/3rdparty/symfony/console/Application.php","line":148,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/www/htdocs/w00b5f79/nextcloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"/www/htdocs/w00b5f79/nextcloud/occ","line":11,"args":["/www/htdocs/w00b5f79/nextcloud/console.php"],"function":"require_once"}],"File":"/www/htdocs/w00b5f79/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":64,"CustomMessage":"Error while applying changes for document 3733669732"},"userAgent":"--","version":"19.0.8.1"}`

**Comment by GrenderG** [comment]
I'm randomly getting the same error with `docx` files. Seems like the editor is somehow corrupting some files.

**Comment by GrenderG** [comment]
After days of testing with 10+ users I think I have narrowed down this issue. Seems to happen when the editor is not "properly" closed, like directly closing the tab, browser, or pressing the Back arrow of your browser (then reloading). I have instructed the users to properly exit the editor and the issues suddenly stopped.
