### ISSUE TITLE
"The editor version has been updated. The page will be reloaded" error after upgrade 0.1.8 ->0.1.9

### ISSUE THREAD

**Issue by alexeyvolkoff** [nextcloud/documentserver_community#200]
After upgrading Community Documentserver I get endless "loading" indcator with message  "The editor version has been updated. The page will be reloaded"

Log:
Error: Undefined property: OCA\Onlyoffice\DocumentService::$appName at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#435

OnlyOffice v. 6.2.0
Nextcloud v. 20.0.7

Any workaround?

**Comment by icewind1991** [comment]
The logged error is a problem with the onlyoffice app that should be fixed with https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/435

The logged error might not be causing the original issue though, try clearing the browser cache and reloading the page.

**Comment by alexeyvolkoff** [comment]
@icewind1991 many thanks! Cleaning chache had actually helped!
