### ISSUE TITLE
fileConverter/bin uses more than 150GB

### ISSUE THREAD

**Issue by rdz-oss** [nextcloud/documentserver_community#202]
My VM ran out of Memory. I could not log in anymore.
Docker-compose said it clould not create a temporary file. I run nextcloud in docker behind a reverse proxy.

The issue was at
custom_apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin
which used more than 150GB.

Nextcloud 21.0.0
Stable

I removed that manually with rm -rf ....custom_apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin

Should the document converter use dthat much space on the disk ?

**Comment by sebastiansterk** [comment]
Having the exact same issue. Even with a fresh installation i run into this issue again. This issue caused a few corrupted documents :-/
