### ISSUE TITLE
OCA\DocumentServer\Document\DocumentConversionException: namespace error and fatal error

### ISSUE THREAD

**Issue by SilverNavigator** [nextcloud/documentserver_community#203]
**Hi - Ubuntu Server with PHP 7.4 - Nextcloud Version 20.0.8 - Community Document Server 0.1.9 - OnlyOffice 6.3.0**

**_### Two Errors - hey keep coming back , what is the problem / how can i fix it_**

1. Problem:
**OCA\DocumentServer\Document\DocumentConversionException:** 
namespace error : Namespace prefix wp14 on sizeRelH is not defined rawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin" ^ namespace error : Namespace prefix wp14 on pctWidth is not defined ain"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin"><wp14:pctWidth ^ namespace error : Namespace prefix wp14 on sizeRelV is not defined 4:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin" ^ namespace error : Namespace prefix wp14 on pctHeight is not defined 14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin"><wp14:pctHeight ^

Screenshot with more details: [https://ibb.co/5GxCLZW](url)

2. Problem:
**OCA\DocumentServer\Document\DocumentConversionException:** 
 # # Fatal error in v8::ToLocalChecked # Empty MaybeLocal. # Received signal 4 ILL_ILLOPN 7f1407aea849 ==== C stack trace =============================== [0x7f1407aeba92] [0x7f1406d0b980] [0x7f1407aea849] [0x7f1407306072] [0x7f14072fafb1] [0x7f14072c8ebe] [0x7f14072bf643] [0x000000748550] [0x00000076011b] [0x000000767895] [0x00000076af1d] [0x00000054034f] [0x7f140658bbf7] [0x000000745f93] [end of stack trace]

Screenshot with more details: [https://ibb.co/cCX6xK1](url)

Thank you

**Comment by Enosinger** [comment]
I see this issue as well 👍 Any updates? Were you able to fix it?

**Comment by Amursky1988** [comment]
am experiencing a similar problem
PHP 7.4 - Nextcloud Version 20.0.8 - Community Document Server 0.1.9 - OnlyOffice 6.3.0
