### ISSUE TITLE
The editor version hass been updated. The page will be reloaded to apply the changes

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/documentserver_community#205]
After updating Nextcloud to v21 2 out of my four machines showing this message when I try to open a OnlyOffice file (docx or xlsx):
```
The editor version hass been updated. The page will be reloaded to apply the changes
```
and this is only happening on Google Chrome (I always used). On the machine, I have this issue, if I use, for example Edge, it works fine. I tried to remove site cache/storage/cookies, pressing 'OK' button, leaving the message on, but no joy. Please help.

Nextcloud version 21.0.0
Community Document Server 0.1.9
Onlyoffice 6.3.0
Debian (Linux Mint)
PHP 8.0.3
PGSQL 12.6

**Comment by dawidol** [comment]
Ok.

So after a few hours checking forums and logs, it looks like you only need to clean your browser caché and everything will go back to normal, hope this help

**Comment by adi-dev** [comment]
I tried to force refresh (Ctrl+F5 or Shift+F5), "Clear Cookies and Site Data" from address bar and even used developer tools to remove any site storage (Cache Storage, Cookies, IndexedDB, Local Storage and Session Storage) but no success.

**Comment by Mastercuber** [comment]
For me opening the dev tools, disable the cache and reload the page with disabled cache solved the problem.
