### ISSUE TITLE
Fatal error in DocumentConversionException

### ISSUE THREAD

**Issue by Gspohu** [nextcloud/documentserver_community#206]
Hello,

I'm having a little trouble with Onlyoffice on Nextcloud. I have just made a brand new installation (not the first one), because the old one went up in flames in Strasbourg.

But now I have a lot of problems with Onlyoffice, before I was using an Onlyoffice server that I had set up myself, but I discovered that a great job had been done with the "documentserver_community" application, so I installed it.

The problems are :
- The loss of some data written in the documents
- Some files become corrupted and can't be opened anymore
- The file versions downloaded from Nextcloud are not up to date and when I open the file with Onlyoffice from my server the data is there, but not in the downloaded version
I think all of this must have a root cause.

The only information I have to give is this error in the log that appears all the time. After a lot of research I don't really understand it and I haven't found a solution. I think it's a bug in the application.

`{"reqId":"***sensitive***","level":3,"time":"2021-03-25T08:55:06+00:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"\n#\n# Fatal error in v8::ToLocalChecked\n# Empty MaybeLocal.\n#\n\nReceived signal 4 ILL_ILLOPN 7f824f6b1849\n\n==== C stack trace ===============================\n\n [0x7f824f6b2a92]\n [0x7f824eac73c0]\n [0x7f824f6b1849]\n [0x7f824eecd072]\n [0x7f824eec1fb1]\n [0x7f824ee8febe]\n [0x7f824ee86643]\n [0x000000748550]\n [0x00000076011b]\n [0x000000767895]\n [0x00000076af1d]\n [0x00000054034f]\n [0x7f824e7980b3]\n [0x000000745f93]\n[end of stack trace]\nIllegal instruction (core dumped)\n","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":125,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":80,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":156,"function":"saveChanges","class":"OCA\\DocumentServer\\DocumentConverter","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/LocalAppData.php","line":102,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":176,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php","line":58,"function":"saveChanges","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php","line":71,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\DocumentServer\\BackgroundJob\\Cleanup","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"}],"File":"/var/www/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":66,"CustomMessage":"Error while applying changes for document 866290271"},"userAgent":"--","version":"21.0.0.18","id":"605c4feb50e4a"}`

Like many things in version 21 of Nextcloud the formatted copy button does not work, so sorry for the presentation.

My server :
Nextcloud version 21.0.0
Community Document Server 0.1.9
Onlyoffice 6.3.0
Ubuntu 20.04 up to date
Database :
Type : mysql
Version : 8.0.23 
PHP :
Version : 7.4.3

My config file :
><?php<br/>
>$CONFIG = array (<br/>
>  'instanceid' => '***Sensitive data***',<br/>
>  'passwordsalt' => '***Sensitive data***',<br/>
>  'secret' => '***Sensitive data***',<br/>
>  'trusted_domains' =>
>  array (
>    0 => 'nextcloud.***Sensitive data***',<br/>
>  ),<br/>
>  'datadirectory' => '/var/www/nextcloud/data',<br/>
>  'dbtype' => 'mysql',<br/>
>  'version' => '21.0.0.18',<br/>
>  'overwrite.cli.url' => 'https://nextcloud.***Sensitive data***',<br/>
>  'dbname' => 'nextcloud',<br/>
>  'dbhost' => 'localhost:3306',<br/>
>  'dbport' => '',<br/>
>  'dbtableprefix' => 'oc_',<br/>
>  'mysql.utf8mb4' => true,<br/>
>  'dbuser' => 'nextcloud',<br/>
>  'dbpassword' => '***Sensitive data***',<br/>
>  'installed' => true,<br/>
>  'updater.release.channel' => 'stable',<br/>
>  'maintenance' => false,<br/>
>  'default_phone_region' => 'FR',<br/>
>  'filelocking.enabled' => true,<br/>
>  'memcache.distributed' => '\OC\Memcache\Redis',<br/>
>  'memcache.local' => '\OC\Memcache\Redis',<br/>
>  'memcache.locking' => '\OC\Memcache\Redis',<br/>
>  'redis' =>
>  array (
>    'host' => 'localhost',<br/>
>    'port' => 6379,<br/>
>    'timeout' => 0.0,<br/>
>    'password' => '***Sensitive data***',<br/>
>  ),<br/>
>  'onlyoffice' =>
>  array (
>    'verify_peer_off' => true,<br/>
>  ),<br/>
>  'allow_local_remote_servers' => true,<br/>
>);

Thank you in advance for reading me,

**Comment by rauldux** [comment]
I also get this Error everytime after every cronjob running on nc 21.02

`{"reqId":"6kTYfppReirs2HYyQ1SC","level":3,"time":"2021-04-13T11:55:14+02:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"\n#\n# Fatal error in v8::ToLocalChecked\n# Empty MaybeLocal.\n#\n\nReceived signal 4 ILL_ILLOPN 7f8556512849\n\n==== C stack trace ===============================\n\n [0x7f8556513a92]\n [0x7f855591e730]\n [0x7f8556512849]\n [0x7f8555d2e072]\n [0x7f8555d22fb1]\n [0x7f8555cf0ebe]\n [0x7f8555ce7643]\n [0x000000748550]\n [0x00000076011b]\n [0x000000767895]\n [0x00000076af1d]\n [0x00000054034f]\n [0x7f85555ec09b]\n [0x000000745f93]\n[end of stack trace]\nIllegal instruction\n","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":125,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":["/tmp/oc_tmp_q8qgU7-.xml",null]},{"file":"/var/www/html/nextcloud/apps/documentserver_community/lib/DocumentConverter.php","line":80,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Document\\ConvertCommand"}]},{"file":"/var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":156,"function":"saveChanges","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":["*** sensitive parameter replaced ***",["78;AgAAADEA//8BAEyu79rMhQAAPAEAABwAAABHAQAARwEAAEcBAAC46wAAuOsAABwAAAA2AC4AMQAuADEALgA1ADMALgBAAEAAUgBlAHYA","66;AgAAADEAAQABAA4AAAAxAF8AMQA3ADEAMAA4AAAABAADAAAADgAAADEAXwAxADcAMQAwADgAAIAgAAAAAAAAAAAA","110;AgAAADEAAQABAA4AAAAxAF8AMQA3ADEAMAA5AAAAHAAnAAAADgAAADEAXwAxADcAMQAwADkADgAAADEAXwAxADcAMQAwADcAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","38;DgAAADEAXwAxADcAMQAwADkAAQAcAAEAAAAAAAAABAAAAAMAAAA=","103;AgAAADEAAQABAA4AAAAxAF8AMQA3ADEAMAA3AAAAAwAOAAAAMQBfADEANwAxADAANwBCAAAAAAAAAAAAAAAOAAAAMQBfADEANwAxADAAOAABAAAADgAAADEAXwAxADcAMQAwADkAAQ==","And 24 more entries, set log level to debug to see all entries"],"/ncdata/appdata_ocih5fp8bqhm/documentserver_community/doc_3367994357/saved.odt","odt"]},{"file":"/var/www/html/nextcloud/apps/documentserver_community/lib/LocalAppData.php","line":102,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":176,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"Closure"}]},{"file":"/var/www/html/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php","line":58,"function":"saveChanges","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[3367994357,[{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},{"__class__":"OCA\\DocumentServer\\Document\\Change"},"And 60544 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php","line":71,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->","args":[3367994357]},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\DocumentServer\\BackgroundJob\\Cleanup","type":"->","args":[null]},{"file":"/var/www/html/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":66,"CustomMessage":"Error while applying changes for document 3367994357"},"userAgent":"--","version":"21.0.1.1","id":"60756a832126a"}`

**Comment by rauldux** [comment]
I also get this Error everytime after every cronjob running on nc 21.02

[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: 
#
# Fatal error in v8::ToLocalChecked
# Empty MaybeLocal.
#

Received signal 4 ILL_ILLOPN 7f8556512849

==== C stack trace ===============================

 [0x7f8556513a92]
 [0x7f855591e730]
 [0x7f8556512849]
 [0x7f8555d2e072]
 [0x7f8555d22fb1]
 [0x7f8555cf0ebe]
 [0x7f8555ce7643]
 [0x000000748550]
 [0x00000076011b]
 [0x000000767895]
 [0x00000076af1d]
 [0x00000054034f]
 [0x7f85555ec09b]
 [0x000000745f93]
[end of stack trace]
Illegal instruction
 at <<closure>>

0. /var/www/html/nextcloud/apps/documentserver_community/lib/DocumentConverter.php line 125
   OCA\DocumentServer\Document\ConverterBinary->run("/tmp/oc_tmp_q8qgU7-.xml", null)
1. /var/www/html/nextcloud/apps/documentserver_community/lib/DocumentConverter.php line 80
   OCA\DocumentServer\DocumentConverter->runCommand(OCA\DocumentServ ... {})
2. /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php line 156
   OCA\DocumentServer\DocumentConverter->saveChanges("*** sensitive parameter replaced ***", ["78;AgAAADEA//8 ... "], "/ncdata/appdata ... t", "odt")
3. /var/www/html/nextcloud/apps/documentserver_community/lib/LocalAppData.php line 102
   OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensitive parameters replaced ***")
4. /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php line 176
   OCA\DocumentServer\LocalAppData->getReadWriteLocalPath(OC\Files\SimpleFS\SimpleFolder {}, Closure {})
5. /var/www/html/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php line 58
   OCA\DocumentServer\Document\DocumentStore->saveChanges(3367994357, [OCA\DocumentSer ... "])
6. /var/www/html/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php line 71
   OCA\DocumentServer\Document\SaveHandler->flushChanges(3367994357)
7. /var/www/html/nextcloud/lib/public/BackgroundJob/Job.php line 80
   OCA\DocumentServer\BackgroundJob\Cleanup->run(null)
8. /var/www/html/nextcloud/cron.php line 128
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

**Comment by rauldux** [comment]
obviously a file-conversion bug. I identified the file which caused the error and converted it manually in LibreOffice to odt (in my case) format. From there on I haven't had problems.

**Comment by dgedgedge** [comment]
How did you find the faulty file ?
