### ISSUE TITLE
Chat is not working

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/documentserver_community#22]
Whenever I type in the community document server chat is not shown either me or any party.
Additionally, strange prefixes appear before the user name.

![image](https://user-images.githubusercontent.com/5199030/72732632-c8ebf580-3b9e-11ea-9748-d9d250421660.png)

**Comment by szaimen** [comment]
just use the chat on the right side

**Comment by ostasevych** [comment]
> just use the chat on the right side

not a smart solution, as the native functionality remains is the system and is not workable. Either to fix it or disable at all.

**Comment by szaimen** [comment]
Have you seen this?
![image](https://user-images.githubusercontent.com/42591237/73023509-fa2d2580-3e2b-11ea-97e4-9940bb38eb8b.png)

**Comment by ostasevych** [comment]
> Have you seen this?
> 
> ![image](https://user-images.githubusercontent.com/42591237/73023590-28126a00-3e2c-11ea-8ca5-6d9900c01c59.png)

Of course! One of chats should be disabled, if not working.

**Comment by republicus** [comment]
Its already an option under admin's ONLYOFFICE settings.

![image](https://user-images.githubusercontent.com/47370709/73128750-0935e400-3fa2-11ea-906f-95b3d2f8aad5.png)

**Comment by szaimen** [comment]
> Its already an option under admin's ONLYOFFICE settings.
> 
> ![image](https://user-images.githubusercontent.com/47370709/73128750-0935e400-3fa2-11ea-906f-95b3d2f8aad5.png)

@republicus so if you disable this option, the chat on the left side doesn't get shown?

**Comment by republicus** [comment]
The cursor is in the wrong spot. The first option *Display Chat menu button*, if unchecked, will not show the left side chat.

Though I would agree this should be the default during auto config.
