### ISSUE TITLE
OnlyOffice down and crashes since v0.1.10

### ISSUE THREAD

**Issue by Der-K-2000** [nextcloud/documentserver_community#220]
Since the newest Version 0.1.10 the office-app ONLYOFFICE for Nextcloud doesn't work anymore. Opening an ms office file (docx, pptx, xlsx) results in an popup message „Editor-Version wurde aktualisiert. Die Seite wird neu geladen, um die Änderungen zu übernehmen.“ (editor version was updated. Page will be reloaded). But that's all. The page won't reload and opening other docs results in the same message. Also, after trying this a few times an error appears, that only 20 people can use ONLYOFFICE at a time.

There are two log entries in NextCloud for that:

`{"reqId":"CBtvyvJPBQjFB8IZBsnW","level":3,"time":"2021-07-07T12:24:32+02:00","remoteAddr":"178.XXX","user":"--","app":"index","method":"POST","url":"/apps/documentserver_community/ConvertService.ashx","message":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"Received signal 11 SEGV_MAPERR 000000000000\n\n==== C stack trace ===============================\n\n [0x7f5534ec60e2]\n [0x7f5534253730]\n [0x7f55346ec4d5]\n [0x7f55346c9ee1]\n [0x7f5534689e74]\n [0x7f5534683020]\n [0x00000077c1eb]\n [0x00000077d915]\n [0x0000007821be]\n [0x00000054165f]\n [0x7f5533f2109b]\n [0x00000075af13]\n[end of stack trace]\n","Code":0,"Trace":[{"file":"/apps/documentserver_community/lib/DocumentConverter.php","line":125,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":["/is/htdocs/user_tmp/wp10591206_W5KD2II0PY/oc_tmp_S8rLO8-.xml",null]},{"file":"/apps/documentserver_community/lib/Document/DocumentStore.php","line":255,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Document\\ConvertCommand"}]},{"file":"/apps/documentserver_community/lib/LocalAppData.php","line":102,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/apps/documentserver_community/lib/Document/DocumentStore.php","line":256,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"Closure"}]},{"file":"/apps/documentserver_community/lib/Controller/ConvertController.php","line":60,"function":"convert","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[3396773412,"jpeg"]},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"convert","class":"OCA\\DocumentServer\\Controller\\ConvertController","type":"->","args":[false,"https://DOMAINXYZ.COM/apps/onlyoffice/download?doc=1234567890","jpeg","pptx","3396773412.pptx","3396773412"]},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\ConvertController"},"convert"]},{"file":"/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\ConvertController"},"convert"]},{"file":"/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\ConvertController","convert",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"documentserver_community.Convert.convert"}]},{"file":"/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/ConvertService.ashx"]},{"file":"/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":66,"CustomMessage":"--"},"userAgent":"Nextcloud Server Crawler","version":"21.0.3.1","id":"60e580e10432c"}`

and

`{"reqId":"lkAM1UiCMdqN0Q69iH32","level":3,"time":"2021-07-07T12:24:32+02:00","remoteAddr":"2a02:XXXX","user":"sp_716taqbbto","app":"onlyoffice","method":"GET","url":"/core/preview?fileId=5633&c=a566364e02deb63531cb00274b10b4c3&x=250&y=250&forceIcon=0&a=0","message":{"Exception":"GuzzleHttp\\Exception\\ServerException","Message":"Server error: `POST https://DOMAINXYZ.COM/apps/documentserver_community/ConvertService.ashx` resulted in a `500 Internal Server Error` response:\n<!DOCTYPE html>\n<html class=\"ng-csp\" data-placeholder-focus=\"false\" lang=\"de-DE\" data-locale=\"de_DE\" >\n\t<head\n data-requ (truncated...)\n","Code":500,"Trace":[{"file":"/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":69,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":[{"__class__":"GuzzleHttp\\Psr7\\Request"},"*** sensitive parameter replaced ***",null,[],null]},{"file":"/3rdparty/guzzlehttp/promises/src/Promise.php","line":204,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/3rdparty/guzzlehttp/promises/src/Promise.php","line":153,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":[1,"*** sensitive parameter replaced ***",null]},{"file":"/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":48,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/3rdparty/guzzlehttp/promises/src/Promise.php","line":248,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->","args":[true]},{"file":"/3rdparty/guzzlehttp/promises/src/Promise.php","line":224,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/3rdparty/guzzlehttp/promises/src/Promise.php","line":269,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/3rdparty/guzzlehttp/promises/src/Promise.php","line":226,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/lib/private/Http/Client/Client.php","line":307,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["post","https://DOMAINXYZ.COM/apps/documentserver_community/ConvertService.ashx",{"verify":"/resources/config/ca-bundle.crt","timeout":"120","headers":{"Content-type":"application/json","User-Agent":"Nextcloud Server Crawler","Accept-Encoding":"gzip"},"body":"{\"async\":false,\"url\":\"https:\\/\\/DOMAINXYZ.COM\\/apps\\/onlyoffice\\/download?doc=1234567890\",\"outputtype\":\"jpeg\",\"filetype\":\"pptx\",\"title\":\"3396773412.pptx\",\"key\":\"3396773412\"}","synchronous":true}]},{"file":"/apps/onlyoffice/lib/documentservice.php","line":362,"function":"post","class":"OC\\Http\\Client\\Client","type":"->","args":["https://DOMAINXYZ.COM/apps/documentserver_community/ConvertService.ashx",{"timeout":"120","headers":{"Content-type":"application/json"},"body":"{\"async\":false,\"url\":\"https:\\/\\/DOMAINXYZ.COM\\/apps\\/onlyoffice\\/download?doc=1234567890\",\"outputtype\":\"jpeg\",\"filetype\":\"pptx\",\"title\":\"3396773412.pptx\",\"key\":\"3396773412\"}"}]},{"file":"/apps/onlyoffice/lib/documentservice.php","line":171,"function":"Request","class":"OCA\\Onlyoffice\\DocumentService","type":"->","args":["https://DOMAINXYZ.COM/apps/documentserver_community/ConvertService.ashx","post",{"timeout":"120","headers":{"Content-type":"application/json"},"body":"{\"async\":false,\"url\":\"https:\\/\\/DOMAINXYZ.COM\\/apps\\/onlyoffice\\/download?doc=1234567890\",\"outputtype\":\"jpeg\",\"filetype\":\"pptx\",\"title\":\"3396773412.pptx\",\"key\":\"3396773412\"}"}]},{"file":"/apps/onlyoffice/lib/documentservice.php","line":90,"function":"SendRequestToConvertService","class":"OCA\\Onlyoffice\\DocumentService","type":"->","args":["https://DOMAINXYZ.COM/apps/onlyoffice/download?doc=1234567890","pptx","jpeg","3396773412",false]},{"file":"/apps/onlyoffice/lib/preview.php","line":267,"function":"GetConvertedUri","class":"OCA\\Onlyoffice\\DocumentService","type":"->","args":["https://DOMAINXYZ.COM/apps/onlyoffice/download?doc=1234567890","pptx","jpeg","3396773412"]},{"file":"/lib/private/Preview/ProviderV1Adapter.php","line":54,"function":"getThumbnail","class":"OCA\\Onlyoffice\\Preview","type":"->","args":["Organigramm.pptx",4096,4096,false,{"__class__":"OC\\Files\\View"}]},{"file":"/lib/private/Preview/GeneratorHelper.php","line":63,"function":"getThumbnail","class":"OC\\Preview\\ProviderV1Adapter","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},4096,4096]},{"file":"/lib/private/Preview/Generator.php","line":244,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->","args":[{"__class__":"OC\\Preview\\ProviderV1Adapter"},{"__class__":"OC\\Files\\Node\\File"},4096,4096]},{"file":"/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"OC\\Files\\Node\\File"},"application/vnd.openxmlformats-officedocument.presentationml.presentation",""]},{"file":"/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},[{"width":250,"height":250,"crop":true,"mode":"fill"}],"application/vnd.openxmlformats-officedocument.presentationml.presentation"]},{"file":"/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},250,250,true,"fill",null]},{"file":"/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},250,250,true,"fill"]},{"file":"/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},250,250,false,false,"fill"]},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[5633,250,250,false,false,"fill"]},{"file":"/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\PreviewController","getPreviewByFileId",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.Preview.getPreviewByFileId"}]},{"file":"/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/core/preview"]},{"file":"/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":113,"CustomMessage":"GetConvertedUri: from pptx to jpeg"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.3.1","id":"60e580e1041ef"}`

**Important:** In the version before I had to fix /apps/documentserver_community/lib/Document/**ConverterBinary.php** and had to add `"LD_LIBRARY_PATH" => "."` – that error was reported here: https://github.com/nextcloud/documentserver_community/issues/195 But this time no success for the current version 0.1.10. Hopefully somebody can help me.

**Comment by KlausRiesmeier** [comment]
I'll got the same error. My solutions:
complete uninstall onlyoffice and documentserver_community, delete all configs from onlyoffice with "config:app:delete" and finaly check entrys in your config.php. After all, it runs on my server. Hope that helps.

**Comment by ariesbi** [comment]
I have encountered the same problem, and the reinstallation did not solve the problem，I find some error：
root@i3:/var/www/nextcloud# sudo -u www-data php occ integrity:check-app onlyoffice
root@i3:/var/www/nextcloud# sudo -u www-data php occ integrity:check-app documentserver_community
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Signature data not found.

**Comment by SebastianBerlin** [comment]
> 
> 
> I have encountered the same problem, and the reinstallation did not solve the problem，I find some error：
> root@i3:/var/www/nextcloud# sudo -u www-data php occ integrity:check-app onlyoffice
> root@i3:/var/www/nextcloud# sudo -u www-data php occ integrity:check-app documentserver_community
> 
>     * EXCEPTION:
>       
>       * class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
>       * message: Signature data not found.

Same here. No success with reinstall/cleaning. I'm back to 0.1.9. Versions 0.1.10 and 0.1.11 don't work.

**Comment by baku104788** [comment]
I too am having issues with v 0.1.10 and 0.1.11
My issue shows itself by me being unable to open documents from within the IOS nextcloud app or on a mobile browser on IOS. Once I manually unzipped v0.1.9 of the community document server I was able to get things working again.
