### ISSUE TITLE
Missing self:: in front of constant in SessionManager.php#L134

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/documentserver_community#222]
https://github.com/nextcloud/documentserver_community/blob/48b051a54290ab7212ce147911f476892a236548/lib/Channel/SessionManager.php#L134

**Comment by KlausRiesmeier** [comment]
Same issue here, with ubuntu Server and PHP7.4.

**Comment by masterct88** [comment]
me too, php 7.4.3.

**Comment by doc75** [comment]
Pull request #226 provided to fix this

**Comment by masterct88** [comment]
Adding "self::" to EXPIRED_SESSION_TIMEOUT; i havent got anymore the warning message.
Thanks.
