### ISSUE TITLE
0.1.10 Error: "The community document server only supports up to 20 concurrent sessions"

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/documentserver_community#224]
I have a strange error after upgrading my Nextcloud to v22 (Community Document Server automatically updated to 0.1.10): `The community document server only supports up to 20 concurrent sessions` even though I'm only user at this moment and I have 3 total users on my instance.
Tried issue #188 - 'dirty fix' but no effect. I'm using PostgreSQL.
There are no logs in error registered when this happens.

**Comment by ThoBunte** [comment]
Same issue - after update we still get message "The community document server only supports up to 20 concurrent sessions"

**Comment by pushakk2** [comment]
Hello,
same here. The error is

"Message":"Use of undefined constant EXPIRED_SESSION_TIMEOUT - assumed 'EXPIRED_SESSION_TIMEOUT' (this will throw an Error in a future version o
f PHP) at /nextcloud/apps/documentserver_community/lib/Channel/SessionManager.php#134","Code":0,"Trace":[{"file":"/nextcloud/apps/documentserver_community/lib/Channel/SessionManager.php","line":134

A non-numeric value encountered at /nextcloud/apps/documentserver_community/lib/Channel/SessionManager.php #134

**Comment by chadek** [comment]
> Same issue for Community server 0.1.10 under NC Version 21.03 - after update we still get message "The community document server only supports up to 20 concurrent sessions"
> Anyone an idea how to rollback to the former version of app?

I check a bit occ cli options and it doesn't seems to support app version. It would be nice feature to have built into this tool.


> I have a strange error after upgrading my Nextcloud to v22 (Community Document Server automatically updated to 0.1.10): `The community document server only supports up to 20 concurrent sessions` even though I'm only user at this moment and I have 3 total users on my instance.
> Tried issue #188 - 'dirty fix' but no effect. I'm using PostgreSQL.
> There are no logs in error registered when this happens.

Onlyoffice simply doesn't work anymore for me (probably since last update).  You may try a workaround playing with licence variable as describe here : https://help.nextcloud.com/t/onlyoffice-community-edition-without-20-connections-limitation/59269/43. Not sure if it will work if the browser is kind of looping on openning connections.

**Comment by Pilzinsel64** [comment]
I already tried increasing and remove the connection limit by editing the php files and restart the server after, but that has no affect. Even after the restart the "connection limit", but it can't be true.

Maybe related to #223 ?

Sorry for the ping, but maybe you @icewind1991 can help?

**Comment by whyronimus** [comment]
Confirm, this bug occured on NC 21.0.3 and with CDS 1.10.

**Hypothesis:** It seems as version 1.10 does not close or delete sessions when the document is closed. In the database, table "oc_documentserver_sess" had over 1200 entries after one day. (i manually augmented the 20 connections limit by editing the PHP files as suggested as 'dirty fix', but this can't be the solution). We observed that sometimes, not even the error message was displayed and overall performance of NC instance was compromised.

With Version 1.9, the table oc_documentserver_sess has zero or just some entries.

**Workaround:** Downgrade to 1.9 manually. First uninstall Community Document Server, then download version 1.9 ZIP and extract to nextcloud/apps folder. Activate via console with occ command. On my install, I had to deactivate and activate again. 

Command: `sudo -u www-data php occ app:disable documentserver_community`
And re-activate: `sudo -u www-data php occ app:enable documentserver_community`

DO NOT occ app:update, it will update to 1.10 again. And of course do not update via GUI.

**Comment by Pilzinsel64** [comment]
Sadly, your solution didn't work. I already tried it multiple times, once again now. Removed CDS app, placed v0.1.9 in /apps, cleared the "oc_documentserver_sess" table, restarted the server, enabled the app, and still the 20 connection limit message. The table "oc_documentserver_sess" stay at zero entries.

**Comment by whyronimus** [comment]
Did you try log out, clearing all browser data and log in again before first-time accessing CDS? 
This is usually necessary when upgrading, so most probably when downgrading.

**Comment by Pilzinsel64** [comment]
Oh sorry, right... Cleared the whole browser cache and now it works again (why didn't I get this idea myself?).
Thank you very much! That's the workaround for now until the "bug" has been fixed.

**Comment by chadek** [comment]
@whyronimus thanks for the tip mate !

**Comment by igherardia** [comment]
hello friends then we have to clear the cache in the browsers of all the users that connect to nextcloud?

**Comment by adi-dev** [comment]
Coming back to the original issue with 0.1.10 - just tested, the `oc_documentserver_sess` table is being populated with new records, but it doesn't get cleared once the page is closed/left. Truncate table does help for a short time.

**Comment by chadek** [comment]
Comparing v0.1.9 and v0.1.10 it appears that EXPIRED_SESSION_TIMEOUT constant is being added to compute cutoffTime like so:
https://github.com/nextcloud/documentserver_community/blob/v0.1.10/lib/Channel/SessionManager.php
```
		$cutoffTime = $this->timeFactory->getTime() -
		        EXPIRED_SESSION_TIMEOUT;
```

cleanSessions function (which should help us here) calls getExpiredSessions where this change is made. I really don't know php so can't really play with that code but I'm pretty sure this might be a lead

**Comment by SebastianBerlin** [comment]
Probably it's also related to the issue I found on my instance since 0.1.10: https://github.com/nextcloud/documentserver_community/issues/220 (solution: I reinstalled the version before)

**Comment by ariesbi** [comment]
Deleted and installed 0.1.11，The problem still exists：The community document server only supports up to 20 concurrent sessions.
the logs:
GuzzleHttp\Exception\ClientException: Client error: `GET http://192.168.50.66/nextcloud/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.oAoRPm5DpEA3wc9OfJYl4C99XMbsXwbZGnDMYVpTKgc` resulted in a `404 Not Found` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found (truncated...)
comannd:
sudo -u www-data php occ onlyoffice:documentserver --check
Error connection: Client error: `GET http://192.168.50.66/nextcloud/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.oAoRPm5DpEA3wc9OfJYl4C99XMbsXwbZGnDMYVpTKgc` resulted in a `404 Not Found` response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found (truncated...)

**Comment by SebastianBerlin** [comment]
That is very very annoying!

**Comment by whyronimus** [comment]
Did anyone here upgrade to version 0.1.11? According to developers, this should be fixed: https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.11

**Comment by adi-dev** [comment]
I think it is fixed. I cannot confirm fully as two of three of my machines' Google Chrome is refusing to purge cache. It works on my personal, Firefox and Chrome okay but two others, I do full refresh, remove cache and cookies, clear app storage but no success, every time the app loads skeleton and that's it. When I will have bit more time, I'll check the console.

**Comment by SebastianBerlin** [comment]
> 
> 
> Did anyone here upgrade to version 0.1.11? According to developers, this should be fixed: https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.11

Yes, but the same issues: https://github.com/nextcloud/documentserver_community/issues/220

**Comment by chadek** [comment]
I upgraded and it work fine for me but I didn't tried ms documents. I think this issue might be close.

**Comment by ThoBunte** [comment]
Updated, to version 0.1.11 - but the message with 20 concurrent Sessions was still there (also if on document only was opened).
So no difference to situation before updating.

**Comment by icewind1991** [comment]
I can't reproduce this problem with 0.1.11, sessions expire as expected

**Comment by chadek** [comment]
It may be some weird stuff still inside the browser cache leading to this issue. Saying that because I still had the issue on an other device which somehow disappeared after a while not using it.

**Comment by ThoBunte** [comment]
After waiting (myaybe one Week after update to version 0.1.11) it works now, without any other changes on installation. 
Curious ;-)
