### ISSUE TITLE
0.1.10 Cannot install on Nextcloud snap 21 on Ubuntu 18.04

### ISSUE THREAD

**Issue by ewan86** [nextcloud/documentserver_community#225]
I am trying to install this on nextcloud, I have tried via the UI and command line. UI returned a generic error. Command line as below. 

> sudo nextcloud.occ app:install documentserver_community
> mmap() failed: [12] Cannot allocate memory
> mmap() failed: [12] Cannot allocate memory

I am running on digital ocean and the previous versions worked fine. I tried uninstalling and reinstalling but it still failed. It also seemed to be stopping nextcloud updating to the latest 21.0 release till it was disabled and caused the whole of nextcloud to stop running. Droplet is base config with 1gb ram.

**Comment by timebotdon** [comment]
Same problem here. I'm only able to start the nextcloud instance normally with this app removed.

**Comment by MaksSharkov** [comment]
I have exactly the same problem. I'm really looking forward to the fix!
