### ISSUE TITLE
Missing 'fonts' directory for adding fonts via documentserver:fonts

### ISSUE THREAD

**Issue by benjaminsabatini** [nextcloud/documentserver_community#228]
Running: 

`sudo -u wwwrun php occ documentserver:fonts --add /usr/share/fonts/truetype/arial.ttf`

In opensuse results in:

`Error: file_put_contents(/.../...documentserver_community/fonts/arial.ttf): Failed to open stream: No such file or directory at /srv/www/htdocs/nextcloud/lib/private/Files/Storage/Local.php#282` in the NC logs.

Which, seems to be caused by the "fonts" directory missing in "documentserver_community". Adding the directory with the correct permissions fixed it. So yeah, add this directory during install of the app, maybe...

**Comment by weasam** [comment]
I upload the fonts in a folder have right permission still could not get it right.
php -d memory_limit=512M ./occ documentserver:fonts --add 
 /home/nextcloud.example.com/public_html/apps/documentserver_community/3rdparty/onlyoffice/documentserver/core-fonts/sans-serif/Roboto-BoldCondensed.ttf
