### ISSUE TITLE
Community Server 0.1.11 unusable

### ISSUE THREAD

**Issue by gcommit** [nextcloud/documentserver_community#229]
When upgrading to 0.1.11 from NC 21 or 22 i can't open old files. Just new ones. It shows this message, but doesn't reload anything. 

<img width="699" alt="Bildschirmfoto 2021-07-28 um 16 36 55" src="https://user-images.githubusercontent.com/18714033/127341661-89e47b18-82d1-4248-9227-f2f50545dad9.png">

**Comment by jhartmann44** [comment]
I'm having the same issue, just tried to open some older files and i get the same error!

**Comment by gcommit** [comment]
Even if i don't update the app, as soon as updating 22.0.0 it is updated to 0.1.11 even if i don't want to. Results in this and not being able to open old files.

**Comment by ariesbi** [comment]
app check error:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- documentserver_community
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [documentserver_community] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

**Comment by MaksSharkov** [comment]
Faced the same problem. This error occurred during manual installation. When installing from the app store, the server crashes.

**Comment by SebastianBerlin** [comment]
Same issue in v.0.1.10, see: https://github.com/nextcloud/documentserver_community/issues/220 and https://github.com/nextcloud/documentserver_community/issues/224

**Comment by gcommit** [comment]
has anyone a fix for this?

**Comment by SebastianBerlin** [comment]
> has anyone a fix for this?

Not yet. Downgrading to 0.1.9 might help: https://github.com/nextcloud/documentserver_community/issues/220#issue-938857087

**Comment by gcommit** [comment]
As far as i know, you can‘t downgrade apps

**Comment by SebastianBerlin** [comment]
> As far as i know, you can‘t downgrade apps

Sure, you can, but only manually – and that works.

**Comment by gcommit** [comment]
How? Can you also tell me how to downgrade?

**Comment by MaksSharkov** [comment]
> How? Can you also tell me how to downgrade?

And me too please :)

**Comment by SebastianBerlin** [comment]
Well, actually it's simple, even if it's a bit dirty without the official install progress: 
1. Deinstall the current app _Community Document Server_ (not ONLYOFFICE) in NextCloud. 
2. Download/Upload/extract the lower version [v0.1.9](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.9) of _documentserver_community.tar.gz_ to /webrootwhatever/apps
3. Give some rights via chmod.
4. Activate the 'old' version in your NextCloud (and don't update).

Keep in mind that I had to fix the ConverterBinary.php (see https://github.com/nextcloud/documentserver_community/issues/195) and the database (https://github.com/nextcloud/documentserver_community/issues/188#issuecomment-805951663) in my case. But that's all.

**Comment by gcommit** [comment]
Weill but it is nothing you do if you manage like a hundret nextclouds... so no solution for me unfortunatly

**Comment by baku104788** [comment]
curious - is the issue behind our errors known / being worked on by the devs?  I've been staying on 0.1.9 also and scared to updated it for fear of breaking things again. Just did a nextcloud system update to 22.1.0 and  the old version of document server is still working fine. I'm a little concerned the days are numbered with this approach though.

**Comment by gcommit** [comment]
I tried to reach out to nextcloud on twitter and different ways, also in the past regarding onlyoffice and they told me to use different apps since this app is not meant for production use. I don't know why, but it seems like they don't care.

**Comment by gcommit** [comment]
@icewind1991 can you help us here?

**Comment by gcommit** [comment]
Guess no one is interested in fixing critical bugs....
