### ISSUE TITLE
Comments and chats should be integrated with the NC

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/documentserver_community#23]
I observe that with Onlyoffice there is potential fragmentation in using communication channels with users when editing documents, as there are comments and chats to the document provided by NC itself, plus there're own services suggested by Onlyoffice. In my opinion we have to have only one way of providing comments and chats in order not to mislead users.

![image](https://user-images.githubusercontent.com/5199030/72733761-2da84f80-3ba1-11ea-8482-2199ceb00d04.png)

**Comment by hydro-b** [comment]
I agree. I would suggest to use the chats provided by nextcloud, as those are independent from the office implementation (OnlyOffice, Collabora Online, etc.).

Note: in NC 18.0.0 the chat function in Onlyoffice does not work currently: [https://help.nextcloud.com/t/chat-is-not-working-in-onlyoffice-community-version/68715/7](url)
And in NC 18.0.0 the NC native chat is not enabled when working in OnlyOffice.

**Comment by felisucoibi** [comment]
I hope we can use chat in the onlñyoffice app could be perfect
