### ISSUE TITLE
Cannot save docx documents

### ISSUE THREAD

**Issue by cabrillo** [nextcloud/documentserver_community#234]
Hi Guys,
I just install onlyoffice document server app (0.1.11) and onlyoffice (7.1.2) in our nextcloud suit with 20.0.6 v.
Documents are opened fine and we can edit, but docx documents can be save the is no error on dashboard but document is not saved, even autosave is forced but does not work...xls files are saved fine.

Any Idea About this error. Any help is welcomed.

I attach a pic with the selected conf options for onlyoffice app:
![Selección_136](https://user-images.githubusercontent.com/7745602/134126872-8948bce2-9538-4c41-bd16-dadca95c6c55.png)

Regards, I

**Comment by himpierre** [comment]
Same problem here. Nothing in the logs. :/

**Comment by cabrillo** [comment]
H,
@himpierre Some times work, but not usually mostly doesn't. We do no use master key.
Regards, I

**Comment by cabrillo** [comment]
Hi any news about this issue? Any recommendation?
regards, I
