### ISSUE TITLE
OnlyOffice Versioning history - problem “Opening Document”

### ISSUE THREAD

**Issue by lord-kyron** [nextcloud/documentserver_community#238]
Hi,
I am using nextcloud installed on Ubuntu 20.04 with nginx according to the documentation and it all works well.
I have setup APCu and Redis caching.
However - when I open docx document with onlyoffice - it opens fine and can be rad/write. But when I try to open the Collaboration → Versioning menu to see document versions - I get the “Opening Document” message and spins indefinitely. Strange thing here is is not crashing or reporting any errors over the logs. Nextcloud is working and can click and get back to files and folders - only OnlyOffice seems stuck during this indefinite opening.
Nextcloud is latest - 22.2.0 with latest apps for onlyoffice installed.
onlyoffice:documentserver --check returns:
`Document server version 6.3.1 is successfully connected`
(I stripped the URL for security)

Can someone suggest what is the problem and how to fix it?
I have tried to disable all kinds of memcaches I am using but with no success.
I haven’t changed any onlyoffice settings - just installed and it was working by default fine until I discovered this problem.

Here is some screenshot of the problem:
![image](https://user-images.githubusercontent.com/39150122/139208446-55023044-6b51-47f3-b851-9b33153ea4f9.png)

**Comment by Corinari** [comment]
We are also affected by this bug, this will also drive people away from NC to MS Teams, so a quick solution would be nice

**Comment by ostasevych** [comment]
The same with 23.0.1. Still no solution?

**Comment by ostasevych** [comment]
The same with NC 24.0.6 and Community Document Server v.0.1.12 (
