### ISSUE TITLE
Missing added fonts in GUI dropdown list

### ISSUE THREAD

**Issue by kostik2022** [nextcloud/documentserver_community#241]
I'm trying to adding some TrueType fonts,
Fon management (`occ documentserver:fonts --add ... `) work fine, I also got a list of my fonts installed:
```
# occ documentserver:fonts
AKAMA.ttf
AKAMABD.ttf
AKAMABI.ttf
AKAMAI.ttf
bab_____.ttf
babi____.ttf
bai_____.ttf
balaram_.ttf
```
But this new fonts are not shown in dropdown list in the OpenOffice editor.
Looks like the file ` documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/common/AllFonts.js` should also be updated, but it's not.

I tried `occ documentserver:fonts --rebuild` , but no luck.

I use latest Nextcloud 22 and latest OnlyOffice app in it.

**Comment by mehlkopf** [comment]
Would be great to get some help here, I have exactly the same problem (up-to-date Nextcloud and documentserver/OnlyOffice apps). Thank you!
