### ISSUE TITLE
Safari gives "An error has occured while opening the file"

### ISSUE THREAD

**Issue by prghix** [nextcloud/documentserver_community#242]
Hello,

I've noticed exactly this behavious mentioned in this issue mentioned in the OO repo:

  https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/541

![image](https://user-images.githubusercontent.com/52444671/142800920-130f6fd6-86bc-45ef-aea3-17fc1796e904.png)

My environment:

Nextcloud 21.0.5
PHP 7.4.25

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - documentserver_community: 0.1.11
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_texteditor: 2.14.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - group_default_quota: 0.1.2
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.2.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1

Tried to disable: "Open on the same tab" -> No change.

**Comment by acalatrava** [comment]
bump! same issue, both on Safari on Mac and iOS
