### ISSUE TITLE
Huge /documentserver_community subfolder in /appdata_oc[...]

### ISSUE THREAD

**Issue by nelsoncarr** [nextcloud/documentserver_community#244]
Hello,

we're have been facing the following issue:

We had OnlyOffice and Community Document Server installed on our Nextcloud (Version 22.2.3.0, it is run by a service provider, we have no direct access to the server).
(OnlyOffice: https://apps.nextcloud.com/apps/onlyoffice)
(Community Document Server: https://apps.nextcloud.com/apps/documentserver_community)

We only used OnlyOffice very rarely. However, it seemed to take up enormous amounts of storage:

We were informed that the folder "appdata_oc[XXXXXXXXXX]/documentserver_community" has three subfolders taking up over 300GB of space:

99.3 GiB [##########] /doc_2329[XXXXXX]
98.8 GiB [######### ] /doc_4141[XXXXXX]
97.9 GiB [######### ] /doc_3905[XXXXXX]

As we hardly use OnlyOffice, I have now deactivated and removed both OnlyOffice and Community Document Server apps, but the huge folder "documentserver_community" in "appdata_oc[XXXXXXXXXX]" is still there.

*My question:*
Is it safe to delete the folder "documentserver_community" after both of these apps are already removed?
All our documents (.docx, .xlsx, .ods, etc) are in their respective folders _within_ our nextcloud folder tree.

Or is there a possibility that removing this remaining folder (both apps are removed) will break things or lead to data loss?

Thank you in advance.

**Comment by marcinkoziej** [comment]
Not an expert here but I suppose you can safely remove them.
The nextcloud files should reside in nextcloud file storage (`files` directory?). You can make a tar archive backup if this makes you more comfortable, Nelson.
