### ISSUE TITLE
Unable to edit docx document

### ISSUE THREAD

**Issue by DeepCollors** [nextcloud/documentserver_community#254]
Unable to edit docx document
![image](https://user-images.githubusercontent.com/53312637/158190683-74f08620-2649-4923-a2c7-e232b58fff64.png)

**Comment by cabrilloji** [comment]
Any advance with this issue?, we are getting same behaviour after upgrade to NC23.X

**Comment by DeepCollors** [comment]
Nextcloud 24.0.2 situation persists

**Comment by nooblag** [comment]
Also reporting this issue in Nextcloud 24.0.2.

**Comment by AtaZ991** [comment]
UP. In clean install also not working.

**Comment by AtaZ991** [comment]
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/576 - it not a bug))
