### ISSUE TITLE
Make Error 1

### ISSUE THREAD

**Issue by bigAboo80** [nextcloud/documentserver_community#255]
Hi, after make command I saw this

docker cp oo-extract:/var/www/onlyoffice/documentserver 3rdparty/onlyoffice
docker rm oo-extract
oo-extract
rm -r 3rdparty/onlyoffice/documentserver/server/{Common,DocService}
rm: cannot remove '3rdparty/onlyoffice/documentserver/server/{Common,DocService}': No such file or directory
make: *** [Makefile:20: 3rdparty/onlyoffice/documentserver] Error 1

After that,  installed Onlyoffice app

In web UI see ONLYOFFICE app not available, please contact your admin
How to solve this issue?

**Comment by smolinde** [comment]
Hi, I have a similar issue on my Ubuntu 20.04 LTS installation. The problem I found could be resolved really fast because after getting the previously mentioned message:
`ONLYOFFICE app not available, please contact your admin`
The error logs show a PHP error and state that there is a missing bracket. I don't have the exact error log but I could reproduce it later and post here again if this issue does not get resolved. I guess it was just a typo while coding :)

**Comment by King-GO** [comment]
> Hi, I have a similar issue on my Ubuntu 20.04 LTS installation. The problem I found could be resolved really fast because after getting the previously mentioned message: `ONLYOFFICE app not available, please contact your admin` The error logs show a PHP error and state that there is a missing bracket. I don't have the exact error log but I could reproduce it later and post here again if this issue does not get resolved. I guess it was just a typo while coding :)

Yes, please

**Comment by smolinde** [comment]
**First error log:**

Exception: sh: 1: ../../tools/allfontsgen: Exec format error
/var/www/nextcloud/apps/documentserver_community/lib/LocalAppData.php - line 80:
OCA\DocumentServer\Document\FontManager->OCA\DocumentServer\Document\{closure}("*** sensiti ... *")
/var/www/nextcloud/apps/documentserver_community/lib/Document/FontManager.php - line 78:
OCA\DocumentServer\LocalAppData->getReadLocalPath()
/var/www/nextcloud/apps/documentserver_community/lib/Migration/RebuildFonts.php - line 52:
OCA\DocumentServer\Document\FontManager->rebuildFonts()
/var/www/nextcloud/lib/private/Repair.php - line 124:
OCA\DocumentServer\Migration\RebuildFonts->run()
/var/www/nextcloud/lib/private/legacy/OC_App.php - line 1071:
OC\Repair->run()
/var/www/nextcloud/lib/private/Installer.php - line 157:
OC_App::executeRepairSteps()
/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 452:
OC\Installer->installApp()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Settings\Controller\AppSettingsController->enableApps()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 36:
OC::handleRequest()

**Second error log:**

OCA\DocumentServer\Document\DocumentConversionException: sh: 1: ./x2t: Exec format error
/var/www/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php - line 74:
OCA\DocumentServer\Document\ConverterBinary->run()
/var/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php - line 36:
OCA\DocumentServer\Document\ConverterBinary->test()
/var/www/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php - line 93:
OCA\DocumentServer\SetupCheck->check()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\DocumentServer\Controller\StaticController->webApps()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 36:
OC::handleRequest()

**Third error log:**

Exception: trim() expects parameter 1 to be string, bool given in file '/var/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php' line 82
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 36:
OC::handleRequest()

**Comment by bigAboo80** [comment]
> missing bracket

Where? In the makefile? in the config.php?)

**Comment by smolinde** [comment]
Sorry, I couldn't reproduce it anymore because I forgot how I did it. The error log that I posted before is taken from the Nextcloud logging webapp. I also forgot to mention my setup:

- Raspberry Pi 4B (8GB)
- Ubuntu 20.04 LTS
- Nextcloud 23.0.3.2
