### ISSUE TITLE
No Text when i Print or export to PDF

### ISSUE THREAD

**Issue by ghost** [nextcloud/documentserver_community#257]
[](https://user-images.githubusercontent.com/63787421/161824276-19c6b893-e2d4-4f7a-9595-1f4bb4c3536d.png)[](https://user-images.githubusercontent.com/63787421/161824374-0ae4b873-796e-4515-b901-1555a1466cf5.png)Hi together,
I noticed that in my OnlyOffice installed in Nextcloud, I can't print files or export to PDF without losing the text. As soon as I save something Print/PDF in Document/Table/Presentation all text is lost.

Versions:
Nextcloud Hub II (23.0.3)
Community Document Server 0.1.12
ONLYOFFICE 7.3.2

![grafik](https://user-images.githubusercontent.com/63787421/162034435-67724872-c4b4-4008-b1c0-a87ea455d747.png)
![grafik](https://user-images.githubusercontent.com/63787421/162034452-436b4828-a7c8-4ff2-a19b-223a353da832.png)

**Comment by Qualitymix** [comment]
I am also experiencing this exact issue.

**Comment by jvels** [comment]
I also have same issue.

**Comment by svegan** [comment]
There is already [ticket](https://github.com/nextcloud/documentserver_community/issues/251) about it..

**Comment by latency0ms** [comment]
All users seem to be affected by this problem - when fix?

```
Community Document Server 0.1.12
ONLYOFFICE 7.3.4
Nextcloud 22.2.7
```
