### ISSUE TITLE
Cant install the App

### ISSUE THREAD

**Issue by Jaxophon** [nextcloud/documentserver_community#26]
When I try to install the Community Document Server App it take a moment and then it shows me just a message in the right upper corner. It says that a failure occurred and that its not possible to continue. How can I fix it?

**Comment by bram-smeets** [comment]
I also have this same error. Managed to install it once before but got the "Community document server is not supported for this instance, please setup and configure an external document server" error. Tried to reinstall but I can no longer get it to properly install. If I press the "Install and enable" button twice it will show as enabled but doesn't work.

**Comment by teutat3s** [comment]
After updating from NC17 to NC18 I'm trying to install this documentserver_community app, but I get the following error:

```
cURL error 28: Operation timed out after 30000 milliseconds with 184680972 out of 305964280 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```

**Comment by guzzisti** [comment]
There's already a workaround mentioned in the Forums: https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603/11

A bug report for nextcloud server is linked above. This issue should be closed.

@bram-smeets 
Please don't mix up different topics in a single issue.

**Comment by Wikinaut** [comment]
Same error for me:
![grafik](https://user-images.githubusercontent.com/1151915/72937248-0d2af180-3d69-11ea-9f75-a1c7a5f5f049.png)

**Comment by Jaxophon** [comment]
Has a solution been found?

**Comment by InfamousUser** [comment]
Same error here:
"cURL error 28: Operation timed out after 30000 milliseconds with 130053548 out of 315860148 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)".

Don't understand how one can even install the app server.

**Comment by CNtester** [comment]
Same error here:
cURL error 28: Operation timed out after 30000 milliseconds with 104536300 out of 315860148 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

is installing manually the only solution?

**Comment by sschuepfer** [comment]
The same problem with new installation on docker x86

**Comment by InfamousUser** [comment]
I fixed the issue by editing the suggested config file, until the 18.0.1 fix.

**Comment by thomasgg23** [comment]
The workaround in the link from @guzzisti also works for me

**Comment by badsmile82** [comment]
> 
> 
> Same error for me:
> ![grafik](https://user-images.githubusercontent.com/1151915/72937248-0d2af180-3d69-11ea-9f75-a1c7a5f5f049.png)

i have the same issue :-(

**Comment by Jaxophon** [comment]
> I fixed the issue by editing the suggested config file, until the 18.0.1 fix.

How do you fixed it? I still cant install the "Community Document Server" app.

**Comment by essys** [comment]
> > I fixed the issue by editing the suggested config file, until the 18.0.1 fix.
> 
> How do you fixed it? I still cant install the "Community Document Server" app.

guzzisti provided a link to a workaround which is working.
https://github.com/nextcloud/documentserver_community/issues/26#issuecomment-577345765

**Comment by InfamousUser** [comment]
Isn't a workaround, it's a direct fix. They changed or implemented this value in v18.

**Comment by KoljaL** [comment]
> is installing manually the only solution?

https://www.c-rieger.de/nextcloud-alert/
