### ISSUE TITLE
Add support for NextCloud 24

### ISSUE THREAD

**Issue by Kitanit** [nextcloud/documentserver_community#260]

**Comment by Kitanit** [comment]
@icewind1991 is the project still alive?

**Comment by peppinoita** [comment]
+ 1

**Comment by James-Oakley** [comment]
Yes, +1: Once this supports NC24, I can update my NextCloud to 24.x, which then means I can update the server's PHP to 8.1

**Comment by Kitanit** [comment]
> Yes, +1: Once this supports NC24, I can update my NextCloud to 24.x, which then means I can update the server's PHP to 8.1

I think the repository is dead :(

**Comment by phonon112358** [comment]
really?? Is it dead? :( It has made it much easier to use onlyoffice-documentserver ... 
That would be really terrible if one has to deal with reverse proxies or docker images again ....

**Comment by Ludovicis** [comment]
unfortunately this project is not progressing much. I am currently running OnlyOffice version 7 on my nextcloud 24 with no problem.
https://github.com/nextcloud/documentserver_community/issues/250
If you want this app on netcloud 24 change in appinfo/info.xml this line
	<dependencies>
		<nextcloud min-version="21" max-version="23"/>
	</dependencies>

By:
	<dependencies>
		<nextcloud min-version="21" max-version="24"/>
	</dependencies>

**Comment by James-Oakley** [comment]
@Ludovicis I had already seen that I could make that simple change. But telling a plugin that it is compatible with a later version of NextCloud isn't quite the same as making sure it will work without problems and is genuinely compatible. It also kicks the can down the road until the day comes when there is a breaking change in the core NextCloud code and more changes are needed than bumping the max-version.

**Comment by Ludovicis** [comment]
@James-Oakley I never said that this would not affect the operation of nextcloud. In any case for me it works perfectly without side effects on nextcloud. Users have a choice whether or not to apply these changes. Some people don't know about this possibility.

**Comment by James-Oakley** [comment]
@Ludovicis I appreciate you saying that it works without issue for the current release. 😃

**Comment by phonon112358** [comment]
Great! ;) Do you know if it's working with php 8.1?

**Comment by Ludovicis** [comment]
![image](https://user-images.githubusercontent.com/16205280/170023375-ebda35cb-f7d3-41da-a17f-9e293d504c22.png)
![image](https://user-images.githubusercontent.com/16205280/170023623-8b8c9c90-31e2-4f93-b933-a9f0920194d0.png)

Sorry i don't know if it's working with php 8.1

**Comment by Kitanit** [comment]
> It is working! ;) I just tested it.
> 
> The app seems to be fully compatible with NC 24 and php 8.1.
need to edit the code then, but the owner of the repository seems to ignore it, so it will be a problem, and it's just a config line

**Comment by Kitanit** [comment]
I'll try to write him an email, maybe at least that way he will notice
![image](https://user-images.githubusercontent.com/65107731/170825525-632852db-00c5-4111-acc8-09562f12378f.png)


*I corrected the error that phonon112358 had
![image](https://user-images.githubusercontent.com/65107731/170825549-11bdede8-d8bc-467a-b4aa-23a63d84fd45.png)

**Comment by phonon112358** [comment]
Thanks! ;)

**Comment by b-pfl** [comment]
+1 regarding the support of NC24 @icewind1991

**Comment by hardingt** [comment]
@Kitanit any luck? I'm not holding my breath :(

**Comment by ml31415** [comment]
A shame to see, that there can not be a maintainer for even just accepting a PR every now and then ... :(

**Comment by BurtGummer** [comment]
After Collabora Online is also not installable on my server (there is no app named "Collabora Online") and I also read about numerous problems with Collabora on github, I will uninstall both apps. Conclusion: a reliable solution looks different.

**Comment by RegentGaudreau** [comment]
+1 also for NC24 support

**Comment by strongthony** [comment]
adding +1 for NC24 and continued support. Please.

**Comment by Kitanit** [comment]
repo dead

**Comment by nachilau** [comment]
Sorry, I am very new to NextCloud, how can I edit the file in nextcloud? I have no permission for /var/www/nextcloud/apps, when I cd into it, I got permission denied. How can I change the /appinfo/info.xml ?

**Comment by ml31415** [comment]
@Kitanit would you volunteer as an occasional maintainer, so that we can suggest to the nextcloud team to add you as a maintainer for this repo?

**Comment by Kitanit** [comment]
> @Kitanit would you volunteer as an occasional maintainer, so that we can suggest to the nextcloud team to add you as a maintainer for this repo?

I would love to, but my knowledge of code is too little to work with (+ no time)

**Comment by Kitanit** [comment]
> On the settings page (Version) Nextcloud tells me, there were compatible Versions for all my apps when upgrading to 24 - including Document Server. Can anybody tell, how this is possible? As far as I can see, the app hasn't been updated.

Bug 🤔

**Comment by mtnbiker777** [comment]
> unfortunately this project is not progressing much. I am currently running OnlyOffice version 7 on my nextcloud 24 with no problem. #250 If you want this app on netcloud 24 change in appinfo/info.xml this line nextcloud min-version="21" max-version="23" By: nextcloud min-version="21" max-version="24"

I must have missed something I made the change to the file located in  /var/www/nextcloud/apps/documentserver_community/appinfo/info.xml and it still says it's not compatible with 24. What did I missed?

**Comment by g-work** [comment]
Same here: https://github.com/nextcloud/documentserver_community/issues/269#issuecomment-1272576677

**Comment by ml31415** [comment]
@aaronhuggins would you volunteer to take over maintenance for this package for some time? Just the most necessary stuff like those version updates at least? Then I'd just suggest you to nextcloud and hope for the best.

**Comment by aaronhuggins** [comment]
@ml31415 I have a vested interested in keeping this working and would totally be up for maintaining this. I'd rather fix and enhance this Nextcloud app rather than fork it. My family needs a portable cloud editor/viewer, and the VPS we're on doesn't support the AppImage for the CODE server, and we're not a big enough install to warrant paying for a separate document editor server.

I'm motivated to revisit this every few months and ensure the document server is up to date and working, if not also get some improvements out the door (for which I already have ideas!).

**Comment by ml31415** [comment]
@icewind1991 would you mind granting maintainer rights to @aaronhuggins , so that we can get this package up and running again? Big big please :)

**Comment by g-work** [comment]
New [release](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.13) available!
Thanks, @icewind1991 @aaronhuggins
