### ISSUE TITLE
Cannot GET //printfile/<>

### ISSUE THREAD

**Issue by nobe80** [nextcloud/documentserver_community#265]
Hi,

we use OnlyOffice community in a docker container version 7.1.1 in connection with Seafile.
All the things works fine so far (working, viewing, saving e.g.) 
When we try to print we get always an error that it cannot GET the printfile (see screenshot)
This happens by word, excel, powerpoint.
Do you have an idea whats going wrong here?

regards

![print_error_onlyoffice](https://user-images.githubusercontent.com/66213908/175316840-3ab0fb37-3a6d-4b63-a277-b16c7754fdc8.PNG)

**Comment by k0stett** [comment]
Have same problem

**Comment by k0stett** [comment]
Found that there is an extra slash in the beggining of PDF's URL. Trying to find where it appears.
