### ISSUE TITLE
Remove the app as it is not maintained anyway

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/documentserver_community#268]
Is it obvious that nobody seems to care about this app. A number of pull requests since May 2021(!) are not merged at all and there is also no feedback on that by the maintainer.

In addition there still still an open issue like #100 and still people think that https://apps.nextcloud.com/apps/documentserver_community is worth trying despite the bad reviews.

Please save the time of people who may try this app and avoid further frustration.

**Comment by lusmo** [comment]
Agreed! I spent a lot of time testing for nothing :-(

**Comment by mrbaseman** [comment]
Please could someone take care of this app. It's not as bad as some comments suggest. The main problem is that contributions aren't merged, and so it's no more compatible with latest nextcloud releases. That's really a pity.

**Comment by aaronhuggins** [comment]
Hey all, if you want to take a risk, I've got an update here:
https://github.com/nextcloud/documentserver_community/pull/274#issuecomment-1301051703

Not sure who to bug at Nextcloud to get this pulled in and released.

**Comment by g-work** [comment]
New [release](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.13) available!
Thanks, @icewind1991 @aaronhuggins
