### ISSUE TITLE
Feature request: allow admin to modify maximum connections

### ISSUE THREAD

**Issue by sunjam** [nextcloud/documentserver_community#27]
I’d like to request allowing admins to configure their own maximum numbers of “connections” from within Nextcloud admin settings.  The arbitrary limit is set at 20 users and 10 documents in OnlyOffice CE, as well as Nextcloud Hub.  You are currently keeping this setting in a php file.

Thanks for your consideration!

As is, admins have to manually build OnlyOffice CE or create their own Docker compose to circumvent this limitation, making system maintenance more complex.  Hopefully, this process can be simplified with the new release of Hub.

Please note, this is already a heavily requested feature on help.nextcloud.com

Also see [this request for documentation of limitations](https://github.com/nextcloud/documentserver_community/issues/19).

**Comment by skjnldsv** [comment]
This is enforced by OnlyOffice as far as I know :)

**Comment by SimonMGS** [comment]
How does AGPL software have "enforced" restrictions?

**Comment by autoize** [comment]
We strongly believe that a developer’s rights to monetize a derivative work based on GPL (or in the case of OnlyOffice, AGPL v.3) open source code should not be impeded. At the same time, they should respect the fundamental freedoms of others to use, modify, and distribute open source code. This is only fair to the developers who came before them, contributing to the work that they themselves modified.

Here is how anyone can [build OnlyOffice Document Server from the source code](https://autoize.com/building-onlyoffice-document-server-from-source/), and [modify the max connection limit](https://autoize.com/building-onlyoffice-document-server-from-source/) - if they wish. The official OnlyOffice documentation has some outdated instructions and missing steps, so we hope that the NextCloud community will find this updated guide useful.

Building any software from the source code is not a straight-forward process, as the build environment (particularly dependencies) can impact its success or failure. For this reason, we believe the developers will continue to find more than enough paying users to support future development. Red Hat, and other major companies who have built billion-dollar businesses based on commercial support for open source software are living proof of this.

**Comment by CoreyBurger** [comment]
All the building stuff is irrelevant to this case, as the restriction in this version is in the PHP, which means it can be changed on trivially

**Comment by SimonMGS** [comment]
Yes, applies to the original version. Still very useful, though, since that might be a better option than the new codebase. It will also let us compare performance with the Nextcloud version.

**Comment by skjnldsv** [comment]
DIscussion was reopened here and is more active: https://github.com/nextcloud/documentserver_community/issues/31

Thanks for your constructive comments everyone! :hugs:

**Comment by SimonMGS** [comment]
Ah, but will we get an honest answer in the other thread, like the one you gave us? :speak_no_evil:

**Comment by skjnldsv** [comment]
> Ah, but will we get an honest answer in the other thread, like the one you gave us?

No idea  if sarcastic or not, but I'm no medium and cannot predict the future :wink: :crystal_ball:
