### ISSUE TITLE
Mobile editing not working

### ISSUE THREAD

**Issue by reysonk** [nextcloud/documentserver_community#276]
In version 0.1.13, unlike 0.1.12, the mobile editing functionality refers to the purchase of a license.
In version 0.1.12 this functionality is available

**Comment by aaronhuggins** [comment]
Mobile editors have always required a license for the community edition, which is bundled in this app. If the editors fro mobile were working, your server admin may have previously implemented a workaround (which I will not link).

You can refer to the feature matrix here.
- Latest: https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions
- v6.4.2 (which was bundled in app v0.1.12): https://github.com/ONLYOFFICE/DocumentServer/tree/v6.4.2#onlyoffice-document-server-editions

**Comment by aaronhuggins** [comment]
@reysonk If you read the official documentation for OnlyOffice, mobile editors are not enabled without a license. I've had a warning for mobile since 2018.

@icewind1991 Do you know how or why mobile editors would have worked in the previous app version?

**Comment by aaronhuggins** [comment]
You're arguing for features which OnlyOffice lists as being outside the support of their released AGPL licensed code. All this project does is wrap the community edition of their document server as a convenience. If you require additional functionality that onlyOffice says is not supported, you'll need to work with or around it. As far as my work to upgrade this app goes, I don't think we should modify the bundled code as that would violate the license.

**Comment by reysonk** [comment]
> You're arguing for features which OnlyOffice lists as being outside the support of their released AGPL licensed code. All this project does is wrap the community edition of their document server as a convenience. If you require additional functionality that onlyOffice says is not supported, you'll need to work with or around it. As far as my work to upgrade this app goes, I don't think we should modify the bundled code as that would violate the license.

I agree with you, but for 3 years I used the version from this branch and had no problems with mobile editing until version 0.1.13.
Moreover, about 6 months ago I deployed a clean server at my facilities and in the cloud, mobile editing works on my home server and in the cloud.
I considered this version an official branch of nextcloud, according to the GNU AGPL
