### ISSUE TITLE
PDF not working

### ISSUE THREAD

**Issue by tiongiedca** [nextcloud/documentserver_community#277]
I thought the problem was in the encoding of files. I checked on a variety of different documents - it does not work as on iPhone, as on Desktop.

<img width="1440" alt="Снимок экрана 2022-11-10 в 21 23 30" src="https://user-images.githubusercontent.com/16136291/201179170-b5c23b3b-1132-4a86-b068-57da08d015c7.png">

Nextcloud logs:

[index] Error: OCA\DocumentServer\Document\DocumentConversionException: Segmentation fault (core dumped)
 at <<closure>>

 0. /var/www/cloud.server.com/apps/documentserver_community/lib/DocumentConverter.php line 125
    OCA\DocumentServer\Document\ConverterBinary->run()
 1. /var/www/cloud.server.com/apps/documentserver_community/lib/DocumentConverter.php line 113
    OCA\DocumentServer\DocumentConverter->runCommand()
 2. /var/www/cloud.server.com/apps/documentserver_community/lib/DocumentConverter.php line 49
    OCA\DocumentServer\DocumentConverter->convertFiles()
 3. /var/www/cloud.server.com/apps/documentserver_community/lib/Document/DocumentStore.php line 98
    OCA\DocumentServer\DocumentConverter->getEditorBinary()
 4. /var/www/cloud.server.com/apps/documentserver_community/lib/LocalAppData.php line 102
    OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/cloud.server.com/apps/documentserver_community/lib/Document/DocumentStore.php line 99
    OCA\DocumentServer\LocalAppData->getReadWriteLocalPath()
 6. /var/www/cloud.server.com/apps/documentserver_community/lib/XHRCommand/OpenDocument.php line 101
    OCA\DocumentServer\Document\DocumentStore->getDocumentForEditor()
 7. /var/www/cloud.server.com/apps/documentserver_community/lib/XHRCommand/AuthCommand.php line 130
    OCA\DocumentServer\XHRCommand\OpenDocument->openDocument()
 8. /var/www/cloud.server.com/apps/documentserver_community/lib/XHRCommand/CommandDispatcher.php line 47
    OCA\DocumentServer\XHRCommand\AuthCommand->handle()
 9. /var/www/cloud.server.com/apps/documentserver_community/lib/Channel/Channel.php line 107
    OCA\DocumentServer\XHRCommand\CommandDispatcher->handle()
10. /var/www/cloud.server.com/apps/documentserver_community/lib/Controller/SessionController.php line 116
    OCA\DocumentServer\Channel\Channel->handleCommand()
11. /var/www/cloud.server.com/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\DocumentServer\Controller\SessionController->xhrSend()
12. /var/www/cloud.server.com/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
13. /var/www/cloud.server.com/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
14. /var/www/cloud.server.com/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
15. /var/www/cloud.server.com/lib/base.php line 1030
    OC\Route\Router->match()
16. /var/www/cloud.server.com/index.php line 36
    OC::handleRequest()

POST /apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/2152595431/c/616/n4amid2g/xhr_send?t=1668104403901

**Comment by g-work** [comment]
Is this the same as #251?

**Comment by mrbaseman** [comment]
it seems so, yes.
