### ISSUE TITLE
No changes when you work together

### ISSUE THREAD

**Issue by AtaZ991** [nextcloud/documentserver_community#279]
After update to 0.1.13, when I work together in onlyoffice files, I can see only cursor, but don't see any changes.

**Comment by alozovskij** [comment]
the problem remained in 0.1.16

**Comment by McSchiller** [comment]
We can confirm that

**Comment by TechanisYT** [comment]
issue still present on my system. i only see the cursor and for all other changes i have to reload the page on both sides
