### ISSUE TITLE
Error: OCA\DocumentServer\Document\DocumentConversionException: TypeError: this.Ia.HK is not a function

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/documentserver_community#282]
Nextcloud: 24.0.7
documentserver_community: 0.1.13
onlyoffice: 7.5.8
=================================
messages every 1-2 Minutes
=================================
[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: TypeError: this.Ia.HK is not a function
    at we.Sc.Ij (<anonymous>:18933:198)
    at we.Gb.TG (<anonymous>:18948:85)
    at mm.Rh (<anonymous>:19931:159)
    at za.C.asc_docs_api.asc_nativeApplyChanges2 (<anonymous>:11253:127)
Uncaught TypeError: this.Ia.HK is not a function
DoctRenderer:<result><error index="759" /></result>
 at <<closure>>

0. /var/www/html/nextcloud/apps/documentserver_community/lib/DocumentConverter.php line 125
   OCA\DocumentServer\Document\ConverterBinary->run()
1. /var/www/html/nextcloud/apps/documentserver_community/lib/DocumentConverter.php line 80
   OCA\DocumentServer\DocumentConverter->runCommand()
2. /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php line 156
   OCA\DocumentServer\DocumentConverter->saveChanges()
3. /var/www/html/nextcloud/apps/documentserver_community/lib/LocalAppData.php line 102
   OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensitive parameters replaced ***")
4. /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php line 176
   OCA\DocumentServer\LocalAppData->getReadWriteLocalPath()
5. /var/www/html/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php line 58
   OCA\DocumentServer\Document\DocumentStore->saveChanges()
6. /var/www/html/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php line 71
   OCA\DocumentServer\Document\SaveHandler->flushChanges()
7. /var/www/html/nextcloud/lib/public/BackgroundJob/Job.php line 79
   OCA\DocumentServer\BackgroundJob\Cleanup->run()
8. /var/www/html/nextcloud/cron.php line 151
   OCP\BackgroundJob\Job->execute()

**Comment by g-work** [comment]
I have a similiar issue; it also seems connected to cron, but shows up only once an hour: #286
