### ISSUE TITLE
kernel: x2t[792851]: segfault at 78 ip sp  error 4 in libgraphics.so

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/documentserver_community#283]
Nextcloud: 24.0.7
documentserver_community: 0.1.13
onlyoffice: 7.5.8
ocurrs every time a document is accessed by nextcloud onlyoffice/documentserver

OS: RHEL 8.6
=========================================================

Process 792851 (x2t) of user 48 dumped core.
CODE_FILE
../src/coredump/coredump.c
CODE_FUNC
submit_coredump
CODE_LINE
822
COREDUMP_CGROUP
/system.slice/php-fpm.service
COREDUMP_CMDLINE
./x2t /tmp/oc_tmp_EQwQ8u-.xml
COREDUMP_COMM
x2t
COREDUMP_CWD
/var/www/html/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin
COREDUMP_ENVIRON
PWD=/var/www/html/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin SHLVL=1 _=./x2t
COREDUMP_EXE
/var/www/html/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/x2t
COREDUMP_GID
48
COREDUMP_HOSTNAME
xxx.xxx.xxx
COREDUMP_OPEN_FDS
0:pipe:[13779203] pos: 0 flags: 00 mnt_id: 14 1:pipe:[13779204] pos: 0 flags: 01 mnt_id: 14 2:pipe:[13779205] pos: 0 flags: 01 mnt_id: 14 4:/var/lib/sss/mc/passwd pos: 0 flags: 02100000 mnt_id: 379 7:socket:[13779197] pos: 0 flags: 02 mnt_id: 10 8:socket:[13779198] pos: 0 flags: 02 mnt_id: 10 10:socket:[13776413] pos: 0 flags: 02 mnt_id: 10 12:socket:[30482] pos: 0 flags: 02 mnt_id: 10 13:pos: 126274 flags: 0100000 mnt_id: 411 14:/tmp/oc_tmp_EQwQ8u-.xml pos: 728 flags: 0100001 mnt_id: 414
COREDUMP_PID
792851
COREDUMP_PROC_CGROUP
12:pids:/system.slice/php-fpm.service 11:hugetlb:/ 10:blkio:/ 9:freezer:/ 8:memory:/system.slice/php-fpm.service 7:cpuset:/ 6:devices:/system.slice/php-fpm.service 5:rdma:/ 4:cpu,cpuacct:/ 3:perf_event:/ 2:net_cls,net_prio:/ 1:name=systemd:/system.slice/php-fpm.service
COREDUMP_PROC_LIMITS
Limit Soft Limit Hard Limit Units Max cpu time unlimited unlimited seconds Max file size unlimited unlimited bytes Max data size 4294967296 4294967296 bytes Max stack size 8388608 unlimited bytes Max core file size 0 unlimited bytes Max resident set unlimited unlimited bytes Max processes 38970 38970 processes Max open files 1024 262144 files Max locked memory 65536 65536 bytes Max address space unlimited unlimited bytes Max file locks unlimited unlimited locks Max pending signals 38970 38970 signals Max msgqueue size 819200 819200 bytes Max nice priority 0 0 Max realtime priority 0 0 Max realtime timeout unlimited unlimited us
COREDUMP_PROC_MAPS
[keine Daten]
COREDUMP_PROC_MOUNTINFO
[keine Daten]
COREDUMP_PROC_STATUS
Name: x2t Umask: 0022 State: S (sleeping) Tgid: 792851 Ngid: 0 Pid: 792851 PPid: 792810 TracerPid: 0 Uid: 48 48 48 48 Gid: 48 48 48 48 FDSize: 64 Groups: 48 986 NStgid: 792851 NSpid: 792851 NSpgid: 1076 NSsid: 1076 VmPeak: 185944 kB VmSize: 185660 kB VmLck: 0 kB VmPin: 0 kB VmHWM: 38500 kB VmRSS: 38448 kB RssAnon: 14364 kB RssFile: 24084 kB RssShmem: 0 kB VmData: 14124 kB VmStk: 132 kB VmExe: 41916 kB VmLib: 43532 kB VmPTE: 292 kB VmSwap: 0 kB HugetlbPages: 0 kB CoreDumping: 1 THP_enabled: 1 Threads: 1 SigQ: 0/38970 SigPnd: 0000000000000000 ShdPnd: 0000000000000000 SigBlk: 0000000000000000 SigIgn: 0000000000001000 SigCgt: 0000000180000000 CapInh: 0000000000000000 CapPrm: 0000000000000000 CapEff: 0000000000000000 CapBnd: 000001ffffffffff CapAmb: 0000000000000000 NoNewPrivs: 0 Seccomp: 0 Speculation_Store_Bypass: vulnerable Cpus_allowed: ff Cpus_allowed_list: 0-7 Mems_allowed: 00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001 Mems_allowed_list: 0 voluntary_ctxt_switches: 6 nonvoluntary_ctxt_switches: 2
COREDUMP_RLIMIT
0
COREDUMP_ROOT
/
COREDUMP_SIGNAL
11
COREDUMP_SIGNAL_NAME
SIGSEGV
COREDUMP_SLICE
system.slice
COREDUMP_TIMESTAMP
1669879203000000
COREDUMP_UID
48
COREDUMP_UNIT
php-fpm.service
MESSAGE_ID
fc2e22bc6ee647b6b90729ab34a250b1
PRIORITY
2
SYSLOG_IDENTIFIER
systemd-coredump
_BOOT_ID
89de6b3a10f145be8e3c34676bd42c48
_CAP_EFFECTIVE
1fff7fcffff
_CMDLINE
/usr/lib/systemd/systemd-coredump
_COMM
systemd-coredum
_EXE
/usr/lib/systemd/systemd-coredump
_GID
0
_HOSTNAME
xxx.xxx.xxx
_MACHINE_ID
43adbc81541c40b89dacdaed716213d2
_PID
792857
_SOURCE_REALTIME_TIMESTAMP
1669879203932559
_TRANSPORT
journal
_UID
0
__CURSOR
s=15bf4f33c4854660ac499fb40c3d770b;i=1824;b=89de6b3a10f145be8e3c34676bd42c48;m=54feaa3e3c;t=5eebf0cc4ab17;x=98a61f65925b275f
__MONOTONIC_TIMESTAMP
365049822780
__REALTIME_TIMESTAMP
1669879203932951

**Comment by m0urs** [comment]
Same here with Debian Linux.

**Comment by sduehr** [comment]
Also with Nextcloud 25.0.2 and Onlyoffice 7.6.8 on el9:
`kernel: x2t[18864]: segfault at 78 ip 00007fae92312f6b sp 00007ffe95969230 error 4 in libgraphics.so[7fae91f2e000+68e000]
`
occurs when listing files.
Workaround: Disable the "Use ONLYOFFICE to generate a document preview" setting.

**Comment by Githopp192** [comment]
i did - but syslog is still full of:

kernel: x2t[2335483]: segfault at 78 ip 00007fa1d5a24f6b sp 00007ffc57cf9960 error 4 in libgraphics.so[7fa1d5640000+68e000]

Workaround does not fix the issue for me

**Comment by Githopp192** [comment]
now on ==>

Nextcloud: 25.0.5
documentserver_community: 0.1.13
onlyoffice: 7.8.0

No change - sames issue - not fixed yet

**Comment by Githopp192** [comment]
still on 

Nextcloud: 25.0.5
documentserver_community: 0.1.13
onlyoffice: 7.8.0

Now: Disable the "Use ONLYOFFICE to generate a document preview" setting - fixed it for me for NC: 25.0.5

Thanks for this good advice/workaround
