### ISSUE TITLE
[Bug]: OnlyOffice App cannot connect to local OnlyOffice server

### ISSUE THREAD

**Issue by RobertBrown3** [nextcloud/documentserver_community#291]
I am running the latest Nextcloud in a Docker container with the OnlyOffice extension. An OpenOffice server is running in a separate container.

The OnlyOffice server is intended only to be used through Nextcloud, so there is no need for SSL setup. The OnlyOffice server is accessible on my local network through HTTP (accessing using the URL 192.168.1.99:8080 returns the OnlyOffice welcome page). 

The firewall is set so that there is no access to the server from the Internet. Only Nextcloud has access to the OnlyOffice server, and it is protected using the standard reverse proxy (through the Nginx proxy manager).

The first problem encountered is that the OnlyOffice Server page only accepts URLs for the OnlyOffice DOCS address that use HTTPS protocol. This is a problem because attempts to save the configuration using an HTTPS protocol causes the following error message:

`Error when trying to connect (cURL error 35: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (see  https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://192.168.1.99:8080) Skip to main content Skip to navigation of app Factor Three File Sharer's homepage ONLYOFFICE `

It is possible to successfully save the configuration by clickimg on the "Advanced server settings" button and entering an HTTP protocol URL (http://192.168.1.99:8080) as the address for internal requests from Nextcloud. This enables the configuration to be saved, but any attempt to open any OnlyOffice documents yields the following failure:

`ONLYOFFICE cannot be reached. Please contact admin`

Apparently, regardless of the setting for the internal request address, there is no way to make Nextcloud use it. It apparently only uses it during the saving of the configuration! There is no setting for allowing Nextcloud to use the internal access address for accessing actual documents (making the advanced settings somewhat irrelevant when actually using OnlyOffice!).

This bug has 2 aspects:

1. While it is correct to require the use of SSL to access OnlyOffice servers that are accessible over the Internet, it is somewhat redundant to force its use for servers that are only accessed locally.

2. There needs to be a way to access a local OnlyOffice service locally. At this point the Advanced settings provided in the OnlyOffice admin page is irrelevant. What is the point of setting local URL access if Nextcloud's OnlyOffice app doesn't use it???

At a minimum, there needs to be a way to make Nextcloud use the local access URL when opening an OnlyOffice document.

**Comment by nyulawbrian** [comment]
I'm having this same problem on a fresh install of Nextcloud All-in-one (AIO).  I've installed both ONLYOFFICE apps from the Nextcloud app store and left all settings to default.  

My Nextcloud AIO installation is pretty vanilla, the only deviation from default settings is that I enabled Caddy (reverse proxy).  

It's unclear to me (I could not find anything in documentation) whether the document server is supposed to be running as a separate Docker container managed by AIO, or if it's running inside the existing Nextcloud container.  Either way, I cannot access ONLYOFFICE from within Nextcloud, nor by going directly to the path automatically populated in the ONLYOFFICE app settings (https://nextcloud.mydomain/apps/documentserver_community).
