### ISSUE TITLE
I have a problem with documentservercommunity when exporting pdf, no text

### ISSUE THREAD

**Issue by Czuczzu** [nextcloud/documentserver_community#293]
I have a problem with documentservercommunity when exporting pdf, no text is applied, Please help and provide detailed instructions

Community Document Server 0.1.13

ONLYOFFICE 7.6.8

#251 

the instructions in 251 don't help or I'm doing something wrong

**Comment by Czuczzu** [comment]
I fixed it by installing onlyoffice per docker manual Choose to install on port 8080 https://helpcenter.onlyoffice.com/installation/docs-community-install-script.aspx

**Comment by LordDoggo** [comment]
Thanks, but it prints "The following TCP Ports must be available: 443" when i try to run. But my nextcloud is running on port 443.
