### ISSUE TITLE
nextcloud 28 support

### ISSUE THREAD

**Issue by cocanut** [nextcloud/documentserver_community#298]
The upgrade to Nextcloud 26 is currently not supported (i.e. stated by the web-updater) by this app (maximum Nexcloud version 25). Is there a plan/idea to support Nextcloud 26?

**Comment by ml31415** [comment]
The same sad story as with every version update :-(

**Comment by cocanut** [comment]
I changed line 39 in "apps/documentserver_community/appinfo/info.xml" to
```
<nextcloud min-version="21" max-version="26"/>
``` 
Then i updated nextcloud via the command line updater to version 26.0.1. So far everything seems to work.

**Comment by hardingt** [comment]
Would like to add my voice here: For all it's bugs, it serves a useful purpose for those households and businesses wanting to get away from the big name providers (and all the baggage they bring with them). @icewind1991 please reconsider adding another maintainer to improve the update situation.

**Comment by aaronhuggins** [comment]
@ml31415 I would still be interested in helping with maintaining this. My maintenance cycle would be reactive, though, as it would be some time after I needed a newer OnlyOffice or Nextcloud version. *Which just happened again and I'll be opening a PR some time in the next week.* 🤦 I'm seeing all y'alls comments now! 🤷 

@icewind1991 Would you be willing to make me a collaborator on this? What all would you need from me to have the confidence for that?

**Comment by hardingt** [comment]
It's now August, I see that https://github.com/ONLYOFFICE/onlyoffice-nextcloud still get's updates, now on 7.9 and 8.2, I'm confused how [LinneyS](https://github.com/LinneyS) seems to keep that repo up to date but doesn't push this one as well. I'm probably missing something basic about the relationship of the document server and Only Office. Another AT to @icewind1991 , @aaronhuggins appears to be willing to take up the mantel!

**Comment by ChristophWurst** [comment]
I'll ask internally

**Comment by chadek** [comment]
I just "accidentally" updated to nextcloud 27 few weeks ago so I cannot use this plugin anymore for now :'( Does someone (@aaronhuggins ?) work on upgrading on 26 and or 27? If so, even if it is still draft, can one open a PR to help contribute to this and be able to manual install while I'd be accepted by the maintainer? I'm php newbee but I'd be happy to give a hand to this as it is useful for many.

**Comment by ml31415** [comment]
@ChristophWurst any results?

**Comment by oujonny** [comment]
I would love to see this project alive again! I'm also in to submit PRs in Future!

**Comment by chadek** [comment]
I opened [this PR](https://github.com/nextcloud/documentserver_community/pull/303) which at least allow to use onlyoffice on nextcloud 27 :) Any help to bump up the document_server version to latest is welcome.

**Comment by ml31415** [comment]
So nextcloud 28 is about to come out and we still talk about proper 26 support ...
@ChristophWurst @AndyScherzinger @blizzz is there really nobody in all nextcloud, who could delegate this package to new caring and responsible hands?

**Comment by AndyScherzinger** [comment]
Sorry for the wait 🙏
This seems to have been gotten lost to do since we discussed it and decided to hand it over.

So for starters I added @chadek and @aaronhuggins to the repo. Just let me know if that is sufficient or if you need other things to be done.

Again sorry for the wait, this definitely slipped through on my end 😞

**Comment by aaronhuggins** [comment]
Hi @AndyScherzinger and @chadek! Thanks for the add and the release! I was trying to get updated OnlyOffice working a while ago and had some notes on it. I'll take a crack at updated binaries in the near future, but no promises as my holiday season is very busy.

**Comment by ml31415** [comment]
@chadek Take your time with updating the binaries. As long as the status quo works for recent nextcloud version, which as far as I can tell works, I guess the most important thing is to get the recent versions marked as supported, so that everyone out there can happily update nextcloud itself without warnings due to dependencies.

**Comment by chadek** [comment]
I have uploaded the asset but it still need to be publish on the app store. I'm new to all of this and it seams that I cannot publish the asset on app store as I'm actual owner of the app. Maybe I could setup a github action to automate that and @icewind1991 could provide a valid token to automatically publish on new release ?

**Comment by AndyScherzinger** [comment]
I expect we need to transfer the app to you (app store account) and need to create a new set of keys for you.

**Comment by chadek** [comment]
That is what I just found out reading the doc, the assets does not come with the expected signature

**Comment by chadek** [comment]
So @AndyScherzinger how shall I proceed? I created an account in the app store using the github sso so it shall be the same username.

**Comment by kn0wmad** [comment]
Is this still in motion?  Would love to see this available for current versions of Nextcloud

**Comment by AndyScherzinger** [comment]
@chadek due to the late stability comment this issue came up on my radar again.
Is there still something open regarding the app store? Didn't check since I am currently on the phone, so  commenting here was just a lot easier thank trying to check the app store.

**Comment by chadek** [comment]
> So @AndyScherzinger how shall I proceed? I created an account in the app store using the github sso so it shall be the same username.

@AndyScherzinger I am still waiting for an answer to this... It is quite far now, but as I remember, I created an account on the app store and I'm now waiting for you/someone to transfer the app to me if it is how it works : I'm new with the use of such store and have no clue of the workflow.

**Comment by AndyScherzinger** [comment]
Thanks for the info, I#ll see what needs to be done 👍

**Comment by AndyScherzinger** [comment]
I got a better picture. For you to be able we'll need to transfer the signing key to you, so you are able to release new versions or need to create a new one.

First step will the best be to remove icewind as a maintainer than add you where you will need to proof ownership using the key for a signing, than you will have taken over the app appstore wise.

We meet next week in person in the office and can than clarify things.

Could you drop me an email until then, so I have your contact for the key?

Andy dot Scherzinger at Nextcloud dot com

**Comment by AndyScherzinger** [comment]
Along very sorry for the delay. This totally slipped through on my end 😔

**Comment by chadek** [comment]
Preparing ground https://github.com/nextcloud/documentserver_community/pull/314 to quickly update in the future

**Comment by chadek** [comment]
Finally pushed to the app store! Waiting some feedbak here before closing

**Comment by chadek** [comment]
@AndyScherzinger I did pushed a github action workflow to easily deploy. I just don't have access to project settings to set up secrets. If we want to go this way, I'll open a new issue to discuss that

**Comment by ChristophWurst** [comment]
> I just don't have access to project settings to set up secrets.

Please be careful with that and see https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/release_automation.html.

**Comment by chadek** [comment]
@ChristophWurst I already used this. I actually pushed latest version to app store using the [workflow in master](https://github.com/nextcloud/documentserver_community/blob/master/.github/workflows/release.yml) from my fork to be able to push to app store. Now my point is whether I keep on publishing with my fork (which is not a good idea as the asset pushed on the app store would point to my repo and not the project repo) or somebody setup here secrets to deploy from this repo, setting up carefully reviews and being really careful when manipulating secrets.

**Comment by ChristophWurst** [comment]
If you bring the automation over to this repo, environment secrets are the only way to go. Repository secrets are not secure.

**Comment by chadek** [comment]
Yes totally right, sorry for that, I did not pay attention to the scope of both. Here is a [pr](https://github.com/nextcloud/documentserver_community/pull/317)  to fix that if you mind take a look.

**Comment by chadek** [comment]
@ChristophWurst if it is all good now, maybe someone can setup environment secrets.
