### ISSUE TITLE
Error "Community document server is not supported for this instance, please setup and configure an external document server"

### ISSUE THREAD

**Issue by Nevarro** [nextcloud/documentserver_community#30]
I'm still (referring to the similar error of the sticky issue) getting the "Community document server is not supported for this instance, please setup and configure an external document server" error on my Synology NAS. It's a x86-64 CPU, I installed the latest version of the documentserver and I changed the permissions as described above. The error is shown, if I try to open a document, however there's nothing coming up in the Nextcloud logs.

I get the same error when I deactivate the community server. Could there be a problem concerning the linking of both Onlyoffice and the document server?

**Comment by ostasevych** [comment]
Which glibc version are you using?

> I'm still (referring to the similar error of the sticky issue) getting the "Community document server is not supported for this instance, please setup and configure an external document server" error on my Synology NAS. It's a x86-64 CPU, I installed the latest version of the documentserver and I changed the permissions as described above. The error is shown, if I try to open a document, however there's nothing coming up in the Nextcloud logs.
> 
> I get the same error when I deactivate the community server. Could there be a problem concerning the linking of both Onlyoffice and the document server?

Which glibc version are you using?

**Comment by Phoara** [comment]
> > I'm still (referring to the similar error of the sticky issue) getting the "Community document server is not supported for this instance, please setup and configure an external document server" error on my Synology NAS. It's a x86-64 CPU, I installed the latest version of the documentserver and I changed the permissions as described above. The error is shown, if I try to open a document, however there's nothing coming up in the Nextcloud logs.
> > I get the same error when I deactivate the community server. Could there be a problem concerning the linking of both Onlyoffice and the document server?
> 
> Which glibc version are you using?

I have no idea, because afaik there wouldn‘t be a way to update glibc on a Synology NAS anyway.

**Comment by thomaskunze3** [comment]
I am experiencing the same issue on my Synology DS1019+ DSM 6.2.2-24922 Update 4.

```
ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.4) 2.19
```

```
lsof -p $$ | grep libc | awk ' { print $NF" --version"; } ' | sh
GNU C Library (crosstool-NG 1.20.0) stable release version 2.20-2014.11, by Roland McGrath et al.
```

Being a Linux noob, I have no idea which version is valid though :-(

**Comment by icewind1991** [comment]
can you post the output of 

    ldd /path/to/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/x2t

**Comment by Phoara** [comment]
> can you post the output of
> 
> ```
> ldd /path/to/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/x2t
> ```

That's the output for me:

> 	linux-vdso.so.1 (0x00007ffce5f41000)
	libkernel.so => not found
	libgraphics.so => not found
	libPdfWriter.so => not found
	libdoctrenderer.so => not found
	libHtmlRenderer.so => not found
	libPdfReader.so => not found
	libDjVuFile.so => not found
	libXpsFile.so => not found
	libHtmlFile.so => not found
	libUnicodeConverter.so => not found
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f53a3fd0000)
	libm.so.6 => /lib/libm.so.6 (0x00007f53a3cca000)
	libc.so.6 => /lib/libc.so.6 (0x00007f53a3925000)
	/lib64/ld-linux-x86-64.so.2 (0x00005625f9d7a000)

**Comment by icewind1991** [comment]
Thanks,

can you change directory to `.../FileConverter/bin/x2t` and run `./x2t`

**Comment by Phoara** [comment]
Thanks for your help. I installed 1.0.3 now and instead of the error message above I now get

"ONLYOFFICE ist zurzeit nicht erreichbar. Bitte wenden Sie sich an Ihren Administrator" (Onlyoffice is not available right now. Please contact the Admin" (roughly translated)

My Synology doesn't accept the run command but when I'm in `.../FileConverter/bin` and type in ./x2t, I get

> ./x2t: /lib/libstdc++.so.6: no version information available (required by ./libgraphics.so)
./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58)
./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58)


-------------------------------------------------------------------------------
		OOX/binary file converter. Version: 5.4.2.46
-------------------------------------------------------------------------------

USAGE: x2t "path_to_params_xml"
or
USAGE: x2t "path_to_file_1" "path_to_file_2" ["path_to_font_selection"]
WHERE:
	"path_to_file_1" is a path to file to be converted
	"path_to_file_2" is a path to the corresponding output file
	"path_to_font_selection" is a path to 'font_selection.bin' location

NOTE: conversion direction will be calculated from file extensions

**Comment by Phoara** [comment]
Update to 0.1.4 didn't change anything on my Synology NAS.

[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: ./x2t: /lib/libstdc++.so.6: no version information available (required by ./libgraphics.so)
./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58)
./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58)
Empty sFileFrom or sFileTo
 at <<closure>>

 0. /volume1/web/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php line 64
    OCA\DocumentServer\Document\ConverterBinary->run("")
 1. /volume1/web/nextcloud/apps/documentserver_community/lib/SetupCheck.php line 34
    OCA\DocumentServer\Document\ConverterBinary->test()
 2. /volume1/web/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php line 89
    OCA\DocumentServer\SetupCheck->check()
 3. /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\DocumentServer\Controller\StaticController->webApps("apps/api/documents/api.js")
 4. /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\DocumentServ ... {}, "webApps")
 5. /volume1/web/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "webApps")
 6. /volume1/web/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\DocumentSe ... r", "webApps", OC\AppFramework\ ... {}, {path: "apps/api ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({path: "apps/api ... "})
 8. /volume1/web/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {path: "apps/api ... "})
 9. /volume1/web/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/documents ... s")
10. /volume1/web/nextcloud/index.php line 38
    OC::handleRequest()

GET /nextcloud/index.php/apps/documentserver_community/web-apps/apps/api/documents/api.js

**Comment by jwsp1** [comment]
getting the same error, in combination with "32 bit setups are not supported".
Being on Nextcloud v18.0.4.2 (nextcloudpi image, v1.25.0) on a RaspberryPi 4B 4GB RAM.
