### ISSUE TITLE
0.1.14 does not seem to work with NC 27.1.3 (whilst 0.1.13 did)

### ISSUE THREAD

**Issue by Sarmingsteiner** [nextcloud/documentserver_community#304]
Unfortunately, Onlyoffice does not work with NC 27.1.3 and documentserver_community version 0.1.14.

With 0.1.13 installed, it was possible to open and edit files with NC 27.1.3 (whilst a bit unstable).

When trying to open a file with 0.1.14 installed, NC shows "Page cannot be found - Page cannot be found or you do not have the right to access it"

Many thanks in advance for your thoughts!

**Comment by Sarmingsteiner** [comment]
OK, it seems it has to be built be ourselves, which seems almost impossible on a shared hosting environment :-(

**Comment by EdRoxter** [comment]
> OK, it seems it has to be built by ourselves, which seems almost impossible on a shared hosting environment :-(

You don't have to build it yourself. Just download the full version including the server-side onlyoffice suite from here:

https://github.com/nextcloud/documentserver_community/releases/download/v0.1.14/documentserver_community.tar.gz

Then put your Nextcloud instance into maintenance mode, delete old "documentserver_community" directory in your "apps" folder, and extract the one from the tgz file. Exit maintenance mode, et voilà, 0.1.14 is fully installed and works.

I'm just wondering why it's not updated in the NC app store yet, but that's another question.

**Comment by chadek** [comment]
@EdRoxter is right, closing
