### ISSUE TITLE
Support for Nextcloud 28

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/documentserver_community#306]
This app stopped working on Nextcloud 28.

This error happens when trying to open a document:
![grafik](https://github.com/nextcloud/documentserver_community/assets/23138465/ff8d4a7b-ef35-474f-b871-48cf3543eb03)
![grafik](https://github.com/nextcloud/documentserver_community/assets/23138465/04a6677e-cfe2-4caf-9f3f-c09867cfac66)

**Comment by AurelienLemaire** [comment]
hi there, fixed it.

need to initialize header to [] prior to call getHeaders in creators of XHRResponse and FileResponse

	public function __construct(
		string $type,
		array $data = null,
		int $statusCode = Http::STATUS_OK,
		$headers = []
	) {
		$this->type = $type;
		$this->data = $data;
		$this->setStatus($statusCode);
	//HERE	
$this->setHeaders([]);

		$this->setHeaders(array_merge($this->getHeaders(), $headers));

		$this->addHeader('Content-Type', 'application/javascript; charset=UTF-8');
	}

**Comment by v-bulynkin** [comment]
@AurelienLemaire, I am sorry but I can't understand how to fix it.
I should edit `/var/www/html/lib/public/AppFramework/Http/Response.php`, right?

I have the following section there:
```php
	public function __construct(int $status = Http::STATUS_OK, array $headers = []) {
		$this->setStatus($status);
		$this->setHeaders($headers);
	}
```

**Comment by mani2jeff** [comment]
I hope this will be rolled out soon we can use it?

**Comment by sokai** [comment]
Not working for me:

```diff
--- a/apps/documentserver_community/lib/FileResponse.dist.php
+++ b/apps/documentserver_community/lib/FileResponse.php
@@ -37,6 +37,7 @@ class FileResponse extends Response implements ICallbackResponse {
                $this->data = $data;
                $this->name = $name;
                $this->setStatus($statusCode);
+        $this->setHeaders([]);
                $this->setHeaders(array_merge($this->getHeaders(), $headers));
                $this->addHeader('Content-Length', $length);
                $this->addHeader('Content-Type', $mimeType);
```

```diff
--- a/apps/documentserver_community/lib/XHRResponse.dist.php
+++ b/apps/documentserver_community/lib/XHRResponse.php
@@ -41,6 +41,7 @@ class XHRResponse extends Response implements ICallbackResponse {
                $this->type = $type;
                $this->data = $data;
                $this->setStatus($statusCode);
+        $this->setHeaders([]);
                $this->setHeaders(array_merge($this->getHeaders(), $headers));
 
                $this->addHeader('Content-Type', 'application/javascript; charset=UTF-8');
```

But it changed the error, because now all my security headers are gone and the browser will not open the inline frame/page …
KR

**Comment by sokai** [comment]
It seems the fix is in #308 (at least it works for me and the solution was nearly here …)

**Comment by WhoAmI0501** [comment]
Please see (and maybe test) #311

**Comment by chadek** [comment]
#298 duplicate
