### ISSUE TITLE
Nextcloud 28.0.1 is out 

### ISSUE THREAD

**Issue by witzker** [nextcloud/documentserver_community#310]
Hi, 
![image](https://github.com/nextcloud/documentserver_community/assets/4120266/57648c16-4acd-498f-b4c7-359006af40b1)

May I ask if it is planned to make the server you offer usable in the new Version 28.x .
If yes, when can we expect the compatible version?

**Comment by ajoana** [comment]
The documentserver 1.13 stopped working with update to 28.0.1 (I updated to solve reconnection issues) - I updated max-version to 28 in info.xml as it worked with the last versions.
An update to 1.14 (with support for 27) is not offered. When will an updated version be available?

**Comment by WhoAmI0501** [comment]
Since #308 is closed and is also just a little bit hacky solution, i opened #311

**Comment by chadek** [comment]
I'm retaking maintenance of this app, I still cannot push to the app store but I'm into it (depend on Nextcloud team guys), hopefully soon I'll merge #311 after review

**Comment by chadek** [comment]
Preparing ground [here](https://github.com/nextcloud/documentserver_community/pull/314) to quickly update in the future
