### ISSUE TITLE
Community Document Server 0.1.16

### ISSUE THREAD

**Issue by a1ex-ak** [nextcloud/documentserver_community#322]
Good afternoon! 

Why is there already version 0.1.16 in the nextcloud store, but only [0.1.15](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.15.1) on Github. 

What changes were made in version 0.1.16?

![Снимок экрана от 2024-04-04 12-18-14](https://github.com/nextcloud/documentserver_community/assets/121604147/a5af65fb-c61d-4f41-8597-3868af2e76a6)

![Снимок экрана от 2024-04-04 12-19-22](https://github.com/nextcloud/documentserver_community/assets/121604147/168f6883-0f69-448d-9fa6-2e961a033ff3)

**Comment by kintaro1981** [comment]
take a look here:
https://github.com/nextcloud/documentserver_community/issues/318#issuecomment-2029513447

**Comment by chadek** [comment]
I opened this [PR](https://github.com/nextcloud/documentserver_community/pull/320) to fix data loss issue and was waiting for users feedbacks  before merging a reliable version to main repository

**Comment by chadek** [comment]
PR merged and released
