### ISSUE TITLE
v.0.1.16 does not work in NC 28.0.4

### ISSUE THREAD

**Issue by kiwiradler** [nextcloud/documentserver_community#323]
I have just updated the server in two installations (both 28.0.4) and OnlyOffice stopped working. If I create a new document, OO won't open but the file is downloaded to my desktop. If I try to open an existing file, same. Actually the update broke functionality. What a pity...

**Comment by kiwiradler** [comment]
Okay, in a third installation I found out that the problem is related to the update of the "OO App" from v.9.0.0. to 9.1.0. Document Server 0.1.16 works together with v.9.0.0 but not 9.1.0. Maybe that helps finding the problem...

**Comment by micker** [comment]
i have same problem documentserver was desactived after update

**Comment by chadek** [comment]
I'll take a look

**Comment by chadek** [comment]
Refresh your cache

**Comment by chadek** [comment]
Updated read me with hint when updating app
