### ISSUE TITLE
I need update for nextcloud 29

### ISSUE THREAD

**Issue by argos2024** [nextcloud/documentserver_community#325]
In recent days, we have proceeded to update NextCloud to version 29. Currently there is no version for this plugin. Please I need an update of it adapting it to version 29 of nextcloud

**Comment by NeverLoseHope777** [comment]
I have found a workaround that works.

I uninstalled the two apps "ONLYOFFICE" and "Community Document Server" in Nextcloud and deleted the folder "documentserver_community" from the "apps" folder on the server.

I then downloaded release v0.1.17 of the "Community Document Server" from GitHub and copied it to the "apps" folder on the server.

In Nextcloud, I activated the "Community Document Server" under "Apps" and reinstalled "ONLYOFFICE".

In my case, I had to enter the address "https://<nextcloud_server>/index.php/apps/documentserver_community/" (including the index.php) in the settings under "ONLYOFFICE" and then it worked again.

Good luck and best regards

**Comment by smeisner** [comment]
Any updates on this? I tried @NeverLoseHope777 solution, but I still receive an error:

Error when trying to connect (Client error: `GET https://<nextcloud server>/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.KLGYsd0wQFVcoAWfrUOxLPGp4HK5Tvxm4Yvzv84DEw4` resulted in a `403 Forbidden` response:
{"message":"Access denied"}
) (version 7.2.2)

NextCloud VM version is 29.0.2 (stable)

The ONLYOFFICE Docs address is set as indicated by NeverLoseHope777 ... I am starting to lose hope though  :)

**Comment by chadek** [comment]
Sorry I didn't pay attention to issues recently, I just release v0.1.18 that should work. Please confirm then I'll close this issue
