### ISSUE TITLE
Nextcloud v28.0.3.2 / OnlyOffice SSL Error

### ISSUE THREAD

**Issue by 1artist** [nextcloud/documentserver_community#327]
My fileserver runs the latest Ubuntu Server 22.04.4 LTS OS. And I installed Nextcloud version 28.0.3.2 using the Nextcloud auto install script located in the link below. Since then I have installed two updates so now my Nextcloud version number is 28.0.5.5 . From what I understand the Nextcloud auto install script generated Self Signed Certificates for Nextcloud to operate under HTTPS.

[](https://github.com/nicrame/Linux-Scripts/blob/master/nextcloud-ins.sh)

In my Nextcloud +APPS area I installed OnlyOffice by installing the two modules and after clicking on the SAVE button in the OnlyOffice configuration area I got the error shown below:

`Error when trying to connect (cURL error 60: SSL: no alternative certificate subject name matches target host name '123.456.7.899' (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://123.456.7.899/apps/documentserver_community/healthcheck)`

I executed the SUDO command below to import the Nextcloud SSL cert:

`root@myserver:~# sudo -u www-data php occ security:certificates:import /etc/ssl/certs/nextcloud.crt`

And below is the error I got:

`Could not open input file: occ`

I would appreciate any advice on how to fix this SSL error because it is preventing my OnlyOffice from working within my Nextcloud environment.  Thank you for your time.

**Comment by chadek** [comment]
ssl cert should match the common name you have defined, here you are pointing directly to an IP, therefore it can not work
