### ISSUE TITLE
ONLYOFFICE is currently not available. Please contact your administrator

### ISSUE THREAD

**Issue by georgy62** [nextcloud/documentserver_community#328]
Hello everyone,

I'm running nexctcloud 29 and ONLYOFFICE 9.2.0 together with the documentserver_community on a rented server. Unfortunately, when I open a document in *docx format, I get the following error message: "ONLYOFFICE is currently not available. Please contact your administrator".

SSL and HSTS are activated on the server. Under the ONLYOFFICE settings, the path to the document server has been set and confirmed with https://[domain]/index.php/apps/documentserver_community/.

The file [domain]/config/config.php contains, among others, the following lines:

'overwrite.cli.url' => 'https://[domain]',
'overwriteprotocol' => 'https',
'allow_local_remote_servers' => true,

Is there a compatible version of ONLYOFFICE or is there something I can do to get it working?

Thank you for your response
georgy62

**Comment by NeverLoseHope777** [comment]
Maybe you could try this:

https://github.com/nextcloud/documentserver_community/issues/325

**Comment by georgy62** [comment]
I tried it the same way several times, but no, unfortunately it doesn't work in my case.

**Comment by georgy62** [comment]
In the file /data/nextcloud.log I found the following line, which is incomprehensible to me:

```
{"reqId":"ZlEGot7BUupZm26qNkHZ9wAAAIk","level":3,"time":"2024-05-24T21:29:06+00:00","remoteAddr":"85.13.141.100","user":"--","app":"index","method":"POST","url":"/index.php/apps/documentserver_community/ConvertService.ashx","message":"./x2t: error while loading shared libraries: libgraphics.so: cannot open shared object file: No such file or directory\n","userAgent":"Nextcloud Server Crawler","version":"29.0.0.19","exception":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"./x2t: error while loading shared libraries: libgraphics.so: cannot open shared object file: No such file or directory\n","Code":0,"Trace":[{"file":"/www/htdocs/[server]/apps/documentserver_community/lib/DocumentConverter.php","line":125,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":["/www/htdocs/[server]/data/tmp/oc_tmp_A54Xlk-.xml",null]},{"file":"/www/htdocs/[server]/apps/documentserver_community/lib/DocumentConverter.php","line":113,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[["OCA\\DocumentServer\\Document\\ConvertCommand"],null]},{"file":"/www/htdocs/[server]/apps/documentserver_community/lib/DocumentConverter.php","line":49,"function":"convertFiles","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":["/www/htdocs/[server]/data/tmp/oc_tmp_E8qZ66-.docx","/www/htdocs/[server]/data/appdata_ocjzs7wdvc3d/documentserver_community/doc_1599327567/Editor.bin",8192,null]},{"file":"/www/htdocs/[server]/apps/documentserver_community/lib/Document/DocumentStore.php","line":98,"function":"getEditorBinary","class":"OCA\\DocumentServer\\DocumentConverter","type":"->","args":[null,"docx","*** sensitive parameters replaced ***",null]},{"file":"/www/htdocs/[server]/apps/documentserver_community/lib/LocalAppData.php","line":102,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/htdocs/[server]/apps/documentserver_community/lib/Document/DocumentStore.php","line":99,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->","args":[["OC\\Files\\SimpleFS\\SimpleFolder"],["Closure"]]},{"file":"/www/htdocs/[server]/apps/documentserver_community/lib/Controller/ConvertController.php","line":59,"function":"getDocumentForEditor","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[1599327567,["OC\\Files\\Node\\File"],"docx"]},{"file":"/www/htdocs/[server]/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"convert","class":"OCA\\DocumentServer\\Controller\\ConvertController","type":"->","args":[false,"https://cloud.fotogerhard.de/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NjYyMzIsInVzZXJJZCI6ImNoZWYifQ.3yeS9tA7VCTsC7d4CtqK8t3VzS-0Lb4A87flOWo3bis","jpeg","docx","1599327567.docx","1599327567"]},{"file":"/www/htdocs/[server]/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\DocumentServer\\Controller\\ConvertController"],"convert"]},{"file":"/www/htdocs/[server]/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\DocumentServer\\Controller\\ConvertController"],"convert"]},{"file":"/www/htdocs/[server]/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\ConvertController","convert",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["documentserver_community.convert.convert"]]},{"file":"/www/htdocs/[server]/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/ConvertService.ashx"]},{"file":"/www/htdocs/[server]/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/[server]/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":67,"message":"./x2t: error while loading shared libraries: libgraphics.so: cannot open shared object file: No such file or directory\n","exception":{},"CustomMessage":"./x2t: error while loading shared libraries: libgraphics.so: cannot open shared object file: No such file or directory\n"}}```

**Comment by georgy62** [comment]
I have set up three instances of Nextcloud Hub 8 (29.0.0) on different servers. In all three I get the same error message after calling up newfile.docx, for example, but different error messages in nextcloud.log. Unfortunately, I am unable to evaluate these log files. I would therefore be grateful if someone could evaluate these files. I have attached the link to two of the log files.
https://cloud.fotogerhard.de/index.php/s/goCMG43jGNxxC5a 
Many thanks

**Comment by blockiyt** [comment]
+1 here

**Comment by blockiyt** [comment]
When opening OnlyOffice I also get the message "ONLYOFFICE is currently not available. Please contact your administrator".
When looking into the inspector, I get an 500 error with a request to this url: https://<nc-url>/apps/documentserver_community/web-apps/apps/api/documents/api.js

**Comment by georgy62** [comment]
> The healthcheck works: https:///apps/documentserver_community/healthcheck

same to me ...

**Comment by blockiyt** [comment]
I fixed the problem by changing a setting in my firewall that blocked the access from one vm to another.

**Comment by georgy62** [comment]
> I fixed the problem by changing a setting in my firewall that blocked the access from one vm to another.

OK, but the "healthchek = true" says that the connection to the document server was successful. However, the error message says that the installed Onlyoffice is not accessible. Is there any connection between nextcloud and Onlyoffice that a firewall can block?

**Comment by blockiyt** [comment]
Yes there is, if there is complicated VLAN routing for example in my case.
My router blocked the access from the Nextcloud to the document server.

**Comment by georgy62** [comment]
> Yes there is, if there is complicated VLAN routing for example in my case.
> My router blocked the access from the Nextcloud to the document server.

OK, in my case both are running on one machine, within the local network, without SSL and without the connection going through a router.
Again: nextcloud can access the document server, which is set and tested in the onlyoffice settings within nextcloud. Then I wonder what the error message "ONLYOFFICE is currently not available. Please contact your administrator" means. Onlyoffice is 
1. installed, 
2. activated, 
3. can access the document server, but 
4. is not accessible itself?

**Comment by hopfenhuhn** [comment]
In my case the following issue helped: #195

I replaced
`$process = proc_open($cmd, $descriptorSpec, $pipes, self::BINARY_DIRECTORY, []); `
by
`$process = proc_open($cmd, $descriptorSpec, $pipes, self::BINARY_DIRECTORY, ["LD_LIBRARY_PATH" => "."]); `
in /apps/documentserver_community/lib/Document/ConverterBinary.php Line 54.

But still using NC 27.

**Comment by georgy62** [comment]
wow, thank you very much. It worked for me too. 
I'm running 
Nextcloud Hub 7 (28.0.6) 
and 
ONLYOFFICE 9.2.2.
