### ISSUE TITLE
Error when installing from store

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/documentserver_community#33]
Hello.

Every time I try to install the Community Document Server from the App Store in Nextcloud 18.0.0, I get this error:
> cURL error 28: Operation timed out after 30000 milliseconds with 57167420 out of 305964280 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I already have the app **onlyoffice** installed since it is need (I did read).
Nextcloud was installed recently on my Webspace at STRATO.

Now my question:
Is it possible to install this app on a simple webspace? If not, is there a way to install it anyway? Or how can I pass this error?

Btw, in Settings this is the full error log I get;
```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30000 milliseconds with 57167420 out of 305964280 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 149:

    GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\H ... l}, { errno: 28, ... "})

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 102:

    GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php - line 43:

    GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 28:

    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensiti ... *", "*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 51:

    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php - line 37:

    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 30:

    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 70:

    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 107:

    GuzzleHttp\RedirectMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 72:

    GuzzleHttp\RedirectMiddleware->checkRedirect(GuzzleHttp\Psr7\Request {}, "*** sensiti ... *", "*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/promises/src/FulfilledPromise.php - line 39:

    GuzzleHttp\RedirectMiddleware->GuzzleHttp\{closure}("*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php - line 47:

    GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}("*** sensiti ... *")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 246:

    GuzzleHttp\Promise\TaskQueue->run(true)

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 223:

    GuzzleHttp\Promise\Promise->invokeWaitFn()

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 267:

    GuzzleHttp\Promise\Promise->waitIfPending()

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 225:

    GuzzleHttp\Promise\Promise->invokeWaitList()

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 62:

    GuzzleHttp\Promise\Promise->waitIfPending()

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131:

    GuzzleHttp\Promise\Promise->wait()

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/private/Http/Client/Client.php - line 149:

    GuzzleHttp\Client->request("get", "https://git ... z", { proxy: nul ... e})

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/private/Installer.php - line 274:

    OC\Http\Client\Client->get("https://git ... z", { save_to: " ... "})

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/apps/settings/lib/Controller/AppSettingsController.php - line 440:

    OC\Installer->downloadApp("documentserver_community")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Settings\Controller\AppSettingsController->enableApps([ "documentserver_community"], [])

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/private/AppFramework/App.php - line 125:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { _route: "s ... "})

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/settings/apps/enable")

    /mnt/web418/a2/84/510199884/htdocs/www/pilzinsel64.com/pilzcloud/index.php - line 38:

    OC::handleRequest()
```

**Comment by EV21** [comment]
> Is it possible to install this app on a simple webspace? If not, is there a way to install it anyway? Or how can I pass this error?

The app is about 292 MB and the downloading operation will be aborted when it is not finished until the timeout. You can can install the app by manually downloading and extracting the app to the apps directory:  
e.g. `/var/www/nextcloud/apps`

or you may change the timeout in `/var/www/nextcloud/lib/private/Http/Client/Client.php` by increasing the following setting to 600 (10 Minutes), depends on your bandwidth 
> RequestOptions::TIMEOUT => 30,

**Comment by Pilzinsel64** [comment]
Thank you very much. I downloaded the app package and extracted the files using 7zip. I had several errors that 7zip was not able to create some symbol links. However, I uploaded it to the apps folder in my nextcloud directory and activated the app. The document server app did change the service address for document editing in onlyoffice options.

I have uploaded an docx file because there is no option to create a new document. But I can't edit this file in onlyoffice. When I click on it then it will be downloaded.

I also tried occ files:scan --all but also that had no affect.

What can I do now?

![grafik](https://user-images.githubusercontent.com/23138465/73050436-368a7100-3e80-11ea-97d4-b5245cc9a260.png)
![grafik](https://user-images.githubusercontent.com/23138465/73050453-45712380-3e80-11ea-9c4a-047400dccb00.png)
![grafik](https://user-images.githubusercontent.com/23138465/73050463-4efa8b80-3e80-11ea-91a9-bc0518894ff4.png)

**Comment by Pilzinsel64** [comment]
I tried to click on "Save" button on onlyoffice settings page. I get an error:
![grafik](https://user-images.githubusercontent.com/23138465/73067488-220e9e80-3ea9-11ea-8989-59e2f84098e3.png)

**Comment by EV21** [comment]
In a working setup the plus-menu (your second picture) should contain the entries "Dokument, Tabelle, Präsentation", the other menu is not changed by the app.

Did you change the entry "Serviceadresse der Dokumentbearbeitung"?
As I can see in your picture, I don't think **...php**/apps/documentserver_community/ is right.
I'm not sure...
try to change it to `https://YOURDOMAIN.com/pilzcloud3/apps/documentserver_community/`

> I had several errors that 7zip was not able to create some symbol links

If you have ssh (console) access you should try to extract the archive on the machine or try another tool.
Make sure the ownership to the app directory is set right. 
You could also try to delete the app, change the timeout setting like mentioned before and download via the internal app store.

**Comment by Pilzinsel64** [comment]
I have tried to change the timeout but then I get an RAM error but I can't increase the RAM for php.

However, I didn't changed the "Serviceaddresse der Dokumentbearbeitung", it was changed after I activated the community document server app.

I also tried to change the address to `https://YOURDOMAIN.com/pilzcloud3/apps/documentserver_community/` but then I got this error:
![grafik](https://user-images.githubusercontent.com/23138465/73068970-d9f17b00-3eac-11ea-9d9a-54dc76ea5b6b.png)

I did read that my error above (bad healthcheck status) has to do something with SSL certificates. Some people wrote to add an option to nextcloud's config.php but also that didn't work:
```
'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )
```
I also tried to activate the demo servers and it worked! But as soon as I disable them and try to use the community document server app I get the error above.

When I am at home, I will try to extract the package using ssh. I hope am allowed to extract files .

**Comment by Pilzinsel64** [comment]
I connected via ssh and tried to install the app using `git clone`. It worked but when I try to open a document there was an error for a missing package.

Then I tried to install the app by downloading v0.1.3 and extracted it via ssh on the webspace. This also workes but when I try to open a document I still get an error. But this error is different.
The error says `32 bit setups are not supported` but in the README of this github repo I can read:
> The community document server only supports running on x86-64 Linux servers.
That means both, 32 and 64 bit, right?

So, why it doesn't work now? I am a bit confused.
Thank you for your patience.

**Comment by EV21** [comment]
> The community document server only supports running on x86-64 Linux servers.
That means both, 32 and 64 bit, right?

No, this app only runs on 64-bit architectures based on x86 instruction sets.
x86 stands for the instruction set for the CPU.
A 64-bit compiled app can run on a 64-bit architecture.
A 32-bit compiled app can run on a 64-bit architecture, if compatibility-mode is supported
A 64-bit compiled app can NOT run on 32-bit architectures.

**Comment by Pilzinsel64** [comment]
Oh, okay. That's bad. That means, I can't use the community document server.

However, thank you very much for your help! 👍

**Comment by bcutter** [comment]
> 
> 
> > The community document server only supports running on x86-64 Linux servers.
> > That means both, 32 and 64 bit, right?
> 
> No, this app only runs on 64-bit architectures based on x86 instruction sets.
> x86 stands for the instruction set for the CPU.
> A 64-bit compiled app can run on a 64-bit architecture.
> A 32-bit compiled app can run on a 64-bit architecture, if compatibility-mode is supported
> A 64-bit compiled app can NOT run on 32-bit architectures.

So... using a Raspberry Pi (4) isn´t working cause even it´s a 64-bit design it´s running on ARM architecture, not x86, right?

**Comment by EV21** [comment]
> So... using a Raspberry Pi (4) isn´t working cause even it´s a 64-bit design it´s running on ARM architecture, not x86, right?

Right, ARM CPUs are not supported, yet.
ARM CPUs are different, they have a reduced instruction set ([RISC](https://en.wikipedia.org/wiki/Reduced_instruction_set_computer)), so the applications need to be compiled for the ARM-architecture. 

So you need a machine with an Intel or AMD CPU running a Linux with 64-bit support.

**Comment by tigernero79** [comment]
> > Quindi ... l'uso di un Raspberry Pi (4) non funziona, anche se è un design a 64 bit che funziona su architettura ARM, non x86, giusto?
> 
> Bene, le CPU ARM non sono ancora supportate.
> Le CPU ARM sono diverse, hanno un set di istruzioni ridotto ( [RISC](https://en.wikipedia.org/wiki/Reduced_instruction_set_computer) ), quindi le applicazioni devono essere compilate per l'architettura ARM.
> 
> Quindi hai bisogno di una macchina con una CPU Intel o AMD che esegua un Linux con supporto a 64 bit.

is arm / raspbian compiled?  if i install ubuntu core with nextcloud snap package Will onlyoffice be usable?

**Comment by EV21** [comment]
> is arm / raspbian compiled?

No.

> if i install ubuntu core with nextcloud snap package Will onlyoffice be usable?

No.
Snap is a app package format which could contain its own and isolated dependencies and configurations, it is normally not a hardware-emulated system. The official nextcloud snap app for arm64 does not contain a (cpu) hardware emulation layer for nextcloud apps with x86_64 architectures, so it is impossible.

**Comment by tigernero79** [comment]
> > is arm / raspbian compiled?
> 
> No.
> 
> > if i install ubuntu core with nextcloud snap package Will onlyoffice be usable?
> 
> No.
> Snap is a app package format which could contain its own and isolated dependencies and configurations, it is normally not a hardware-emulated system. The official nextcloud snap app for arm64 does not contain a (cpu) hardware emulation layer for nextcloud apps with x86_64 architectures, so it is impossible.

do you have support for lamp system on raspbian armhf or on Ubuntu arm64?  it would be really nice and kick off mass home use

**Comment by tigernero79** [comment]
@EV21 
stubbornly I tried to install ubuntu core 18 arm64 on my raspberry pi4 4gb and installed nextcloud 18 snap and by magic he asked me if I wanted to install useful packages including documenatry server and to my surprise it worked.

so if you can run it on arm64 why can't we do the same on classic non-snap installations?

look here

https://github.com/nextcloud/documentserver_community/issues/90
