### ISSUE TITLE
OO documentation improvement for docker deploy

### ISSUE THREAD

**Issue by LeoChecon** [nextcloud/documentserver_community#333]
Reading the [instructions] (https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx) of OnlyOffice installation on a local server, I found the following:

"Normally, you do not need to store container data because the container operation does not depend on its state. Saving data will be useful:

* for easy access to container data, such as logs;
* to remove the limit on the size of the data inside the container;
* when using services launched outside the container such as PostgreSQL, Redis, RabbitMQ.
"

I think this instruction is misleading, as the content of `/var/lib/onlyoffice` is crucial for preventing data loss in some scenarios (server off, crash, etc).

I suggest to modify this page to something like:

__You should persist the content of `/var/lib/onlyoffice/documentserver` in your computer, using a bind or a named volume. This data is crucial for preventing data loss in some scenarios (server crash, loss of connection, etc.), since OnlyOffice does cache autosave data in this place.__

**Comment by chadek** [comment]
You should open an issue on onlyoffice repo not on this one.
