### ISSUE TITLE
Compatibility with Nextcloud 30

### ISSUE THREAD

**Issue by a1ex-ak** [nextcloud/documentserver_community#337]
Please update to make Community Document Server compatible with Nextcloud 30.

![Image](https://github.com/user-attachments/assets/5afe0767-ca5a-4335-b5e8-08d3da382217)

**Comment by chadek** [comment]
[Nextcloud 30 compatibility](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.20) just added

**Comment by a1ex-ak** [comment]
> [Nextcloud 30 compatibility](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.20) just added

![Image](https://github.com/user-attachments/assets/7736071e-2d9a-4c64-81d2-a83d683b3c92)
 
0.1.18 ))

**Comment by chadek** [comment]
CI was skipping the upload to app store... It should be fix by now
