### ISSUE TITLE
Internal server Error when trying to access https://nextcloud.home/apps/documentserver_community/web-apps/apps/api/documents/api.js

### ISSUE THREAD

**Issue by andreasmolnardev** [nextcloud/documentserver_community#339]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Installed the app on Nextcloud AIO v. 30 (Docker ARM)
2. Tried to open a .docx document -> "ONLYOFFICE cannot be reached. Please contact admin"
3. Console: Refused to execute script from 'https://nextcloud.home/apps/documentserver_community/web-apps/apps/api/documents/api.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

tree output of /var/www/html/custom_apps/documentserver_community
├── 3rdparty
│   └── onlyoffice
│       └── documentserver
│           ├── core-fonts
│           ├── dictionaries
│           ├── document-templates
│           ├── fonts
│           ├── license
│           ├── npm
│           ├── sdkjs
│           ├── sdkjs-plugins
│           ├── server
│           └── web-apps
├── appinfo
│   ├── info.xml
│   └── routes.php
├── documentserver_community
│   ├── 3rdparty
│   │   └── onlyoffice
│   │       └── documentserver
│   ├── appinfo
│   │   ├── info.xml
│   │   └── routes.php
│   ├── img
│   │   ├── app-dark.svg
│   │   └── app.svg
│   ├── js
│   │   ├── binaryerror.js
│   │   └── sessionlimit.js
│   ├── lib
│   │   ├── AppInfo
│   │   │   └── Application.php
│   │   ├── BackgroundJob
│   │   │   └── Cleanup.php
│   │   ├── Channel
│   │   │   ├── ChannelFactory.php
│   │   │   ├── Channel.php
│   │   │   ├── IPCMulticast.php
│   │   │   ├── SessionManager.php
│   │   │   └── Session.php
│   │   ├── Command
│   │   │   ├── FlushChanges.php
│   │   │   └── Fonts.php
│   │   ├── Controller
│   │   │   ├── CoAuthoringController.php
│   │   │   ├── ConvertController.php
│   │   │   ├── DocumentController.php
│   │   │   ├── SessionController.php
│   │   │   └── StaticController.php
│   │   ├── Document
│   │   │   ├── Change.php
│   │   │   ├── ChangeStore.php
│   │   │   ├── ConvertCommand.php
│   │   │   ├── ConverterBinary.php
│   │   │   ├── DocumentConversionException.php
│   │   │   ├── DocumentFormat.php
│   │   │   ├── DocumentStore.php
│   │   │   ├── FontManager.php
│   │   │   ├── Lock.php
│   │   │   ├── LockStore.php
│   │   │   ├── PasswordRequiredException.php
│   │   │   └── SaveHandler.php
│   │   ├── DocumentConverter.php
│   │   ├── FileResponse.php
│   │   ├── IPC
│   │   │   ├── DatabaseIPCBackend.php
│   │   │   ├── DatabaseIPCFactory.php
│   │   │   ├── IIPCBackendFactory.php
│   │   │   ├── IIPCBackend.php
│   │   │   ├── IIPCChannel.php
│   │   │   ├── IIPCFactory.php
│   │   │   ├── IPCChannel.php
│   │   │   ├── IPCFactory.php
│   │   │   ├── MemcacheIPCBackend.php
│   │   │   ├── MemcacheIPCFactory.php
│   │   │   ├── RedisIPCBackend.php
│   │   │   └── RedisIPCFactory.php
│   │   ├── JSSettingsHelper.php
│   │   ├── LocalAppData.php
│   │   ├── Migration
│   │   │   ├── RebuildFonts.php
│   │   │   ├── Version001000Date20190806104527.php
│   │   │   ├── Version001000Date20191217135318.php
│   │   │   ├── Version001000Date20200107143228.php
│   │   │   └── Version001400Date20200129140530.php
│   │   ├── OnlyOffice
│   │   │   ├── AutoConfig.php
│   │   │   ├── URLDecoder.php
│   │   │   └── WebVersion.php
│   │   ├── SetupCheck.php
│   │   ├── XHRCommand
│   │   │   ├── AuthCommand.php
│   │   │   ├── CommandDispatcher.php
│   │   │   ├── CursorCommand.php
│   │   │   ├── GetLock.php
│   │   │   ├── ICommandHandler.php
│   │   │   ├── IIdleHandler.php
│   │   │   ├── IsSaveLock.php
│   │   │   ├── LockExpire.php
│   │   │   ├── OpenDocument.php
│   │   │   ├── SaveChangesCommand.php
│   │   │   ├── SessionDisconnect.php
│   │   │   └── UnlockDocument.php
│   │   ├── XHRResponse.php
│   │   └── XMLResponse.php
│   └── README.md
├── img
│   ├── app-dark.svg
│   └── app.svg
├── js
│   ├── binaryerror.js
│   └── sessionlimit.js
├── lib
│   ├── AppInfo
│   │   └── Application.php
│   ├── BackgroundJob
│   │   └── Cleanup.php
│   ├── Channel
│   │   ├── ChannelFactory.php
│   │   ├── Channel.php
│   │   ├── IPCMulticast.php
│   │   ├── SessionManager.php
│   │   └── Session.php
│   ├── Command
│   │   ├── FlushChanges.php
│   │   └── Fonts.php
│   ├── Controller
│   │   ├── CoAuthoringController.php
│   │   ├── ConvertController.php
│   │   ├── DocumentController.php
│   │   ├── SessionController.php
│   │   └── StaticController.php
│   ├── Document
│   │   ├── Change.php
│   │   ├── ChangeStore.php
│   │   ├── ConvertCommand.php
│   │   ├── ConverterBinary.php
│   │   ├── DocumentConversionException.php
│   │   ├── DocumentFormat.php
│   │   ├── DocumentStore.php
│   │   ├── FontManager.php
│   │   ├── Lock.php
│   │   ├── LockStore.php
│   │   ├── PasswordRequiredException.php
│   │   └── SaveHandler.php
│   ├── DocumentConverter.php
│   ├── FileResponse.php
│   ├── IPC
│   │   ├── DatabaseIPCBackend.php
│   │   ├── DatabaseIPCFactory.php
│   │   ├── IIPCBackendFactory.php
│   │   ├── IIPCBackend.php
│   │   ├── IIPCChannel.php
│   │   ├── IIPCFactory.php
│   │   ├── IPCChannel.php
│   │   ├── IPCFactory.php
│   │   ├── MemcacheIPCBackend.php
│   │   ├── MemcacheIPCFactory.php
│   │   ├── RedisIPCBackend.php
│   │   └── RedisIPCFactory.php
│   ├── JSSettingsHelper.php
│   ├── LocalAppData.php
│   ├── Migration
│   │   ├── RebuildFonts.php
│   │   ├── Version001000Date20190806104527.php
│   │   ├── Version001000Date20191217135318.php
│   │   ├── Version001000Date20200107143228.php
│   │   └── Version001400Date20200129140530.php
│   ├── OnlyOffice
│   │   ├── AutoConfig.php
│   │   ├── URLDecoder.php
│   │   └── WebVersion.php
│   ├── SetupCheck.php
│   ├── XHRCommand
│   │   ├── AuthCommand.php
│   │   ├── CommandDispatcher.php
│   │   ├── CursorCommand.php
│   │   ├── GetLock.php
│   │   ├── ICommandHandler.php
│   │   ├── IIdleHandler.php
│   │   ├── IsSaveLock.php
│   │   ├── LockExpire.php
│   │   ├── OpenDocument.php
│   │   ├── SaveChangesCommand.php
│   │   ├── SessionDisconnect.php
│   │   └── UnlockDocument.php
│   ├── XHRResponse.php
│   └── XMLResponse.php
└── README.md

### Expected behaviour
The document should be opened

### Actual behaviour
As mentioned above

### Server configuration

using docker, :latest

**Nextcloud version:** 30

The error could be caused by the version support and/or architecture (ARM64)

**Comment by chadek** [comment]
Adding [Nextcloud 30 compatibility](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.20) should solve this
