### ISSUE TITLE
 Allow to start up with "odt" (or "ods") by default

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/documentserver_community#34]
Crossposted as https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/225:

When I start a new document, it currently will be stored as ```<filename>.docx```.

However, I prefer to have ```<filename>.odt``` only. Same for ```.ods```.

How can I set this up?

**Comment by icewind1991** [comment]
This change would need to be made in the onlyoffice app, closing in favour of https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/224
