### ISSUE TITLE
Outdated version on Nextcloud App Store

### ISSUE THREAD

**Issue by brianidavide** [nextcloud/documentserver_community#341]
#### Description
The [Document Server App](https://apps.nextcloud.com/apps/documentserver_community) on the Nextcloud App Store is stuck at version `0.1.18`. However, the latest release on the official GitHub repository ([Nextcloud/documentserver_community](https://github.com/nextcloud/documentserver_community)) is version `0.1.20`.

#### Steps to Reproduce
1. Visit the Nextcloud App Store: [Document Server](https://apps.nextcloud.com/apps/documentserver_community).
2. Observe the latest available version (`0.1.18`).
3. Compare with the releases on GitHub: [Releases](https://github.com/nextcloud/documentserver_community/releases) (latest version: `0.1.20`).

#### Expected Behavior
The latest version (`0.1.20`) should be available on the Nextcloud App Store to ensure users have access to the most recent updates and fixes.

#### Actual Behavior
The Nextcloud App Store is not updated to reflect the latest version (`0.1.20`).

#### Impact
Users relying on the App Store for updates may miss critical improvements and fixes included in newer versions.

#### Request
Please update the Nextcloud App Store to include the latest release (`0.1.20`).

#### Additional Information
- **App Store link**: [Document Server](https://apps.nextcloud.com/apps/documentserver_community)
- **GitHub repository**: [Nextcloud/documentserver_community](https://github.com/nextcloud/documentserver_community)
- **GitHub latest release**: `0.1.20`

**Comment by chadek** [comment]
CI was skipping the upload to app store... It should be fix by now
