### ISSUE TITLE
Fonts are incorrect in 0.1.3

### ISSUE THREAD

**Issue by autoize** [nextcloud/documentserver_community#36]
Can finally load the documents with Community Document Server 0.1.3 but the fonts are incorrect. The Normal style should be Arial 11pt. Even though the correct font and font size is displayed in the toolbar, the actual font that is displayed resembles Comic Sans MS. 

![Screenshot_2020-01-24 Document docx - Nextcloud Demo](https://user-images.githubusercontent.com/22459787/73081970-7cffc000-3ec0-11ea-81e7-a11ba731a315.png)

The contents of the fonts folder at `/var/www/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/fonts` looks like this.

```
[root@nextcloud-test-01 fonts]# ls
000  008  016  024  032  040  048  056  064  072  080  088  096  104  112  120  128  136  144  152  160  168  176  184  192  200  208
001  009  017  025  033  041  049  057  065  073  081  089  097  105  113  121  129  137  145  153  161  169  177  185  193  201  209
002  010  018  026  034  042  050  058  066  074  082  090  098  106  114  122  130  138  146  154  162  170  178  186  194  202  210
003  011  019  027  035  043  051  059  067  075  083  091  099  107  115  123  131  139  147  155  163  171  179  187  195  203  211
004  012  020  028  036  044  052  060  068  076  084  092  100  108  116  124  132  140  148  156  164  172  180  188  196  204  212
005  013  021  029  037  045  053  061  069  077  085  093  101  109  117  125  133  141  149  157  165  173  181  189  197  205  213
006  014  022  030  038  046  054  062  070  078  086  094  102  110  118  126  134  142  150  158  166  174  182  190  198  206
007  015  023  031  039  047  055  063  071  079  087  095  103  111  119  127  135  143  151  159  167  175  183  191  199  207
```

**Comment by albertooka** [comment]
The same thing happens to me ... Does anyone know how to solve this problem?

**Comment by davidcheeeese** [comment]
Hello,
Same here and if I add Monofur for powerline and I select it, it's "mry_KacstQurn" displayed on font selection.

**Comment by th3raid0r** [comment]
I'm also experiencing this issue.

**Comment by th3raid0r** [comment]
The fonts in `var/www/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/fonts` are generated by the allfontsgen utility and are expected.

My issue went away once I completely wiped my browser history/cookies (clearing site data wasn't enough).

**Comment by davidcheeeese** [comment]
I tested from android tablet, with Firefox and Opera and fonts are OK. Will try to clear cache and history on the desktop.

**Comment by autoize** [comment]
Cleared cache and it is working properly on Firefox 72.0.2 on Mac OS 10.15.2.
If any others can confirm that it is functioning properly after a browser cache clear, this issue can probably be closed.

**Comment by davidcheeeese** [comment]
I tested on Firefox and Opera on Linux, clearing cache solve the problem and let me use installed fonts.
There is an issue with mobile layout, on a android tablet, tested with Opera and Firefox, installed fonts doesn't appear on the font list. But I think it's another problem requiring another ticket.

**Comment by davidcheeeese** [comment]
Added font on mobile devices appears now, after a reboot of the devices.

**Comment by webresurs** [comment]
- добавить .ttf фалы из «c:\Windows\Fonts» в «/var/www/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/core-fonts» (у вас может быть другой путь) — желательно каждый шрифт в отдельную папку…

- создать .sh файл (отредактируйте путь DIR=".. под ваш)

```
#!/bin/sh


ONLYOFFICE_DATA_CONTAINER=false
if [ "$1" != "" ]; then
    ONLYOFFICE_DATA_CONTAINER=$1
fi

#DIR="/var/www/onlyoffice/documentserver"
DIR="/var/www/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver"

#Start generate AllFonts.js, font thumbnails and font_selection.bin
echo -n Generating AllFonts.js, please wait...

"$DIR/server/tools/allfontsgen"\
  --input="$DIR/core-fonts"\
  --allfonts-web="$DIR/sdkjs/common/AllFonts.js"\
  --allfonts="$DIR/server/FileConverter/bin/AllFonts.js"\
  --images="$DIR/sdkjs/common/Images"\
  --selection="$DIR/server/FileConverter/bin/font_selection.bin"\
  --output-web="$DIR/fonts"\
  --use-system="true"

chown -R www-data:www-data "$DIR/sdkjs"
chown -R www-data:www-data "$DIR/server/FileConverter/bin"
chown -R www-data:www-data "$DIR/fonts"

echo Done

#Remove gzipped fonts
rm -f $DIR/fonts/*.gz $DIR/sdkjs/common/AllFonts.js.gz
```

- запустить этот скрипт (назвал его GeneratingAllFonts )

`sudo -u www-data bash GeneratingAllFonts.sh`

- перезапустить браузер с предварительной очисткой данных (кэш)
