### ISSUE TITLE
HTTPS (self signed) not working with Community Document Server

### ISSUE THREAD

**Issue by ruapotato** [nextcloud/documentserver_community#39]
I installed Nextcloud Hub then installed:
https://apps.nextcloud.com/apps/documentserver_community
When I go to:
ONLYOFFICE settings in Nextcloud and hit save, it gives the error:

```
Error when trying to connect (cURL error 60: SSL certificate problem: self signed certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))
```

I have tried creating a file called "/etc/onlyoffice/documentserver/defaults.json" and adding 
```
services.CoAuthoring.requestDefaults.rejectUnauthorized=false
```
That did not help.

**Comment by icewind1991** [comment]
You can make the document server work with self signed certificates by importing the certificate using

    occ security:certificates:import /path/to/certificate.crt

**Comment by ruapotato** [comment]
That helped a bit. The command I used looked like:
```
sudo -u wwwrun php /srv/www/htdocs/nextcloud/occ security:certificates:import /path/to/certificate.crt
```
Now when I try to hit save I see:
```
Error when trying to connect (cURL error 51: SSL: unable to obtain common name from peer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))
```
I'm guessing my cert skills are lacking.

**Comment by JRelland** [comment]
HI, thank you for CDS

Our CDS is in a NextCloud installed with YUNOHOST with a Let's Encrypt certificate.
As recommanded, I run

```
**occ $** security:certificates:import /path/to/certificate.crt
certificate not found
```
Without "occ" otherwise I have this message:  `Command "occ" is not defined.`

I tried
```
occ $ security:certificates
+-----------+-------------+--------------+-------------+-----------+
| File Name | Common Name | Organization | Valid Until | Issued By |
+-----------+-------------+--------------+-------------+-----------+

```

Thank you for any comment on how to install this certificate

even if OnlyOffice works well :)
https://jreservices.fr/nextcloud/apps/onlyoffice/474?filePath=%2FSpreadsheet (3).xlsx

Thank Jrd from France
