### ISSUE TITLE
x2t: Exec format error

### ISSUE THREAD

**Issue by metsuke0** [nextcloud/documentserver_community#41]
I upgraded my FreeBSD 12.1-RELEASE, Nextcloud 17 instance to Nextcloud 18 and attempted to use the Community Document Server app. I get this error when trying to open any document:

`OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: Exec format error `

Are there possibly separate binaries that I need to grab?

**Comment by laryllian** [comment]
Heyhey, "The community document server only supports running on x86-64 Linux servers using glibc based distributions." Are you running a 64bit OS?

**Comment by metsuke0** [comment]
Since Linux is a requirement then I will not be able to run this. Hopefully in the future, other OS' will be supported

**Comment by goerbs** [comment]
Are ther any news about working on FreeBSD? I am waiting too

**Comment by sankayop** [comment]
Hey there,
FreeBSD community is active :)
I would also be super happy if there were some progress on this issue :)

Thanks in advance to the amazing NC devs
