### ISSUE TITLE
Cannot add fonts

### ISSUE THREAD

**Issue by MartinSfromB** [nextcloud/documentserver_community#42]
I added some fonts with sudo -u userxy php occ documentserver:fonts --add /usr/share/fonts/onlyoffice/xy.ttf.
If I run sudo -u userxy php occ documentserver:fonts my fonts are listed but I cannot use them in a document. My fonts are not shown in the font selection list box. 

If I run allfontsgen (after chmod -x) as in FontManager.php done, I get "error while loading shared libraries: libgraphics.so".

Is here some help?

**Comment by davidcheeeese** [comment]
Check here, it solve my issue #36

**Comment by MartinSfromB** [comment]
> Check here, it solve my issue #36

See no solution there. Also using a clean new browser does not bring the fonts up.

**Comment by icewind1991** [comment]
0.1.4 includes some related fixes, can you see if the problem persists with the latest version

**Comment by MartinSfromB** [comment]
works now as expected for me
