### ISSUE TITLE
cannot download and activate from nextcloud apps

### ISSUE THREAD

**Issue by gilluc** [nextcloud/documentserver_community#43]
i got this message (i am in France):
Une erreur est survenue durant la requête. Impossible de traiter la demande.
i also got on another server:
 cURL error 28: Operation timed out after 30000 milliseconds with 31560252 out of 315860148 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

so no way to install community server....

**Comment by xsxavier** [comment]
Having the same issue, since yesterday as far as I know.

**Comment by mokkin** [comment]
Me too:
```
 cURL error 28: Operation timed out after 30000 milliseconds with 113086772 out of 315860148 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```

**Comment by simphide** [comment]
Either install the app via git manuelly or change the timout in the following file:

/var/www/nextcloud/lib/private/Http/Client/Client.php

e.g. from RequestOptions::TIMEOUT => 30 to RequestOptions::TIMEOUT => 600

**Comment by icewind1991** [comment]
Duplicate of https://github.com/nextcloud/documentserver_community/issues/26

**Comment by gilluc** [comment]
> Either install the app via git manuelly or change the timout in the following file:
> 
> /var/www/nextcloud/lib/private/Http/Client/Client.php
> 
> e.g. from RequestOptions::TIMEOUT => 30 to RequestOptions::TIMEOUT => 600

does not work! maybe apache or nginx option to modify?

**Comment by simphide** [comment]
> > Either install the app via git manuelly or change the timout in the following file:
> > /var/www/nextcloud/lib/private/Http/Client/Client.php
> > e.g. from RequestOptions::TIMEOUT => 30 to RequestOptions::TIMEOUT => 600
> 
> does not work! maybe apache or nginx option to modify?

maybe set it to an higher timeout value

**Comment by gilluc** [comment]
The error msg raises after just 16 seconds.. 


⁣.................
Gilles Lucato
gilles@lucato.com
................ 

Télécharger BlueMail pour Android ​

Le 30 janv. 2020 à 20:58, à 20:58, Simon <notifications@github.com> a écrit:

**Comment by 15538** [comment]
been worked for some time on this issue. It worked with this proposal :

https://help.nextcloud.com/t/community-document-server-curl-error-28-operation-timed-out-after-120000-millisecond/80589/17
