### ISSUE TITLE
Interface size problem with 4k screen

### ISSUE THREAD

**Issue by Alexconquer** [nextcloud/documentserver_community#47]
Hello,
The attached image is enough to understand the problem
Context: 4k screen and 175% scaling in windows settings, Brave browser 1.2.43 (chromium 79)

![screencapture-cloud-index-php-apps-onlyoffice-123-2020-01-29-10_25_05](https://user-images.githubusercontent.com/1763362/73344148-20b2ec80-4282-11ea-9796-02b10485c89c.png)

**Comment by ostasevych** [comment]
The same with 1920x1080 screen. The font size and the size of icons is small comparing with the one used in the NC interface, compare the size of fonts of the title of a browser tab, NC interface and the Documentserver interface:
![image](https://user-images.githubusercontent.com/5199030/73395219-b59c0100-42e7-11ea-906a-6990cc087f93.png)

**Comment by icewind1991** [comment]
This is an upstream issue with onlyoffice, please report it with them
