### ISSUE TITLE
Error when trying to connect (Bad healthcheck status)

### ISSUE THREAD

**Issue by giddisey** [nextcloud/documentserver_community#48]
I have installed ONLYOFFICE 4.1.4 and Community Document Server 0.1.3 on Nextcloud 18.0.0 running in a Docker container (official image) on Ubuntu 19.10 x64. 

When I go to the ONLYOFFICE settings the "Document Editing Service address" and "Server address for internal requests from the Document Editing Service" are prefilled with the address of my Nextcloud instance but the "Document Editing Service address for internal requests from the server" is empty. 

If I hit save on the settings page I get an error toast with the message "Error when trying to connect (Bad healthcheck status)". There are no Onlyoffice options in either the create file menu or the file context menu.

**Comment by axcairns** [comment]
Still not working with 0.1.5. 

I noticed this in my Nextcloud logs (via settings > Logging) - 

[PHP] Error: fclose(): supplied resource is not a valid stream resource at /var/www/html/custom_apps/documentserver_community/lib/Document/FontManager.php#66

GET /index.phpapps/update/documentserver_community
from 59.167.111.65 by allan at 2020-02-04T12:59:10+00:00

... and this in my docker logs for the nextcloud container - 

[Tue Feb 04 20:59:38.166593 2020] [authz_core:error] [pid 125] [client 59.167.111.65:0] AH01630: client denied by server configuration: /var/www/html/config

**Comment by SenchoPoro42** [comment]
I have this same issue.
If I change https://mydomain.tld/apps/documentserver_community to https://localhost/apps/documentserver_community I get "ONLYOFFICE cannot be reached. Please contact admin" instead.
I have nginx setup with reverse proxies and am wondering if I need a change to one of the location flags to reflect this new access.

**Comment by Wdavery** [comment]
Stuck at this point too, also behind a nginx reverse proxy.

**Comment by klaask** [comment]
Similar setup and healthcheck error on our side:
nginx reverse proxy & ssl termination (no docker)

To fix this error we added a different subdomain as "Document Editing Service address" and "Server address for internal requests from the Document Editing Service" and as trusted_domain in config.php.

**Comment by SenchoPoro42** [comment]
I fixed my issue by letting removing the ONLYOFFICE application only, then installing it again. The correct server address was already filled in, but I just avoided pressing save on it and it then worked correctly and could connect.

**Comment by LordMort** [comment]
The following fixed my issue on a NC 19.0.6 installation with OO 0.1.8 DSCE.
1) In the OO-settings page I simply removed ALL server-entries and REFRAINED from clicking the safe-button.
2) After that I switched to another settings page, the "Overview" in my case, and returned to the OO-settings without changing anything else.
3) The OO-settings had been auto-filled with working entries, see below. Clicking on the safe-button at that time successfully enabled OO in my NC-installation.

The entry that had been auto-filled was:
https://<MY.DOMAIN.TLD>/index.php/apps/documentserver_community/

**Comment by TheSimu** [comment]
@LordMort : Thanks! Your the hero of the day with that URL - did the trick on v.21 and current OO as of today...

**Comment by MaoMaoCake** [comment]
> The following fixed my issue on a NC 19.0.6 installation with OO 0.1.8 DSCE.
> 
> 1. In the OO-settings page I simply removed ALL server-entries and REFRAINED from clicking the safe-button.
> 2. After that I switched to another settings page, the "Overview" in my case, and returned to the OO-settings without changing anything else.
> 3. The OO-settings had been auto-filled with working entries, see below. Clicking on the safe-button at that time successfully enabled OO in my NC-installation.
> 
> The entry that had been auto-filled was: https://<MY.DOMAIN.TLD>/index.php/apps/documentserver_community/

if this dosent work try adding ```/index.php/apps/documentserver_community/``` to the end of the url 
for example your server is at https://<MY.DOMAIN.TLD>/ fill in https://<MY.DOMAIN.TLD>/index.php/apps/documentserver_community/

**Comment by iamhakeembey** [comment]
> The following fixed my issue on a NC 19.0.6 installation with OO 0.1.8 DSCE.
> 
> 1. In the OO-settings page I simply removed ALL server-entries and REFRAINED from clicking the safe-button.
> 2. After that I switched to another settings page, the "Overview" in my case, and returned to the OO-settings without changing anything else.
> 3. The OO-settings had been auto-filled with working entries, see below. Clicking on the safe-button at that time successfully enabled OO in my NC-installation.
> 
> The entry that had been auto-filled was: https://<MY.DOMAIN.TLD>/index.php/apps/documentserver_community/

In my case I had to click "Save", but simply changing the URL manually works the same. Just ensure that it includes the "index.php". Also, it's important that both "Nextcloud Office" and "Collabora Online - Built-in CODE Server" are disabled. Otherwise, documents will be stalled at the loading screen as [at least one of] the two apps appear to interfere with ONLYOFFICE somehow. Once disabled, everything worked fine for me.

**Comment by goulvench** [comment]
In my case, I had installed OnlyOffice from NextCloud's app directory, but documentserver_community had not been downloaded automatically. I had to add it myself, then activate it, then re-enable the OnlyOffice connector, and now things run fine.
