### ISSUE TITLE
0.1.4 activity app shows own entrys as changes from "External Users"

### ISSUE THREAD

**Issue by apg1980** [nextcloud/documentserver_community#49]
Hi i am using

Nextcloud 18
User_Ldap
Documentserver_Community
PHP7.3
Postgresql

Changes in Documents appears in Activity app as "External User" instead of my own.

Best regards

**Comment by q-wertz** [comment]
Same here.
nextcloud app "Onlyoffice" version: 4.1.4
nextcloud app "Community Document Server" version: 0.1.5

![image](https://user-images.githubusercontent.com/20948931/73736273-6830f100-4738-11ea-8226-e258af6c0bd3.png)

**Comment by icewind1991** [comment]
might be fixed with 0.1.8
