### ISSUE TITLE
Print function is not showing available printers

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/documentserver_community#50]
By clicking on the icon Print or clicking Ctrl-P I am suggested to save the document in PDF file instead of showing the interface window with selection of printers. 

Normally it should show available options on printing documents, available both in the web browser and the OS itself.

**Comment by MartinSfromB** [comment]
Same here. Since switching from my onlyoffice docker solution to the new own nextcloud solution the print button leads to a download instead opening print dialog.

**Comment by icewind1991** [comment]
For me, when using the docker image I also only get the pdf download option, so I'm not sure how to resolve this issue

**Comment by ostasevych** [comment]
> For me, when using the docker image I also only get the pdf download option, so I'm not sure how to resolve this issue

It works fine with Collabora eg.
