### ISSUE TITLE
App Fails with Onlyoffice cannot be reached - please contact admin

### ISSUE THREAD

**Issue by dblinick** [nextcloud/documentserver_community#51]
Getting the following error in nextcloud.log
on 0.1.4 with next cloud 18.0.0.10

Looks similar to https://github.com/nextcloud/documentserver_community/issues/24

Errors:
`{"reqId":"s7M7cbDXBeFN29JsDOyi","level":3,"time":"2020-01-29 16:45:50","remoteAddr":"192.168.5.15","user":"dblinick","app":"index","method":"GET","url":"/apps/documentserver_community/web-apps/apps/api/documents/api.js","message":{"Exception":"Exception","Message":"trim() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/var/www/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},{"file":"/var/www/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/var/www/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/var/www/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},{"file":"/var/www/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"trim() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/data/userapps/documentserver_community/lib/SetupCheck.php","line":80,"function":"trim","args":[false]},{"file":"/data/userapps/documentserver_community/lib/SetupCheck.php","line":55,"function":"lddError","class":"OCA\\DocumentServer\\SetupCheck","type":"->","args":[]},{"file":"/data/userapps/documentserver_community/lib/Controller/StaticController.php","line":90,"function":"getHint","class":"OCA\\DocumentServer\\SetupCheck","type":"->","args":[]},{"file":"/var/www/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"webApps","class":"OCA\\DocumentServer\\Controller\\StaticController","type":"->","args":["apps/api/documents/api.js"]},{"file":"/var/www/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},{"file":"/var/www/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},{"file":"/var/www/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/var/www/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/var/www/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},{"file":"/var/www/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/data/userapps/documentserver_community/lib/SetupCheck.php","Line":80},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","version":"18.0.0.10"}`

**Comment by mgiggs** [comment]
I am getting the same issue.

Error:
`{"reqId":"sU9JxluZ5ic8sLe6dfQ2","level":3,"time":"2020-02-05T01:09:31+00:00","remoteAddr":"192.168.2.173","user":"giggs_admin","app":"index","method":"GET","url":"/apps/documentserver_community/web-apps/apps/api/documents/api.js","message":{"Exception":"Exception","Message":"trim() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},{"file":"/config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/config/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},{"file":"/config/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"trim() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php","line":80,"function":"trim","args":[false]},{"file":"/config/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php","line":55,"function":"lddError","class":"OCA\\DocumentServer\\SetupCheck","type":"->","args":[]},{"file":"/config/www/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php","line":90,"function":"getHint","class":"OCA\\DocumentServer\\SetupCheck","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"webApps","class":"OCA\\DocumentServer\\Controller\\StaticController","type":"->","args":["apps/api/documents/api.js"]},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},{"file":"/config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"file":"/config/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},{"file":"/config/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/config/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php","Line":80},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","version":"18.0.0.10"}`

**Comment by NeroBurner** [comment]
does this may help?
https://help.nextcloud.com/t/after-upgrading-from-v17-0-3-to-v18-0-0-10-onlyoffice-cannot-be-reached-please-contact-admin/70223/4

essentially remove `Document Editing Service Address` in the app configuration. It then defaults to the following:
```
https://YOUR-DOMAIN-NAME/apps/documentserver_community/
```

**Comment by mr-bolle** [comment]
If you open after this changes from NeroBurner a "Unknown Error" - you have to add into your nextcloud config\config.php. Then you should have access to your Office Documents.

`'overwriteprotocol' => 'https',`

**Comment by blitzdesigner** [comment]
> If you open after this changes from NeroBurner a "Unknown Error" - you have to add into your nextcloud config\config.php. Then you should have access to your Office Documents.
> 
> `'overwriteprotocol' => 'https',`

This does not work with me, first I get a blank page after adding this option, then after saving the settings in OnlyOffice again I'm back at the first place...
