### ISSUE TITLE
xt2 Syntax error "(" unexpected

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/documentserver_community#52]
I have this app installed on my nextcloud on my raspberry pi 4 as snap package. The target OS is Ubuntu Server (64bit)

Every time I try to open a document I get following error:
![grafik](https://user-images.githubusercontent.com/23138465/73444940-efa5eb00-4359-11ea-81d5-a544f7137c69.png)

And in the nextcloud error log I can find the same two errors as every time I try to open a document.

The first one:
![grafik](https://user-images.githubusercontent.com/23138465/73445002-106e4080-435a-11ea-901a-9a54e5ce5dce.png)

And that is the second:
![grafik](https://user-images.githubusercontent.com/23138465/73445036-1ebc5c80-435a-11ea-802c-4365093ce2b4.png)

**Comment by mr-bolle** [comment]
Have a look into this issue 

https://github.com/nextcloud/documentserver_community/issues/10

**Comment by Pilzinsel64** [comment]
Thank you. I tried all the solutions described there, but nothing did help.
Maybe, because in #10 they describe the problem with having an "xt2 not found" error, but I have an "xt2 Syntax error" every time i try to create or open a new document of any type.

**Comment by smolinde** [comment]
I face the same issue right now. After executing x2t it throws:
`./x2t: 1: Syntax error: "(" unexpected`
Which I believe is a coding error, but I don't know where the x2t file is stored so I could manually fix this. Does someone has a hint?
