### ISSUE TITLE
Using NC Hub Community Documentserver file gets modified but revisions and activity are not tracked

### ISSUE THREAD

**Issue by penzoiders** [nextcloud/documentserver_community#53]
I post this issue here since I believe it's an issue of this php implementation of the OnlyOffice document server.
```
nextcloud version 18.0.0
onlyoffice version: 4.1.4
documentserver_community version: 0.1.4
```

## Procedure used to highlight the issue:
- Log in to NextCloud
- Navigate to a folder containing an XLSX 
- Click on the XLSX file
- OnlyOffice Editor is launched
- Modify the Document
- Close  OnlyOffice Editor
- Back to the folder view, select "Details" for the XLSX file

## Expected behavior
> obtained when using an external community document server: plain community document server installed on a centos system using this script: https://gist.github.com/penzoiders/105c6ac92912bd6b3367eef9d1201e04
- I'm able to see, in the Activity tab, an entry for my modification action
- I'm able to see, in the Versions tab, a revision kept for roll-back at the state before my modification

## Current behavior
> obtained when using the integrated community document server form NC Apps 
- I'm **NOT** able to see, in the Activity tab, an entry for my modification action
- I'm **NOT** able to see, in the Versions tab, a revision kept for roll-back at the state before my modification

![image](https://user-images.githubusercontent.com/7568057/73440894-67701780-4352-11ea-9222-d1e490cd6c13.png)

**Comment by rakekniven** [comment]
Confirmed

**Comment by lenni-web** [comment]
confirmed. This is a big problem ... . When you make changes in OnlyOffice and afterwards you download the file from Nextcloud, you receive the old, non edited, document

**Comment by dtony** [comment]
I am facing the same issue, no error in logs. The only error i can find is in the browser console :
`Failed to load resource: /ocs/v2.php/apps/text/workspace?path=%2F the server responded with a status of 404 (Not Found)`
but I don't think it is related.

**Comment by chrstn-hntschl** [comment]
It seems #55 is also related to this issue.

**Comment by HFranz** [comment]
same here with NC 18.0.3 and native OO integration.

**Comment by sebthesun** [comment]
Same with NC 20.0.5, OO documentserver 6.1.1
