### ISSUE TITLE
stream_get_contents(): supplied resource is not a valid stream resource at FontManager.php#67

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/documentserver_community#54]
Got this error from time to time in den Nextcloud logs...

Updated from Nextcloud 17.0.2 to 18.0.0

```
{"reqId":"XjMU7cZJFoD7u3HgzTIDhgAAAAg","level":3,"time":"2020-01-30T17:41:06+00:00","remoteAddr":"84.161.215.253","user":"USERNAME","app":"PHP","method":"GET","url":"/settings/apps/update/documentserver_community","message":"fclose(): supplied resource is not a valid stream resource at /var/www/html/nextcloud/apps/documentserver_community/lib/Document/FontManager.php#66","userAgent":"Mozilla/5.0 (Linux; Android 9; SNE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Mobile Safari/537.36","version":"18.0.0.10","id":"5e3317a41b45b"}
{"reqId":"XjMU7cZJFoD7u3HgzTIDhgAAAAg","level":3,"time":"2020-01-30T17:41:06+00:00","remoteAddr":"84.161.215.253","user":"USERNAME","app":"PHP","method":"GET","url":"/settings/apps/update/documentserver_community","message":"fclose(): supplied resource is not a valid stream resource at /var/www/html/nextcloud/apps/documentserver_community/lib/Document/FontManager.php#66","userAgent":"Mozilla/5.0 (Linux; Android 9; SNE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Mobile Safari/537.36","version":"18.0.0.10","id":"5e3317a41b45b"}
```

**Comment by Rogergonzalez21** [comment]
Same here! Upgraded from 17.0.2 to 18.0.0, using docker-compose for my configuration

**Comment by Nils160988** [comment]
Happening here after update of the document_server app to version 0.1.5

**Comment by ghostwind66** [comment]
Yes, I can also confirm this as well. the error occurs for me on both 0.1.4 and 0.1.5

**Comment by brogers-navex** [comment]
Try the permission fix as mentioned here: https://github.com/nextcloud/documentserver_community/issues/40

**Comment by herrwusel** [comment]
I can confirm this behaviour in my docker set up as well:
```
{"reqId":"jQO0XzQaMjeAT8wAirca","level":3,"time":"2020-02-07T10:57:52+00:00","remoteAddr":"xx","user":"xx","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"fclose(): supplied resource is not a valid stream resource at /var/www/html/custom_apps/documentserver_community/lib/Document/FontManager.php#66","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10","id":"5e3d883c40b3f"}
{"reqId":"jQO0XzQaMjeAT8wAirca","level":3,"time":"2020-02-07T10:57:52+00:00","remoteAddr":"xx","user":"xx","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"stream_get_contents(): supplied resource is not a valid stream resource at /var/www/html/custom_apps/documentserver_community/lib/Document/FontManager.php#67","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10","id":"5e3d883c40b2f"}
```
Mentioned permission fix didn't help it.

**Comment by howudodat** [comment]
same problem here.  not running in a docker container.  fresh install of both nc18 and document server.

**Comment by xthursdayx** [comment]
I'm also having this same problem & FontManager.php#66 as well. I'm running nc18.0.1 via the Linuxserver Nextcloud image. 

```
[PHP] Error: stream_get_contents(): supplied resource is not a valid stream resource at /config/www/nextcloud/apps/documentserver_community/lib/Document/FontManager.php#67

POST /settings/apps/enable
from 172.19.0.1 by xthursdayx at 2020-02-16T20:15:55+00:00
```

**Comment by inkfs** [comment]
nc 18.0.1
cds 0.1.5
ubuntu server 18.04 

setting permissions as in suggested in #40 is not possible, the file does not exist after unpacking cds 0.1.5.

ie there is no "allfontsgen" in

$NEXTCLOUD_DIR/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/

It is, however in 

$NEXTCLOUD_DIR/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/tools

There the execution-bit is set (-rwxr-xr-x). #40 suggests "chmod -", thus removing the execution bit.

**Comment by Aurnytoraink** [comment]
I got the same error to with my docker installation.
[Link to the forum](https://help.nextcloud.com/t/onlyoffice-cant-open-file/71867/6?u=aurnytoraink)

**Comment by Oliv4945** [comment]
Hi,

I think that it is not an execution right issue as rights are set [here](https://github.com/nextcloud/documentserver_community/blob/f1b67feb1e40b6a888fedbb0213e0c7f93734b24/lib/Document/FontManager.php#L43), but `allfontsgen` is looking for libraries it does not find. Adding symlinks from `FileConverter/bin` in `server/tools` of : 
```
libUnicodeConverter.so
libgraphics.so
libicudata.so.58
libicuuc.so.58
libkernel.so
```
helps and the message disappears. Fonts are listed in `documentserver_community/3rdparty/onlyoffice/documentserver/fonts` but OnlyOffice is still not working :/

It seems that this file has been created by @icewind1991 maybe he can help :)

**Comment by Jolopu** [comment]
Same problem here with Nextcloud 18.0.2
fclose(): supplied resource is not a valid stream resource at /home/www/cloud.myserver.tv/apps/documentserver_community/lib/Document/FontManager.php#66

**Comment by Jolopu** [comment]
I think the issue has to do with the font used in the docx. It was created in MS Word with Calibri. Then it was saved on Nextcloud. When I tried to open it with OnlyOffice it got stuck on loading. Calibri is not included in the OnlyOffice fonts. When I created the document using Arial I could open it in OnlyOffice.

**Comment by WhilelM** [comment]
I have the messages at the activation of app documentserver_community ´occ app:enable documentserver_community´

**Comment by mcnesium** [comment]
> I think the issue has to do with the font used in the docx
Can not approve. Just updated NC from v17.0.4 to v18.0.2 (Docker) and downloaded and enabled *Community Document Server* app afterwards. It took quite some time to install, obviously, but when it was done, nothing else happened. No extra icon in the header menu, no extra entries in the (+) menu. Instead, I also see the aforementioned `stream_get_contents()…` notes in the logs. There are no .docx nor .odt nor any other documents anywhere whatsoever.

**Comment by Aurnytoraink** [comment]
@mcnesium I'm in the same situation as you but I have the icons.
In the settings, go to the ONLYOFFice tab and make sure that the address is "https" (that worked for me)
But I'm still stuck. When I create a new document, openoffice launch up but I get an error pop-up

**Comment by mcnesium** [comment]
@Aurnytoraink unfortunately, there is also no OnlyOffice tab in the settings :(

**Comment by Aurnytoraink** [comment]
@mcnesium Go the applications and make sure that only office is installed

**Comment by mcnesium** [comment]
@Aurnytoraink 

![Screenshot_2020-03-18 Apps - Nextcloud](https://user-images.githubusercontent.com/476060/76948905-07383380-6908-11ea-98b0-94e77c82aca8.png)

![Screenshot_2020-03-18 Settings - Nextcloud](https://user-images.githubusercontent.com/476060/76948877-ff788f00-6907-11ea-9180-3e306c7af1e2.png)

![Screenshot_2020-03-18 Logging - Nextcloud](https://user-images.githubusercontent.com/476060/76948931-10290500-6908-11ea-9dc1-730ea24362da.png)

**Comment by Aurnytoraink** [comment]
@mcnesium on the applications page (first pic), click on the search button (top-right corner) and search for onlyoffice

**Comment by mcnesium** [comment]
@Aurnytoraink Thank you, now I understand.

Why in the world does it not say "You also need to install this other app" on the top of the README.md of this app? I am sure many users struggle to get this running just because Nextcloud does not communicate transparently how to do it.

So now I got this ONLYOFFICE ([*](https://www.stadtkindfrankfurt.de/wp-content/uploads/frankfurt-sticker-acab-all-caps-and-bold.jpg)) entry in the settings. `Document Editing Service address` is set to `https://cloud.mydomain.de/index.php/apps/documentserver_community/` and I was able to create a spread sheet using the (+) menu. Thank you for guiding me to that :+1:

**Comment by inkfs** [comment]
Thank you @Aurnytoraink @mcnesium 
Finally I have OO up and running, too : )

**Comment by Aurnytoraink** [comment]
Glad that's working for you :disappointed_relieved:

**Comment by Oliv4945** [comment]
Thank you @Aurnytoraink , I did not understood too that a second package is required...

**Comment by herrwusel** [comment]
Same here. Thanks for clarifying @Aurnytoraink !
