### ISSUE TITLE
Manual saving and warning when navigating away?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/documentserver_community#55]
It seems like it is not possible to do manual saving of a document right now (only autosave).

There is also no warning or saving when using the Nextcloud menu to navigate away from the document, leading to data loss up to the latest autosave point.
I guess the latter is more an issue with the connector app, but saving (or intentionally discarding unsaved data) is an general issue right now.

**Comment by chrstn-hntschl** [comment]
Maybe related: when I close an open document with the small x (upper right corner) and reopen it again I can see myself twice as co-editor with unsaved changes. Sometimes, an old state of the document is opened. How do I actively sync changes?
