### ISSUE TITLE
25s websocket time

### ISSUE THREAD

**Issue by markuman** [nextcloud/documentserver_community#60]
![S](https://user-images.githubusercontent.com/3920157/73831456-abf22c00-4806-11ea-8263-d10e5ae56591.png)

After updating from Nextcloud 17 with separate documentserver in a docker container to Nextcloud 18 using documentserver community app, we see that the websocket connection has always a time of  ~25 seconds (99% goes to "Waiting TTFB").

Is it by design? Is it a bug? Any ideas/words about it?

**Comment by icewind1991** [comment]
This is by design as the documentserver uses long polling with a 25s timeout
