### ISSUE TITLE
Can't install Docserver 

### ISSUE THREAD

**Issue by KoljaL** [nextcloud/documentserver_community#61]
Hi there

I can't install the app on a fresh NC 18, running on a normal webspace (no root access)
There are this message: "`Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.`"
gtranslate: "An error has occurred in the request. It cannot continue."

What can i do?

**Comment by lenni-web** [comment]
Just have a look in the Logfile. You can find it settings -> logging

When you can see the error, it may be one of these problems:
https://github.com/nextcloud/documentserver_community/issues/26
oder https://github.com/nextcloud/documentserver_community/issues/57

**Comment by KoljaL** [comment]
Hi Lenni

There is no entry in the logs. (logLevel => 0)

And this: 
> I’ve solved the Problem by manually Setting the Value for
> "RequestOptions::TIMEOUT "
> to 120 or a higher value in the following file:
> “/path/to/nextcloud/lib/private/Http/Client/Client.php”
makes no difference.

**Comment by nfavrod** [comment]
Hello - I got an error too when installing : 

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Can someone help?

**Comment by BerndCz** [comment]
I get this error when I try to install DocumentServer on a fresh Nextcloud Hub installation:

GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 119987 milliseconds with 269167996 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

What can I so?

**Comment by PopeRigby** [comment]
Also having this issue

**Comment by batgranny** [comment]
+1, the resultion mentioned (Increasing the timeout) produces the same error in 18.0.1

**Comment by ureimers** [comment]
I increased my `max_execution_time` and `max_input_time` to 600 seconds.

Interestingly the message "Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden." always comes up after exactly 60 seconds.

The Guzzle-Timeout-Log-Entry isn't displayed in a yellow alert box [like the one displayed in the documentation](https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/), instead it's in settings/logging (Einstellung/Protokolierung):

```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 120000 milliseconds with 80180796 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html
```

This happens exactly 120 seconds after I tried to install the document server (so 60 seconds after the App-Installer said that the installation failed). So I assumed that the installation was, in fact, still running, even if the above message was displayed by the installer.

So I patched `lib/private/Http/Client/Client.php` like this:
```
	private function buildRequestOptions(array $options): array {
		$defaults = [
			RequestOptions::PROXY => $this->getProxyUri(),
			RequestOptions::VERIFY => $this->getCertBundle(),
			RequestOptions::TIMEOUT => 30,
		];

		$options = array_merge($defaults, $options);
		
		$options[RequestOptions::TIMEOUT] = 600; // <-- That line is new.

		if (!isset($options[RequestOptions::HEADERS]['User-Agent'])) {
			$options[RequestOptions::HEADERS]['User-Agent'] = 'Nextcloud Server Crawler';
		}

		return $options;
	}
```

Just changing `RequestOptions::TIMEOUT` from 30 to, e.g., 600 won't change a thing because that's only the default value which gets overwritten with the value from the parameter `$options` (which seems to be 120 in my case and ignores `max_execution_time`). So I had to set it _after_ the merge with the passed options array.

Now the message "Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden." still was displayed but the installer was still able to do its job, no errors where logged and the document server was installed.

I then installed the OnlyOffice App which successfully installed and added the document server address into it's configuration but when I tried to edit an Excel file I got "ONLYOFFICE ist zurzeit nicht erreichbar. Bitte wende Dich an Deinen Administrator".

There was no error in the error log so I figured that the installer wasn't run correctly (remember the halt after exactly 60 seconds from above).

So I deactivated the Document Server app and activated it again in the hope that this would skip the download and just run the installer again.

Now that instantly leads to the above error message: "Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden." and the error log shows three entries:

```
proc_open() has been disabled for security reasons at /var/www/vhosts/ulfreimers.de/nc.ulfreimers.de/apps/documentserver_community/lib/Document/FontManager.php#64

Undefined offset: 0 at /var/www/vhosts/ulfreimers.de/nc.ulfreimers.de/apps/documentserver_community/lib/Document/FontManager.php#66

Exception: fclose() expects parameter 1 to be resource, null given
```

I'm out of options.

**Comment by PopeRigby** [comment]
Here's my error, if it's useful:
```
[settings] Error: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 120000 milliseconds with 204186884 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at <<closure>>

 0. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 149
    GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\Handl ... l}, {errno: 28,error ... 2})
 1. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 102
    GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 2. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 43
    GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 3. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 28
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 51
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 5. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 37
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 6. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 30
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 7. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 70
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 107
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 9. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 72
    GuzzleHttp\RedirectMiddleware->checkRedirect(GuzzleHttp\Psr7\Request {}, "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
10. /config/www/nextcloud/3rdparty/guzzlehttp/promises/src/FulfilledPromise.php line 39
    GuzzleHttp\RedirectMiddleware->GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
11. /config/www/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 47
    GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
12. /config/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 246
    GuzzleHttp\Promise\TaskQueue->run(true)
13. /config/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 223
    GuzzleHttp\Promise\Promise->invokeWaitFn()
14. /config/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 267
    GuzzleHttp\Promise\Promise->waitIfPending()
15. /config/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 225
    GuzzleHttp\Promise\Promise->invokeWaitList()
16. /config/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
17. /config/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php line 131
    GuzzleHttp\Promise\Promise->wait()
18. /config/www/nextcloud/lib/private/Http/Client/Client.php line 149
    GuzzleHttp\Client->request("get", "https://github. ... z", {proxy: null,ver ... e})
19. /config/www/nextcloud/lib/private/Installer.php line 274
    OC\Http\Client\Client->get("https://github. ... z", {save_to: "/tmp/ ... 0})
20. /config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 440
    OC\Installer->downloadApp("documentserver_community")
21. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->enableApps(["documentserver_community"], [])
22. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
23. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
24. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
25. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
26. /config/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
27. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/enable")
28. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

POST /settings/apps/enable
from 172.18.0.5 by poperigby at 2020-03-02T17:35:11+00:00
```

**Comment by timthee** [comment]
Here's mine on 18.0.1 : 
`Out of memory (allocated 37748736) (tried to allocate 315857416 bytes) at /homepages/3/d455544589/htdocs/tangente/lib/private/Installer.php#278`

**Comment by MuellerSeb** [comment]
@timthee I had the same problem. In your (my) case, it's not a timeout, but the allowed memory size that is to low. I had to edit my `php.ini` and change the line setting the memory limit:

    memory_limit = 512M

Afterwards I could install. Hope that helps.
Cheers, Sebastian

**Comment by KoljaL** [comment]
and for those without access to the php.ini:
write into the` .htaccess`:
`php_value memory_limit 512M`

but not all hosters give you the 512....

**Comment by PopeRigby** [comment]
> @timthee I had the same problem. In your (my) case, it's not a timeout, but the allowed memory size that is to low. I had to edit my `php.ini` and change the line setting the memory limit:
> 
> ```
> memory_limit = 512M
> ```
> 
> Afterwards I could install. Hope that helps.
> Cheers, Sebastian

That didn't work for me. Same error.

**Comment by MuellerSeb** [comment]
@PopeRigby that is because you didn't have a memory error but a timeout error (as written in your log). You could try setting:

    max_execution_time = 240

Since your download aborts after 120 seconds.

**Comment by MuellerSeb** [comment]
And as @KoljaL mentioned:
You could try adding this `.htaccess`, if you can't write to `php.ini`:

    php_value max_execution_time 240

**Comment by PopeRigby** [comment]
Same error.

**Comment by JonnyHaystack** [comment]
I'm also getting this error
```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 120000 milliseconds with 105666108 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I tried adding `php_value max_execution_time 800` to both `/config/.htaccess` and `/data/.htaccess`, but it's still timing out after 120 seconds so it looks like that has no effect. I'm running Nextcloud in docker.

**Comment by JonnyHaystack** [comment]
Some more information:
- I am on Nextcloud 18.0.3 and latest version of OnlyOffice connector app
- When looking in the network tab of my browser's developer console, it shows a request to `Editor.bin` has status `blocked:csp`
