### ISSUE TITLE
Cenros 7 Selinux Prolem after install

### ISSUE THREAD

**Issue by gueniewie** [nextcloud/documentserver_community#62]
Hello
I test now on my server (centos7) the new nextcloud 18 with onlyoffice and documentserver, but it is only running with disabled Selinux ?
What is the way to have Selinux again enabled?

the Problem files I mean are x2t.

Have any correct policy for the documentserver

Thanks

**Comment by Wotisrv** [comment]
Still present in 2021 with Nextcloud 20 and latest OnlyOffice.
