### ISSUE TITLE
Pasting an image into a document causes the editor to get stuck "loading image"

### ISSUE THREAD

**Issue by BlipRanger** [nextcloud/documentserver_community#64]
Hey guys, working with NC18 + the documentserver_community for the first time and I'm encountering this issue where attempting to paste an image from the clipboard into a doc is causing the editor to freeze up and get stuck with the "loading image" popup spinning. In case it makes a difference, I am running this instance of NC in docker behind Traefik but I don't have any issues accessing anything else on the server so I think those configurations are correct.

**Comment by bremensaki** [comment]
I'm able to reproduce this, also same issue when using insert image from Nextcloud storage. No Docker involved here, Debian 10 server with Nginx. Same issue on a non-public test server running Ubuntu 18.04.

Only insert from file works reliably - never had any issues with that method at all, including a drag and drop of an image onto the browser window.

**Comment by alexanderonlyoffice** [comment]
@BlipRanger, @bremensaki, if you are using the Community Document Server app developed by Nextcloud, we cannot assist with its issues. Please refer to the post on our official forum under this [link](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by icewind1991** [comment]
This should be fixed with the next release (5359f2a)

**Comment by markuman** [comment]
#73

**Comment by Bolli84** [comment]
Just patched and tried the mentioned fix: [https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/233](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/233)

It is working just fine.

**Comment by eeintech** [comment]
I can confirm I have the same issue in NC18.0.4 pasting or inserting "Image from Storage".
Inserting "Image from File" works fine.

**Comment by thomber-ethz** [comment]
We encounter the same issue on our NC 18.0.4 installation. Pasting a JPEG image from the clipboard (CTRL+V) to a document infinitely shows _loading Image_ and the OnlyOffice editor gets stuck. We see the same effect when trying to insert an image from URL. Inserting by File and Storage is just working fine.
