### ISSUE TITLE
'Missing' features documentation

### ISSUE THREAD

**Issue by pc-robelbois** [nextcloud/documentserver_community#65]
Hi

The following description can be found on your app's page on nextcloud webpage:

> The community document server is designed to make it easy to get OnlyOffice running in a Nextcloud instance without the need to setup an external document server, the community document server **_does not support all features_** of the official OnlyOffice document server and does not provide the same performance and scalability.

Could you please specify the missing features ? I am unable so far to see the difference (new to ONLYOFFICE).

Thanks

**Comment by tcitworld** [comment]
OnlyOffice posted something about this on their forum: https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444
