### ISSUE TITLE
ARM support planned?

### ISSUE THREAD

**Issue by Schroedingers-Cat** [nextcloud/documentserver_community#69]
Will this port(?) of OnlyOffice support ARM CPUs at some point in the future?

**Comment by tigernero79** [comment]
I also make an effort to know if its scheduled to have apps for arm.  I use a Pi4 Pi4 raspberry with 4gb of ram and it would be a sight to be able to manage onlyoffice on it.  please give us a date.

**Comment by tigernero79** [comment]
wooohhh

https://github.com/nextcloud/documentserver_community/issues/90

**Comment by elpraga** [comment]
Any plans on aarch64 support? Have you got a timeline?

**Comment by giacp** [comment]
Any news about arm support?

**Comment by markuman** [comment]
> [Starting from version 7.1, ONLYOFFICE Docs can be installed using Docker for the 64-bit ARM architecture.](https://helpcenter.onlyoffice.com/installation/docs-community-install-docker-arm64.aspx)

I think it's time for make an update to the community document server ....
