### ISSUE TITLE
modification date

### ISSUE THREAD

**Issue by prolibre** [nextcloud/documentserver_community#71]
I don't know if it's this app that is concerned but when I leave onlyoffice after having modified a document, the modification date (in nextcloud) doesn't change. This implies (for example) that my fulltext search doesn't start.

Nextcloud 18 and Nextcloud 18.1 and Nextcloud 18.2 (update 03/13)

PS : if it's not this app where I can report the bug please

**Comment by pc-robelbois** [comment]
@prolibre I noticed the same. Also this seems that a document can be edited multiple times by multiples uses without triggering a new version/history. Have you noticed that ?

**Comment by tjareson** [comment]
I have the same issue here. Moreover all changes made will disappear if I copy the document within nextcloud. 
It looks like that the updated documents never get processed back to the original file. If I look inside of nextcloud docker image I see that the temporary files (Editor.bin etc) never gets processed.
I wonder what triggers the build of the document after editing it. It happened once that it worked properly, but never again afterwards.

**Comment by tk7936** [comment]
Same issue here. This also causes Versioning to not work and sync client only syncs new file or deletions not updates anymore.

**Comment by vsandre** [comment]
same problem as in #12
