### ISSUE TITLE
FreeBSD Support planned?

### ISSUE THREAD

**Issue by goerbs** [nextcloud/documentserver_community#74]
Will this port(?) of OnlyOffice support FreeBSD at some point in the future?

**Comment by mzary** [comment]
I got it working on FreeBSD with Linux emulation enabled. It will be nice to have Community Document Server running on FreeBSD natively. The same for ONLYOFFICE suite, perhaps it will gain FreeBSD support in the future.

**Comment by defilor** [comment]
+1 as I would assume many people are running nextcloud on freenas

**Comment by privettoli** [comment]
When I read about "DocumentServer" I had hopes it will really run out of the box, sadly it requires some effort and knowledge to run under FreeNAS. It would be useful to understand whether support for FreeBSD is planned or investment into setting OnlyOffice up on a virtual machine / using emulation is the only way to go.

**Comment by mzary** [comment]
I am getting sometimes this error while running it on FreeBSD:
linux: pid 4665 (V8 WorkerThread): futex stuff in thread_detach failed.
This has appeared for the first time on Community Document Server  v0.1.8.
