### ISSUE TITLE
unable to use the onlyoffice

### ISSUE THREAD

**Issue by Darkmagister** [nextcloud/documentserver_community#76]
Hello, i've updated my nextcloud installation to 18.0.01 
after having the issue with timeout (i've manually downloaded the package and installed in the apps folder) after enabling the connector (already with the documentserver url) it can connect i can select which file to associate, but if i try to click on a odt, xls file it ask to download it don't try to open it on the web, there is something that i'm missing? it's the first time that i'm using onlyoffice

thanks

**Comment by icewind1991** [comment]
You also need to install the onlyoffice app
