### ISSUE TITLE
Syncing with destop client causes empty documents 

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/documentserver_community#77]
Nextcloud's Community Document server and only Office apps:

First I activated onlyOffice connector. Then I tried to download Community Document server from the app-store . 
The download of Community-server failed because of **time-out** messages etc. (that was predictable, because the size is about 300 MB !). That's already mentioned in other issues. (Would be great to increase time-out per default and add a progress bar or something else..).

So I did the download of the Document server manually form [here](https://apps.nextcloud.com/apps/documentserver_community/releases?platform=18#18), moved it to the apps folder , set permissions (user www-data is owner of it ) , imported the self-signed Certificate as described [here](https://github.com/nextcloud/documentserver_community) and it worked fine !

So far, everything is ok -only pasting images does not work as described in https://github.com/nextcloud/documentserver_community/issues/64. Inserting images from Desktop/PC's file explorer works well.

Now I can create document files on Nextcloud for example, can download it or make copies of that file and can open it with Microsoft word -everything seems to be alright, but ***the document file on Desktop/PC which is produced by desktop client (win10) when syncing is empty*** ! When I make a copy of original file on Nextcloud, put it in any folder on Nextcloud and let the copy sync with desktop-client, the copy is ok and has the right content (only images are lost sometimes - but inserting images seems to be buggy anyway - as described above )! :roll_eyes:
No errors concerning that problem found in protocol.

Nextcloud 18.0.1
Maria DB 10.4
Redis 4.0.9 (memcache /file locking)
apps latest one
Desktop Client (win10) latest version

:thinking:

Nevertheless:
**_Thanks to Nextcloud team for the great work for us so far !_** 
With kind regards, Joe

**Comment by Luxamman** [comment]
Guess I have the same issue:

ONLYOFFICE in Nextcloud works fine, saves the changes to the (in the browser) opened file, I can reopen it in the browser with the changes made before by ONLYOFFICE in Nextcloud. No problem online/in the browser.

But when I open the same file (synced by the latest client) on the PC with LibreOffice, the file has no changes. So when I save the file in LibreOffice, it's synced back to Nextcloud and overwrites the changes made in ONLYOFFICE. 

So the sync is only working from the PC to the cloud, but not from the cloud to the PC.

Hope this will be gone soon to work with that great feature :)

Nextcloud 18.0.1 with Community Document Server 0.1.5 and ONLYOFFICE 4.1.4. 
Nextcloud Desktop Client Version 2.6.2stable-Win64 (build 20191224)

**Comment by Joe7new** [comment]
Thnx for your comment - I already thought that I was the only one having that sync-problem .
You are right: document syncing with desktop client only works correctly in one direction ! 
I hope this issue will soon be labed as bug. Working with documents and onlyOffice on nextcloud is really a great feature, but buggy syncing with destop client can cause data loss and therefore I also hope that this supposed bug will be fixed in near future !
Regards Joe

**Comment by csarmendariz** [comment]
I have the same problem

**Comment by Joe7new** [comment]
Thnx for comment. Hope that someone of nextcloud-team takes notice of the problem soon !
Joe

**Comment by christianvw** [comment]
Same problem here. Even without syncing to desktop clients this problem appeared.

Editing an excel with the online editor and after that reloading the website causes not editable fields and a few minutes after a blank document.

**Comment by vsandre** [comment]
Same problem as in #12

**Comment by Joe7new** [comment]
ok, I see. Still waiting and hoping that someone of nextcloud-team takes notice of it .. 
Joe

**Comment by Jolopu** [comment]
Same problem here. I can create and edit documents online in OnlyOffice. Then they get saved locally by the Nextcloud Client. When I open the local version the document is blank. The version date always stays at the creation date even if the document is edited online. Sometimes the document can't be opened online in OO anymore. But this seems to be another issue.

I use:
Nextcloud 18.0.2 on a shared hosting - fresh install
Community Document Server 0.1.5
ONLYOFFICE 4.1.4

Because of this, we already suffered from data loss. Stopped using NC/OO until this is resolved.

**Comment by KevID** [comment]
Hi @icewind1991 ,

Big bug with last version 1.0.5, see other issues: #78  #87 

Thanks for your help.

**Comment by caguiar** [comment]
Installed yesterday the Community Document Server and ONLYOFFICE, did some tests and came across the same problem - unfortunately cannot use this feature until it is fixed.

Nextcloud 18.0.2 on own Ubuntu 18.08 server
Community Document Server 0.1.5
ONLYOFFICE 4.1.4

**Comment by KevID** [comment]
The bug comes from the fact that nextcloud doesn't detect the closing of the onlyoffice file. The file is detected as always open, so the recording doesn't run.

**Comment by fabiangebert** [comment]
> The bug comes from the fact that nextcloud doesn't detect the closing of the onlyoffice file. The file is detected as always open, so the recording doesn't run.

According to what you've written: in which project should this bug be tracked and fixed?

**Comment by frabe1579** [comment]
Same problem with Nextcloud 18.0.2 on Docker.

**Comment by Jolopu** [comment]
NC 18.0.3 has been released. Let's see if the issue is solved.

**Comment by timo12357** [comment]
Same here. Really unpleasant bug. Just lost one day's worth of work.

**Comment by Joe7new** [comment]
yes, bug still there in new version...
Great feature, but limited use. 
**still waiting that someone of NC-team at least set the bug label** . Really annoying bug.
Joe

**Comment by Joe7new** [comment]
I openend the issue nearly a month before! Just wait and hope...

**Comment by Joe7new** [comment]
Thnx ! I see..
kind regards, Joe

**Comment by narFnarF** [comment]
It's 2 years later and the issue still occurs.

Here are steps to reproduce the issue with consistancy:

# Steps to reproduce:
1. On Nextcloud, install **Community Document Server** from the Nextcloud app store
2. install the **ONLYOFFICE** app from the same app store
1. In Nextcloud **Files**, create a new .xlsx document and open it.
2. Write something in any cell. Save and close. 
3. Wait 1 minute, just to be sure it has time to save properly.
3. On your computer, install the [Nextcloud Sync client](https://nextcloud.com/install/#install-clients) if it's not already installed.
4. Sync your Nextcloud files to your local computer (you can use the "Force sync now" option just to be sure)
5. In File Explorer (on Windows or whatever OS you use), navigate to the synced folder and to the file created earlier. Right-click and open this file with OnlyOffice (or LibreOffice)
6. Observe that the file is blank.
**Expected result:** The text written in the file at step # 4 should be visible.

# My setup

## OnlyOffice
Desktop version: 7.0.0.127
[OnlyOffice app](https://apps.nextcloud.com/apps/onlyoffice) for Nextcloud: 7.3.0
[Community Document Server](https://apps.nextcloud.com/apps/documentserver_community): 0.1.12

## Nextcloud Server
Version: 22.2.3

### Database:
mysql
8.0.28
267.5 MB

### PHP:
7.4.3
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 2 GB

## Nextcloud Desktop Client
Version 3.4.2 (Windows)

**Comment by kintaro1981** [comment]
is this fixed with this?
https://github.com/nextcloud/documentserver_community/issues/12#issuecomment-2041417850
