### ISSUE TITLE
Show nice warning if OnlyOffice app is not installed.

### ISSUE THREAD

**Issue by ghost** [nextcloud/documentserver_community#8]
After tried to activate the App, I had: OCA\Onlyoffice\AppConfig and the App ist deactivated. Server ist a 18rc2

**Comment by tgurr** [comment]
I'm experiencing the same problem with the just released Nextcloud 18.0.0, here's the formatted log Nextcloud provides:

```
[no app in context] Error: Error: Class 'OCA\Onlyoffice\AppConfig' not found at <<closure>>

 0. /var/www/vhost.server.domain/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\DocumentServer\AppInfo\Application->OCA\DocumentServer\AppInfo\{closure}("*** sensitive parameters replaced ***")
 1. /var/www/vhost.server.domain/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php line 113
    Pimple\Container->offsetGet("OCA\\DocumentSe ... g")
 2. /var/www/vhost.server.domain/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php line 408
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\DocumentSe ... g")
 3. /var/www/vhost.server.domain/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php line 386
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\DocumentSe ... g")
 4. /var/www/vhost.server.domain/htdocs/apps/documentserver_community/lib/AppInfo/Application.php line 84
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\DocumentSe ... g")
 5. /var/www/vhost.server.domain/htdocs/apps/documentserver_community/lib/AppInfo/Application.php line 88
    OCA\DocumentServer\AppInfo\Application->getAutoConfig()
 6. /var/www/vhost.server.domain/htdocs/apps/documentserver_community/appinfo/app.php line 4
    OCA\DocumentServer\AppInfo\Application->register()
 7. /var/www/vhost.server.domain/htdocs/lib/private/legacy/app.php line 266
    require_once("/var/www/vhost. ... p")
 8. /var/www/vhost.server.domain/htdocs/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("documentserver_community")
 9. /var/www/vhost.server.domain/htdocs/lib/private/legacy/app.php line 128
    OC_App::loadApp("documentserver_community")
10. /var/www/vhost.server.domain/htdocs/lib/base.php line 993
    OC_App::loadApps()
11. /var/www/vhost.server.domain/htdocs/index.php line 38
    OC::handleRequest()

GET /apps/files
from xxx by xxx at 2020-01-17T19:46:32+00:00
```
First I thought it maybe because I switched to PHP 7.4 with the update to Nextcloud 18, but it also happens on PHP 7.3.

**Comment by jookk** [comment]
{"reqId":"FdEpt8437Db46ULqEMm8","level":3,"time":"2020-01-17T20:46:04+01:00","remoteAddr":"192.168.1.1","user":"ncuser","app":"no app in context","method":"GET","url":"/apps/files","message":{"Exception":"Error","Message":"Class 'OCA\\Onlyoffice\\AppConfig' not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OCA\\DocumentServer\\AppInfo\\{closure}","class":"OCA\\DocumentServer\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":113,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":408,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":386,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php","line":84,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php","line":88,"function":"getAutoConfig","class":"OCA\\DocumentServer\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/appinfo/app.php","line":4,"function":"register","class":"OCA\\DocumentServer\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":265,"args":["/var/www/nextcloud/apps/documentserver_community/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php","Line":70,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.9","id":"70c"}

**Comment by jookk** [comment]
I tried installing via appstore and downloaded from github to /apps and enabling, but cant enable

debian 10x64
php7.4-fpm
nginx 1.17.x

docker not installed on system - required?

**Comment by kesselb** [comment]
You have https://apps.nextcloud.com/apps/onlyoffice installed?

**Comment by NorryNew** [comment]
Ohhhh noooo, that was not clear for me, i was trapped with one click installation ;-),

**Comment by autoize** [comment]
Agree this should be implemented.  It is confusing.

**Comment by flozi00** [comment]
I just made a clean installation, onlyoffice and document server are installed by default but the error is still coming

**Comment by ostasevych** [comment]
I suggest to suggest to be satisfied interdependency to install onlyoffice when installing community documentserver app. So, both apps are installed, or none.

**Comment by Wikinaut** [comment]
same for me here
