### ISSUE TITLE
Support relative URL for Document Editing Service address

### ISSUE THREAD

**Issue by jernst** [nextcloud/documentserver_community#81]
On home networks, stable DNS and IP addresses are a problem :-)

Depending on the time of day, the phase of the moon, and whatever else, a given Nextcloud installation may be accessed by the user at URLs as varied as:

* `http://192.168.1.2`
* `http://192.168.1.222`
* `http://nextcloud.local`
* `http://nextcloud.ihaveadnsserveryay.com`

To use the document server, a setting for Document Editing Service address has to be given, such as: `http://192.168.1.2/apps/documentserver_community/`.

Unfortunately, the document editor will only come up if Nextcloud was accessed with a compatible URL: `http://192.168.1.2` from the example. If another one is used (e.g. `http://nextcloud.local`, or the IP address changed from one day to the next, we only get error message "ONLYOFFICE cannot be reached. Please contact admin".

So. I don't know how hard or easy this is, but it would be nice if the Document Editing Service address could be given as a relative URL, which is relative to the Nextcloud installation URL, such as `apps/documentserver_community/`. (Ideally also relative to the root context URL of the Nextcloud install, so subdirectories are possible.) And this app would, at run-time, resolve the relative URL into an absolute one.

This would allow the setting of the parameter once, and it would continue to work even if IP addresses and/or hostnames changed.

**Comment by jernst** [comment]
Well, three likes, four years, no progress. :-(

**Comment by chadek** [comment]
Well this is more a network issue, in an https context, you must always use the same url to match the certificates information. You whether temporarly change your hosts file or set an override in your DNS resolver. This shouldn't be reported here anyway, it should be reported to Onlyoffice app (https://apps.nextcloud.com/apps/onlyoffice) but they'll probably give you a similar answer
