### ISSUE TITLE
Errors on x86 Synology Systems

### ISSUE THREAD

**Issue by rkreienbuehl** [nextcloud/documentserver_community#85]
When installing the Document Server on a Nextcloud instance on a Synology System, it is not possible to open any documents within OnlyOffice because of the following errors:

```
./x2t: /lib/libstdc++.so.6: no version information available (required by ./libgraphics.so)
./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58)
./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58)
```

As a quick fix I copied the `libstdc++.so.6` from a Debian into the folder `nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin`.

There is also a topic at the nextcloud-forum: [https://help.nextcloud.com/t/x2t-lib-libstdc-so-6-no-version-information-available/72874](url)

Is there a way to integrate the lib in the package?

Kind regards
Roger

**Comment by Judocrafter** [comment]
How can I fix this? I am relatively new here. I installed the Nextcloud on my Synology.

OCA\DocumentServer\Document\DocumentConversionException: ./x2t: /lib/libstdc++.so.6: no version information available (required by ./libgraphics.so) ./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58) ./x2t: /lib/libstdc++.so.6: no version information available (required by ./libicuuc.so.58) Empty sFileFrom or sFileTo

**Comment by thomaskunze3** [comment]
- Download **libstdc++6_6.3.0-18+deb9u1_amd64.deb** from https://packages.debian.org/de/stretch/amd64/libstdc++6/download
- unpack via i.e 7zip
- Copy **libstdc++.so.6.0.22** from l**ibstdc++6_6.3.0-18+deb9u1_amd64\data.tar\_\usr\lib\x86_64-linux-gnu** to **nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin**
- Rename or symlink **libstdc++.so.6.0.22** to **libstdc++.so.6**
- chown libstdc++.so.6 to your http user
- chmod 644 libstdc++.so.6
