### ISSUE TITLE
Documents get wiped randomly, versioning does not work, ghost users

### ISSUE THREAD

**Issue by christianvw** [nextcloud/documentserver_community#87]
Hi,

we tried to use Nextcloud 18 with OnlyOffice in a production environment but we ran into multiple serious issues which led to a suspension of OnlyOffice from our production servers:

- Documents get wiped randomly. Sometimes the whole document gets blank, sometimes just the latest changes get wiped. Latest changes can mean up to a few hours.
- Due to the not-use of Nextclouds versioning and due to the fact that we are not able to rollback per file individually - these random wipes **result in a data loss**. This is an instant killer in every production environment. Daily backups to an offsite host do not help here when the changes are done in under one day.
- Sometimes (e.g. when you leave the website and open the document again) there are now two users (same account), one of them as a ghost which blocks the field he edited. When this happens the chance of a wipe is near 100% from our experience.

We can reproduce these errors very easily. Please fix this issues. We liked OnlyOffice integrated in Nextcloud and the easy to use UI very much but these issues are heavy.

**Comment by tk7936** [comment]
We have exact same Problem and had to revert back to collabora. 
It seems the files only get changed within Onlyoffice but not on the Nextcloud share, so there is no sync as timestamp never changes and if its edited by multiple people, some changes get saves and some not.
Not really usable.

**Comment by goldgoldfish** [comment]
I am also having the same problem. It makes it very inconvenient to have to download a second copy of the document to ensure the changes have been applied and then sync the file back when move from working offline back to online.

**Comment by KevID** [comment]
I have the same problem with a fresh install with Nextcloud VM (https://github.com/nextcloud/vm), 2 days ago.

I use:
Nextcloud 18.0.2 on a shared hosting - fresh install with Nextcloud VM
Community Document Server 0.1.5

**Comment by Jolopu** [comment]
We have the same problem. We can create and edit documents online in OnlyOffice. Then they get saved locally by the Nextcloud Client. When we open the local version the document is blank. The version date always stays at the creation date even if the document is edited online.
We use:
Nextcloud 18.0.2 on a shared hosting - fresh install
Community Document Server 0.1.5
ONLYOFFICE 4.1.4

We already suffered from data loss and therefore stopped using NC/OO in a production environment until theses severe issues are resolved.

**Comment by RomanSixty** [comment]
Same issues here.

I figured those problems don't stem from OnlyOffice itself but from the Nextcloud connector here. So last week I switched back to a Docker installation of OnlyOffice Community Server (basically [this one](https://github.com/ONLYOFFICE/Docker-CommunityServer/)). I disabled the "Community Document Server" app in Nextcloud and used the URL of my standalone installation in the OnlyOffice Nextcloud app.

Running this setup for a few days now I haven't heard complaints from users about those problems yet. Documents are saved, I didn't encounter ghost users yet and so far no data loss. Compared to the Nextcloud integration it's quite a hazzle to set up, but at least it's running quite stable that way.

**Comment by tk7936** [comment]
Yes its definatly Community Document Server causing the Problem. Unfortunatly there have been no updates to it since January.

**Comment by christianvw** [comment]
We have also had the same experience. With a specially hosted document server we have significantly fewer problems.

We use an nginx reverse proxy and docker / docker-compose. With the following configuration files we got it work.

**docker-compose.yml (onlyoffice document server)**
````
version: 2

services:
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "YOURpassword_123456789"
    expose:
      - "80"
    networks:
      - production-network

networks:
  production-network:
    external: true
````

**nginx.conf (for nginx reverse proxy)**
````
upstream onlyoffice {
  server onlyoffice-documentserver:80;
}

server {
  server_name cloud.domain.com www.cloud.comain.com;
  
  ...
  
  #onlyoffice documentserver
  location ^~ /docs/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host/docs;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass         http://onlyoffice/;
    proxy_redirect     off;
  }
  
  #normal nextcloud
  location / {
    ...
  }
}
````

With this configuration you can access your document server via `https://cloud.comain.com/docs` with your secret set in the `docker-compose.yml` (onlyoffice document server).
