### ISSUE TITLE
Unable to add multiple fonts with shell expansion

### ISSUE THREAD

**Issue by bovender** [nextcloud/documentserver_community#89]
Trying to add multiple TTF fonts with the `occ` script:

```
php occ documentserver:fonts -a /path/to/my/TrueType/IBM-Plex-Sans/*.ttf
```

This fails with the following message:

```
Too many arguments, expected arguments "command".
```

I can add a single TTF font all right, but it's kind of tedious to do this for all IBM Plex fonts...

NC version 18.0.2, documentserver_community: 0.1.5.

Am I doing something wrong, or is it a bug?

**Comment by maexbower** [comment]
No this doesn't seem to be implemented yet. What should work for now is a simple for loop which adds all fonts.
`for font in /path/to/my/TrueType/IBM-Plex-Sans/*.ttf; do php occ documentserver:fonts -add $font; done`
don't forget to run the php command as your webservers user to not mess up with your file ownerships.
