### ISSUE TITLE
Documentserver dont start

### ISSUE THREAD

**Issue by koarlmichael** [nextcloud/documentserver_community#9]
The app **Community Document Server** wont start after download in the app store.

I see this in the nextcloud logfile:

[no app in context] Error: Error: Class ‘OCA\Onlyoffice\AppConfig’ not found at <>

    /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\DocumentServer\AppInfo\Application->OCA\DocumentServer\AppInfo{closure}("*** sensitive parameters replaced ***")
    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 113
    Pimple\Container->offsetGet(“OCA\DocumentSe … g”)
    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 408
    OC\AppFramework\Utility\SimpleContainer->query(“OCA\DocumentSe … g”)
    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 386
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback(“OCA\DocumentSe … g”)
    /var/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php line 84
    OC\AppFramework\DependencyInjection\DIContainer->query(“OCA\DocumentSe … g”)
    /var/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php line 88
    OCA\DocumentServer\AppInfo\Application->getAutoConfig()
    /var/www/nextcloud/apps/documentserver_community/appinfo/app.php line 4
    OCA\DocumentServer\AppInfo\Application->register()
    /var/www/nextcloud/lib/private/legacy/app.php line 266
    require_once("/var/www/nextcl … p")
    /var/www/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile(“documentserver_community”)
    /var/www/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp(“documentserver_community”)
    /var/www/nextcloud/lib/base.php line 993
    OC_App::loadApps()
    /var/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /nextcloud/apps/files
from 192.168.1.1 by +++ at 2020-01-17T20:24:55+01:00

Nextcloud 18,
Debian 10, mariadb, php 7.3.13, apache2

**Comment by NorryNew** [comment]
this is the same?
https://github.com/nextcloud/documentserver_community/issues/8

**Comment by koarlmichael** [comment]
> this is the same?
> #8

Yes!

**Comment by kesselb** [comment]
Closing as duplicate
