### ISSUE TITLE
OnlyOffice removed mobile editing from DocumentServer 5.5.0

### ISSUE THREAD

**Issue by sunjam** [nextcloud/documentserver_community#94]
Here is the error:
![error-onlyoffice](https://user-images.githubusercontent.com/1787238/77018125-9d388200-6939-11ea-9a38-f724cd69401e.jpg)

- [Here is a link to the commit in OnlyOffice](https://github.com/ONLYOFFICE/web-apps/commit/19e4859e1051fe16697272be3bacaacc06cc9f40), which can be reversed.
- [Discussion here on the Nextcloud Forum](https://help.nextcloud.com/t/onlyoffice-removed-mobile-editing-from-version-5-5-0-of-community-document-server/74360)
- [See this issue on OnlyOffice Github](https://github.com/ONLYOFFICE/DocumentServer/issues/805) requesting the functionality be returned to the open source Community DocumentServer.
- [Here is the changelog for the community Document Server](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#550)
    `Mobile editors available only for paid version`
- Nextcloud Community Documentserver is currently using version 5.4.2.x, [as shown in the makefile here](https://github.com/nextcloud/documentserver_community/blob/master/Makefile).
- [OnlyOffice website product comparison](https://www.onlyoffice.com/compare-server-editions.aspx) now describes mobile web applications for the Community DocumentServer as being viewer only.
`Mobile web applications | (viewers only)| --`

**Comment by immanuelfodor** [comment]
This is real bad news for home usage after such strong partnership announcements with Nextcloud. At least lower the price to 10 bucks or something that people might consider to pay. Or change license to allow home usage and make companies pay for theirs.

**Comment by jospoortvliet** [comment]
Well, I think that REMOVING features from an open source product is stupid as it can be re-added very easily. And if somebody provides a patch that re-adds this to the version of 5.5 that we will ship as part of the community document server, we will merge it. There is no legal limit to this...

**Comment by jospoortvliet** [comment]
Yeah, this is uncool, we have to check what's happening. Removing already-available features from an open source product is of course never a good idea as anyone can re-add them :rocket:

**Comment by sunjam** [comment]
[Added a link to the commit](https://github.com/ONLYOFFICE/web-apps/commit/19e4859e1051fe16697272be3bacaacc06cc9f40) in the original post.

**Comment by mageunic** [comment]
Hi on onlyoffice server the solution is : https://help.nextcloud.com/t/onlyoffice-removed-web-mobile-editing-from-version-5-5-0-of-community-document-server/74360/46

**Comment by JasonCoombs** [comment]
OnlyOffice has no choice but to revert this change which attempts to revoke the rights granted under the GNU AGPL.

https://github.com/ONLYOFFICE/web-apps/commit/19e4859e1051fe16697272be3bacaacc06cc9f40#commitcomment-66092641
