### ISSUE TITLE
Spell Check Doesn't Work

### ISSUE THREAD

**Issue by gotmax23** [nextcloud/documentserver_community#97]
I know that spell-checking not working has been reported befiore. I'm wondering whether there has been a change and/or a way to fix it. I would prefer not to have use the docker version and be able to fix this issue with the version that comes with. It does work on the Onlyoffice application that I believe is simply a web-wrapper, though.

Thanks.

**Comment by ostasevych** [comment]
As I have got it is not ported to php version at all.
